### ISSUE TITLE
Unable to return model type from custom resolver

### ISSUE THREAD

**Issue by wasd171** [graphcool/graphcool#1001]
I am referring to this piece of [documentation](https://docs-next.graph.cool/concepts/functions-and-events/resolvers-mu3iar0eiz#shortcuts-to-the-graphql-engine). I would like to create a `getMyself` query which would return the logged in user without needing id. My typings look as the following:
```
extend type Query {
    getMyself: User!
}
```

**Current behavior**
`graphcool deploy` fails with `Schema Extension Error for function 'getMyself': Must provide return type. For example: type MyPayload { someField: Boolean }`

**Expected behavior?**
It should be possible to return model from custom query or mutation.

**Comment by marktani** [comment]
The concepts you're linking to are not quite uptodate. We'll update them soon.
Currently, it's not possible to return model types from resolver functions. You can refer to this example for a query that returns user _data_ (like `id` or `name`): https://github.com/graphcool/templates/blob/master/auth/email-password/

Look at #743 for more information and an in-depth proposal.
