### ISSUE TITLE
Make it easier to create Auth0 users

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool#117]
Maybe a small popup in the Console, that allows you to sign up a new Auth0 user

**Comment by mindeavor** [comment]
Would this be necessary? Auth0 already has a nice interface for creating users in their dashboard.

**Comment by marktani** [comment]
Creating a user in the `User` model with the Auth0 integration is a two-step process:

* obtaining a valid Auth0 id token from *somewhere* (usually Auth0 Lock)
* calling the `createUser` mutation with this token

Creating the user in the Auth0 dashboard will not be synced to Graphcool yet.

**Comment by marktani** [comment]
With custom authentication, this is now possible. Please join the discussion here: https://www.graph.cool/forum/t/feedback-schema-extensions-beta/405.
