### ISSUE TITLE
persist lastLogin inside of User 

### ISSUE THREAD

**Issue by dohomi** [graphcool/graphcool#135]
Hi,

I just compared my old database and saw, that I persisted the `lastLogin`of each user. Would be nice if this could be added to the general handling of the `User` table, beside `updatedAt` and `createdAt`
Cheers

**Comment by marktani** [comment]
Thanks, makes a lot of sense! :+1:

**Comment by marktani** [comment]
This can now be solved with the new "Schema Extensions" feature, for example with a simple adjustment to this [Facebook Login example](https://github.com/graphcool-examples/functions/tree/master/facebook-authentication).

**Comment by marktani** [comment]
This can be further discussed here: https://www.graph.cool/forum/t/feedback-schema-extensions-beta/405.
