### ISSUE TITLE
Return authenticated data on signin request

### ISSUE THREAD

**Issue by mbiqbal** [graphcool/graphcool#139]
The signin response with email auth does not return authenticated data fields. So if i have to get some authenticated data for a user i will have to send another authenticated request. The signin request causes the authentication so why not treat the response as authenticated.

**Comment by marktani** [comment]
This is how the authentication modules in https://github.com/graphcool/modules/tree/master/authentication should be designed once better type support for schema extensions is available. For further questions and discussions on schema extensions that were used to build these modules, please join the discussion in the forum: https://www.graph.cool/forum/t/feedback-schema-extensions-beta/405.
