### ISSUE TITLE
`graphcool local upgrade` should show some (progress) output

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#1505]
Currently running `gc local upgrade` doesn't show any kind of output and therefore seems "stuck" for ~1min.

![image](https://user-images.githubusercontent.com/1567498/34575401-f2294094-f17a-11e7-9e4e-6d20fe66613a.png)

The CLI should show some output and at least a spinner like in the `gc deploy` command.
  
The same is the case for `gc local nuke`.

**Comment by marktani** [comment]
What's your version? It works for me on `1.0.0-beta.3.3`.

**Comment by schickling** [comment]
`graphcool/1.0.0-beta3.3.1 (darwin-x64) node-v8.6.0`
