### ISSUE TITLE
Ability to disable/delete User and File default types

### ISSUE THREAD

**Issue by sonaye** [graphcool/graphcool#151]

**Comment by marktani** [comment]
I agree, we're already looking into this!

Why would this be interesting to you? Is it for "cosmetic" reasons or are the two models hindering your experience in more ways than that? Curious to learn more about your thoughts :slightly_smiling_face:

**Comment by sonaye** [comment]
@marktani For mainly cosmetic reasons is a good way to put it i think, but there is also the "waste of resources" factor on your side as well. If i just created a simple type "Submission" with one field "title" for example, here is what graphcool would generate:
![screen shot 2017-03-31 at 5 17 27 pm](https://cloud.githubusercontent.com/assets/23000873/24554363/f2848b00-1635-11e7-9eb6-a185f7ba5c07.png)

Which i think is a bit too much, not that having these modules is not great, it's just that if you are aiming to become a provider for a much broader community of users with many different use cases, you would consider that some are just interested in the database-related features only of the platform, not auth, not storage, just beautiful graphql data management with a neat console.

You already have an integrations system which is just superb, as a part of your direction of offering more than just graphql, graphql and a suite of services around it to help us as devs build better apps. I imagine it wouldn't be that difficult to migrate those two types to the current integrations ecosystem.

I have decided recently to take jump and use graphql via graphcool in production, started working on the project about a ten days ago, so you should expect more feedback from me on the general experience of the platform :) thanks for the great work.

**Comment by THook** [comment]
On the cosmetic side, I hate clicking on "Schema" and seeing an empty File table every time. Makes me want to create an "A" table just to avoid that frustration :)

**Comment by marktani** [comment]
Thanks for your feedback guys, this is very helpful :slightly_smiling_face: Having separate integrations for the File/User models is a great idea and makes a lot of sense!

**Comment by marktani** [comment]
This is available in the closed CLI beta, please reach out in a PM in the forum to learn more: https://www.graph.cool/forum/u/nilan/activity

**Comment by marktani** [comment]
the current behaviour is as follows (using the CLI beta):

* the `User` and `File` type is not added by default
* once it is added, it cannot be removed anymore
