### ISSUE TITLE
Add TSLint:Disable to generated/graphcool.ts 

### ISSUE THREAD

**Issue by philcockfield** [graphcool/graphcool#1543]
With GraphCool 1.0 a TypeScript file is generated locally after deploy:

    /src/generated/graphcool.ts

This produces typescript that may conflict with the projects `tslint.json` rules.
Can you include a 

    // tslint:disable

directive at the top of the generated file to exclude it from the projects linting output, please?

Thanks.

**Comment by kbrandwijk** [comment]
This issue was moved to supergraphql/graphql-static-binding#32
