### ISSUE TITLE
Unable to do anything in cli after gc local nuke

### ISSUE THREAD

**Issue by lunchboxer** [graphcool/graphcool#1554]
I tried `gc local nuke` in the hopes that it might give me a different answer for a bug I'm encountering and after the command completes I'm now unable to do anything useful with the graphcool-cli. This may not be directly related to nuke itself.

when I run graphcool deploy:
```
 ▸    The CLI version (1.0.0-beta4.0.5) and cluster version (1.0.0-beta3.3) of
 ▸    cluster local do not match. Please use graphcool local
 ▸    upgrade to get the latest cluster.
```
when I run graphcool local upgrade the output suggests everything is kosher:
```
Pulling latest docker image 19.1s
Booting local development cluster 3.3s
```
but graphcool deploy gives the same output.

graphcool list gives two blank lines
graphcool info gives:
```
ERROR: Variable "$input" got invalid value {"workspaceSlug":null,"clusterName":"graphcool-eu1","serviceName":"graphql-boilerplate","stageName":"dev"}; Expected non-nullable type String! not to be null at value.workspaceSlug.

{
  "errors": [
    {
      "message": "Variable \"$input\" got invalid value {\"workspaceSlug\":null,\"clusterName\":\"graphcool-eu1\",\"serviceName\":\"graphql-boilerplate\",\"stageName\":\"dev\"}; Expected non-nullable type String! not to be null at value.workspaceSlug.",
      "locations": [
        {
          "line": 2,
          "column": 17
        }
      ]
    }
  ],
  "status": 400
}
```
What's going wrong here?

**Comment by marktani** [comment]
Hey @lunchboxer,

please install the latest beta and upgrade your local cluster afterwards:

```sh
npm install -g graphcool@beta
graphcool local upgrade
```

This should bring your CLI and local cluster versions back in sync 🙂 
Also, feel free to ping me [in Slack](https://slack.graph.cool) if you need further help with getting your local environment up and running.
