### ISSUE TITLE
CLI: graphcool info does not work on 1.0.0-beta4.0.6

### ISSUE THREAD

**Issue by michaelchiche** [graphcool/graphcool#1555]
**Current behavior**
when doing `graphcool info`, I get this with:
<img width="1760" alt="screen shot 2018-01-09 at 12 05 26 redacted" src="https://user-images.githubusercontent.com/371278/34718101-b718faee-f535-11e7-967e-873d2dd031ae.png">

**Reproduction**

Just install the latest version of the cli.
I used the advanced typescript boilerplate.

`graphcool local upgrade`

`graphcool info`

**Expected behavior?**

it should display de correct data for graphcool info command

**Comment by marktani** [comment]
Which cluster did you deploy to?

**Comment by michaelchiche** [comment]
to the local cluster

**Comment by michaelchiche** [comment]
it now seems solved in the latest 1.0.0-beta4
