### ISSUE TITLE
Subscription doesn't seem to work for asian wss address

### ISSUE THREAD

**Issue by Kisepro** [graphcool/graphcool#1565]
**Current behavior**
Hello,

I have a simple code which subscribes to a query and works for the european cluster.
When I change the wss adress to an asian cluster ( with a replic of the previous database), the updateQuery is never called anymore.

App.js
```
**Reproduction**
const serviceId = `xxxxxxxxxxxxxxxxxxx`;

const httpLink = new HttpLink({ uri: `https://api.graph.cool/simple/v1/${serviceId}` }); 

const wsLink = new WebSocketLink({
  uri: `wss://subscriptions.graph.cool/v1/${serviceId}`, // working for the european ID cluster
  uri: `wss://subscriptions.graph.cool/v1/${serviceId}`, // not working for asian ID cluster
  uri: `wss://subscriptions.ap-northeast-1.graph.cool/v1/${serviceId}`, //address given by playground for the asian cluster.  Not working either
  options: {
    reconnect: true
  }
});

const link = split(
  ({ query }) => {
    const { kind, operation } = getMainDefinition(query);
    console.log("OPERATION");
    console.log(kind);
    console.log(operation);
    return kind === "OperationDefinition" && operation === "subscription";
  },
  wsLink,
  httpLink
);

const client = new ApolloClient({
  link,
  cache: new InMemoryCache(window.__APOLLO_STATE)
});

```

MyComponent.js
```
componentWillMount() {
    this.props.data.subscribeToMore({
      document: VIDEO_SUBSCRIPTION,
      updateQuery: (prev, { subscriptionData }) => {
        console.log("[updateQuery]");
        //console.log(subscriptionData);
        return prev;
      },
      onError: () => {
        console.log("ERRRRRRRRRRROOOOOOOOOOOOOOOOOORRRRRRRR");
      }
    });
  }

const VIDEO_SUBSCRIPTION = gql`
  subscription videoSubscription {
    Video {
      node {
        id
        title
        createdAt
      }
    }
  }
`;

const allVideosQuery = gql`
  query allVideosQuery {
    allVideos(orderBy: createdAt_DESC) {
      id
      createdAt
      title
    }
  }
`;
```

> "apollo-cache-inmemory": "^1.1.5",
>     "apollo-client": "^2.2.0",
>     "apollo-client-preset": "^1.0.6",
>     "apollo-link": "^1.0.0",
>     "apollo-link-context": "^1.0.2",
>     "apollo-link-error": "^1.0.3",
>     "apollo-link-http": "^1.3.2",
>     "apollo-link-ws": "^1.0.0",
>     "apollo-utilities": "^1.0.4",
>     "react": "16.0.0",
>     "react-apollo": "^2.0.4",
>  "graphcool-lib": "^0.1.4",
>     "graphql": "^0.11.7",
>     "graphql-tag": "^2.6.1",

**Comment by marktani** [comment]
What do you mean with "not working"? 🙂 
Do you receive an error message?

Please try directly connecting to your subscriptions endpoint following [these instructions here](https://gist.github.com/marktani/5df524523693c88be425bfb623ca8b8a).

**Comment by Kisepro** [comment]
@marktani By not working, I mean the function "UpdateQuery" is never called anymore, just changing the wss address.

I tried your code but I get an error message in the logs saying "The provided query doesn't include any known model name. Please check for the latest subscriptions API.""

But the behavior is exactly the same for 

- wss://subscriptions.ap-northeast-1.graph.cool/v1/IDASIA

- wss://subscriptions.graph.cool/v1/IDEUROPE

- wss://subscriptions.graph.cool/v1/IDASIA

```

Event {isTrusted: true, type: "open", target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}bubbles: falsecancelBubble: falsecancelable: falsecomposed: falsecurrentTarget: WebSocketbinaryType: "blob"bufferedAmount: 0extensions: ""onclose: nullonerror: nullonmessage: nullonopen: nullprotocol: "graphql-ws"readyState: 1url: "wss://subscriptions.ap-northeast-1.graph.cool/v1/cj9vp039h19vn0148esu3nv31"__proto__: WebSocketdefaultPrevented: falseeventPhase: 0isTrusted: truepath: []returnValue: truesrcElement: WebSocket {url: "wss://subscriptions.ap-northeast-1.graph.cool/v1/cj9vp039h19vn0148esu3nv31", readyState: 1, bufferedAmount: 0, onopen: null, onerror: null, …}target: WebSocket {url: "wss://subscriptions.ap-northeast-1.graph.cool/v1/cj9vp039h19vn0148esu3nv31", readyState: 1, bufferedAmount: 0, onopen: null, onerror: null, …}timeStamp: 859.5450000000001type: "open"__proto__: Event
test (2).html:27 message
test (2).html:28 MessageEvent {isTrusted: true, data: "{"type":"connection_ack"}", origin: "wss://subscriptions.ap-northeast-1.graph.cool", lastEventId: "", source: null, …}bubbles: falsecancelBubble: falsecancelable: falsecomposed: falsecurrentTarget: WebSocket {url: "wss://subscriptions.ap-northeast-1.graph.cool/v1/cj9vp039h19vn0148esu3nv31", readyState: 1, bufferedAmount: 0, onopen: null, onerror: null, …}data: "{"type":"connection_ack"}"defaultPrevented: falseeventPhase: 0isTrusted: truelastEventId: ""origin: "wss://subscriptions.ap-northeast-1.graph.cool"path: []ports: []returnValue: truesource: nullsrcElement: WebSocket {url: "wss://subscriptions.ap-northeast-1.graph.cool/v1/cj9vp039h19vn0148esu3nv31", readyState: 1, bufferedAmount: 0, onopen: null, onerror: null, …}target: WebSocket {url: "wss://subscriptions.ap-northeast-1.graph.cool/v1/cj9vp039h19vn0148esu3nv31", readyState: 1, bufferedAmount: 0, onopen: null, onerror: null, …}timeStamp: 1190.7400000000002type: "message"__proto__: MessageEvent
test (2).html:27 message
test (2).html:28 MessageEvent {isTrusted: true, data: "{"id":"0","payload":{"message":"The provided query…r the latest subscriptions API."},"type":"error"}", origin: "wss://subscriptions.ap-northeast-1.graph.cool", lastEventId: "", source: null, …}bubbles: falsecancelBubble: falsecancelable: falsecomposed: falsecurrentTarget: WebSocket {url: "wss://subscriptions.ap-northeast-1.graph.cool/v1/cj9vp039h19vn0148esu3nv31", readyState: 1, bufferedAmount: 0, onopen: null, onerror: null, …}data: "{"id":"0","payload":{"message":"The provided query doesn't include any known model name. Please check for the latest subscriptions API."},"type":"error"}"defaultPrevented: falseeventPhase: 0isTrusted: truelastEventId: ""origin: "wss://subscriptions.ap-northeast-1.graph.cool"path: []ports: []returnValue: truesource: nullsrcElement: WebSocket {url: "wss://subscriptions.ap-northeast-1.graph.cool/v1/cj9vp039h19vn0148esu3nv31", readyState: 1, bufferedAmount: 0, onopen: null, onerror: null, …}target: WebSocket {url: "wss://subscriptions.ap-northeast-1.graph.cool/v1/cj9vp039h19vn0148esu3nv31", readyState: 1, bufferedAmount: 0, onopen: null, onerror: null, …}timeStamp: 1497.9550000000002type: "message"__proto__: MessageEvent
test (2).html:27 message
test (2).html:28 MessageEvent {isTrusted: true, data: "{"type":"ka"}", origin: "wss://subscriptions.ap-northeast-1.graph.cool", lastEventId: "", source: null, …}
test (2).html:27 message
```

**Comment by marktani** [comment]
You need to adjust [this subscription query](https://gist.github.com/marktani/5df524523693c88be425bfb623ca8b8a#file-subscriptions-html-L21-L29) to a valid subscription query for your service.

**Comment by Kisepro** [comment]
@marktani My bad sorry 

So it's working with your code.

wss://subscriptions.ap-northeast-1.graph.cool/v1/IDASIA   // Working
wss://subscriptions.graph.cool/v1/IDEUROPE   // Working
wss://subscriptions.graph.cool/v1/IDASIA  // Not Working but this is quite normal

**Comment by marktani** [comment]
```
wss://subscriptions.ap-northeast-1.graph.cool/v1/IDASIA // Working
wss://subscriptions.graph.cool/v1/IDEUROPE // Working
wss://subscriptions.graph.cool/v1/IDASIA // Not Working but this is quite normal
```

Yes, this is all expected. `wss://subscriptions.graph.cool/v1/` only works for europe based projects.

This looks like an implementation problem in your client code, so I'm closing this issue. Feel free to create [a new thread in the Forum](https://www.graph.cool/forum/c/questions) if you need help with your code 🙂

**Comment by Kisepro** [comment]
@marktani I know it seems to be from my code but the only thing I change is 2 urls (httplink and wslink).
Maybe it should be something parsing the url ? Or maybe it's part of apollo ?

Working
```
const httpLink = new HttpLink({ uri: `https://api.graph.cool/simple/v1/IDEurope` });

const wsLink = new WebSocketLink({
  uri: `wss://subscriptions.graph.cool/v1/IDEurope`,
  options: {
    reconnect: true
  }
});
```

Not Working
```
const httpLink = new HttpLink({ uri: `https://api.graph.cool/simple/v1/IDAsia` });

const wsLink = new WebSocketLink({
  uri: `wss://subscriptions.ap-northeast-1.graph.cool/v1/IDAsia`,
  options: {
    reconnect: true
  }
});

```
Both urls are working with your subscriptions.html, so it does not come from a url confusion.
The rest of the code is in common.

**Comment by marktani** [comment]
Maybe the `IDAsia` service doesn't expose the correct schema 🙂

**Comment by Kisepro** [comment]
@marktani I have fully redeployed from scratch the same server project, 1 on asia, 1 on europe.
I really don't see where the difference could come from my code, I tried to eliminate all this kind of possible reasons and simplified my code at the maximum.

Anyway, I won't lose my time on it anymore... I will export my data to a european server and try later.

**Comment by Kisepro** [comment]
@marktani Hi,  could you please re-open the issue ?

I re-re-re-re-tested with a virgin project and the basic facebook model.
I tested also with the US cluster, not working either.
Exactly the same than the export problem describe here #1564 and #1570 working only on EU cluster

**Comment by bamne123** [comment]
Can anyone share the working example of Subscription using Apollo 2 for React Native.

My Scenario:
I am using GraphCool shared server with Apollo Client 2.2.0. 
I have subscribed to query which works perfectly on Graphcool Playground. Where i am creating node from Graphcool Playground only.

Where as when i subscribe to same query using SubscribeToMore from my client, UpdateQuery does not get called.
I am not sure weather Websocket is working or not.
I am not able to debug as well.

:weary::weary::weary::weary::weary:

**Comment by Kisepro** [comment]
@bamne123 My example is working when I'm using from the right continent otherwise there is a bug that we can face with graphcool export also
