### ISSUE TITLE
[1.0] Internal Server Error on User relation

### ISSUE THREAD

**Issue by hoodsy** [graphcool/graphcool#1596]
**Current behavior**

When trying to create a relation between `users`, get an internal server error:
```Request ID: api:api:cjcc2ki9u029s015116kgqrlq```

Mutation:
```js
  async follow(parent, args, ctx, info) {
    const auth0Id = await parseUserAuth0Id(ctx)
    return await ctx.db.mutation.updateUser({
      where: { username: args.username },
      data: {
        followers: {
          connect: [{ auth0Id }]
        }
      }
    })
  },
```

**Reproduction**

> If your problem can be reproduced with a certain service definition, please create a new GitHub repository with the reproduction instructions.

**Expected behavior?**

A relation would be created between the authenticated user and the target user.

**Comment by marktani** [comment]
Does this also happen when you talk to your GraphQL API directly?
Also, please enable debug output and share the raw query sent to your GraphQL API.

```js
    db: new Graphcool({
      typeDefs: 'src/generated/graphcool.graphql',
      endpoint: process.env.GRAPHCOOL_ENDPOINT,
      secret: process.env.GRAPHCOOL_SECRET,
      debug: true,
    }),
```

**Comment by hoodsy** [comment]
Here's the output with `debug`:
```
query:
mutation ($_data: UserUpdateInput!, $_where: UserWhereUniqueInput!) {
  updateUser(data: $_data, where: $_where) {
    id
    auth0Id
    email
    email_verified
    username
    name
    picture
    gender
    description
    video
  }
}
operationName: null
variables:
{
  "_data": {
    "followers": {
      "connect": [
        {
          "auth0Id": "auth0|5a4e4dbbcfb31a278933961d"
        }
      ]
    }
  },
  "_where": {
    "username": "logan"
  }
}
Response from http://localhost:60000/homeroom-api/dev:
{
  "updateUser": null
}
```

I'm not sure what you mean by talk directly with my GraphQL API, but I'd be happy to give it a shot.

**Comment by marktani** [comment]
I mean, visiting `http://localhost:60000/homeroom-api/dev` and running `updateUser` with the same values as you do in your resolver.

**Comment by hoodsy** [comment]
Ah ok. Yes just ran and got the same error
