### ISSUE TITLE
Secret doesn't work on initial deploy

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphcool#1602]
When I use a boilerplate, and go to the playground immediately, my secret doesn't work.
Only after I deploy again, it works.

**Comment by timsuchanek** [comment]
Thanks for reporting. Can you post the exact commands that you're executing together with the version?
I tried to reproduce it, but currently can't.
Both choosing a boilerplate and the simple example in `gc init` set the secret correctly for me the first time, when I take the `gc token` output and run the Playground with it.

**Comment by kbrandwijk** [comment]
I will try to reproduce this again.

**Comment by kbrandwijk** [comment]
Unable to reproduce this in the latest version.
