### ISSUE TITLE
graphcool cli should find project by graphcool extension, not hardcoded name

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphcool#1605]
Currently, instead of looking for the project with the graphcool extension pointing at the graphcool.yml file I am deploying, the cli looks for a hardcoded project name `database` in my .graphqlconfig.yml.
This makes using 2 graphcool endpoints impossible, and also limits the naming options.

Please look for the right graphcool.yml by looking at the extension object.

**Comment by schickling** [comment]
This is part of the next release 🎉
