### ISSUE TITLE
Integration with CI (for testing)

### ISSUE THREAD

**Issue by jvbianchi** [graphcool/graphcool#169]
It should be able to create a quick copy of a existing Project just for testing, then teardown afterwards.

**Comment by marktani** [comment]
Thanks for the great suggestion!

For now you can use https://www.graph.cool/graphql-up/ to quickly setup a project based on a [schema file in IDL syntax](https://www.graph.cool/docs/faq/graphql-idl-schema-definition-language-kr84dktnp0/).

Projects created with `graphql-up` are deleted after 30 days of inactivity, so if you don't need to clone the project's data but only the project's schema, that's a great tool to be used for CIs.

**Comment by jvbianchi** [comment]
It would be great if graphql-up could copy the schema from a existing project
