### ISSUE TITLE
Support OAuth 2 Password Grant directly

### ISSUE THREAD

**Issue by wvteijlingen** [graphcool/graphcool#179]
When using the "Graphcool Email + Password" auth provider we can currently sign in using the `signinUser` mutation.

I think it would be a nice addition if we could use the OAuth 2 Resource Owner Password Credentials Grant directly as well. This makes it a lot easier to integrate with existing client side OAuth libraries, without having to go through a third party such as Auth0.

**Comment by changalberto** [comment]
Graphcool, please bump this as priority =)

**Comment by radum** [comment]
Is there a way to achieve this as it is now? This is the only thing that blocks me for moving forward. I need to be able to use my own Node.js server with Passport.js and social logins and I have no clue how I could do this using Graph.cool

Any help will be greatly appreciate it.

**Comment by marktani** [comment]
This can now be implemented using the new beta feature "Schema Extensions". If you're interested in participating in the beta program, please reach out to me in Slack 🙂

**Comment by marktani** [comment]
This is now possible to be built with [resolver functions](https://blog.graph.cool/extend-your-graphcool-api-with-resolvers-ca0f0270bca7). 

If you're implementing this in your project, please provide an example here: https://github.com/graphcool/templates.
