### ISSUE TITLE
Rollback nested mutations if it wasn't fully executed

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool#191]
Currently, when a user doesn't have the right to connect nodes in a relation and uses a nested create mutation, both nodes are created but then not connected because of the expected permission error.

In this case, rolling back the two create mutations would be neat.

**Comment by sedubois** [comment]
Yes this is important. And relates to multiple transactional mutations (#74)?

**Comment by marktani** [comment]
Yep, they are two very similar feature requests, the other one is about multiple GraphQL mutations in the same HTTP request.

**Comment by marktani** [comment]
This is even more important in the case of constraints like required and unique, as discussed [here](https://www.graph.cool/forum/t/rollback-on-large-nested-object-insert/634?u=nilan).

**Comment by sorenbs** [comment]
I'm consolidating discussion of transactions for nested mutation in https://github.com/graphcool/graphcool/issues/597

Please comment on that issue if there are additional areas we need to cover :-)
