### ISSUE TITLE
Firebase Authentication template

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool#192]
A Firebase authentication module should be added to https://github.com/graphcool/templates.

**Comment by jhalborg** [comment]
As discussed with @marktani on Slack, this would be an awesome feature IMO. Not only is it a free(!) alternative to Auth0, but it would also allow users to take advantage of the rest of the Firebase suite seamlessly. Personally I'm not a fan of the Firebase DB for anything else than fairly simple data structures and specific real-time scenarios, given that it's simply a key/value store, so the option to combine the powers of Graphcool with the other Firebase modules would be a godsent for a plethora of projects! I really hope this gets fast-tracked on the roadmap

**Comment by perrosnk** [comment]
Any idea when this will be available? I am really interested int that integration

**Comment by jhalborg** [comment]
@marktani - Can you reveal any plans as to when this will go into WIP/beta? :)

**Comment by gustavopch** [comment]
I would also love this integration! Any news?

**Comment by michaelspeed** [comment]
I would love to contribute to this feature. this would be awesome!

**Comment by marktani** [comment]
This can now be implemented using the new beta feature "Schema Extensions". If you're interested in participating in the beta program, please reach out to me in Slack 🙂

**Comment by FredyC** [comment]
I just want to point out here if this is ever going to be implemented officially (as it probably should), that Firebase Functions should be used for it. First are foremost it minimizes dependency on other services (AWS), but also removes the need to deal with service key which is normally required when verifying Firebase token externally. Here is [an example of minimalistic function](https://gist.github.com/FredyC/e9c79301761859c111b9b1ff6880ff0e#file-firebase-functions-js) that can be automatically deployed to Firebase cloud as part of integration setup process.

**Comment by kbrandwijk** [comment]
@FredyC Could you create an issue in the functions repo to track this?

**Comment by FredyC** [comment]
@kbrandwijk I don't understand how is that related to Graphcool functions? This is an integration with Firebase Authentication. The [Firebase Functions](https://firebase.google.com/docs/functions/) is probably something similar to AWS, just cloud for microservices with an added bonus of direct (admin) access to other parts of Firebase platform.

**Comment by kbrandwijk** [comment]
@FredyC Well, the example in that repo is about Firebase Authentication. If that should be implemented using Firebase Functions, then the Firebase authentication example could be updated to do just that.

**Comment by FredyC** [comment]
@kbrandwijk Ok now it makes sense, but unfortunately I don't have a time & will right now to provide more elaborate example except that gist. If someone feels for that, I am open to questions though (contact me on Graphcool slack).

**Comment by marktani** [comment]
This is now possible to be built with [resolver functions](https://blog.graph.cool/extend-your-graphcool-api-with-resolvers-ca0f0270bca7), have a look here for an example: https://github.com/graphcool/templates.
