### ISSUE TITLE
Local Development Workflow for functions

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool#206]
* version control
* IDE of choice
* combine with CLI?

**Comment by PierBover** [comment]
* testing locally before deploying?

**Comment by marktani** [comment]
As we're using Auth0 Extend, an integration with `wt-cli` is worth considering: ttps://github.com/auth0/extend/wiki/Auth0-Extend-User's-Guide#enabling-command-line-tool-for-your-users

**Comment by lastmjs** [comment]
You might want to look into [lambda-local](https://www.npmjs.com/package/lambda-local). Here's a blog post that might be interesting: https://www.npmjs.com/package/lambda-local

**Comment by lastmjs** [comment]
I would also like to see continuous deployment capabilities, like with the `aws cli`. I want to be able to run all of my tests locally on a CI server, and then have everything pushed to production automatically.

**Comment by lastmjs** [comment]
I'm hoping it can be very simple @marktani, version control and IDE of choice won't be a problem if you just check your functions into git, and if the CLI let's you pass in a file with you function to deploy to production.

**Comment by sorenbs** [comment]
See https://github.com/graphcool/graphcool/issues/797
