### ISSUE TITLE
Return user data in signInUser mutation payload

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool#223]
This saves a roundtrip compared to `signInUser -> user`

**Comment by marktani** [comment]
This is how authentication modules in https://github.com/graphcool/modules should be designed once better type support in custom resolvers is available.

**Comment by sorenbs** [comment]
With the introduction of modules/templates, this is no longer a framework concern.

**Comment by kbrandwijk** [comment]
However, providing the Type support for resolver functions to actually achieve this is...

**Comment by marktani** [comment]
@kbrandwijk right! still, this can further be discussed in #743.
