### ISSUE TITLE
Allow Writing Functions in ES7+

### ISSUE THREAD

**Issue by MrLoh** [graphcool/graphcool#227]
It would be really great if you could allow writing functions in ES7+, since graphcool is mainly for frontend engineers, being able to use a normal `export default` and object destructuring and even stage0 features like object-rest-spread-operator would be really nice, and should just be a babel compile step for you away. 

I was expecting to be able to write something like this:

```js
export default function ({ data }) {
  const slug = data.title.toLowerCase().replace(' ', '-')
  return { data: { ...data, slug } }
}
```

**Comment by PierBover** [comment]
Also async/await...

I cannot imagine going back to writing chains of `then()`.

**Comment by MrLoh** [comment]
`async/await` is even supported by recent node releases, so there's really not that much to compile down. Mainly [object-rest-spread](https://github.com/tc39/proposal-object-rest-spread) is missing, which is something, I got very used to since react enables it by default.

**Comment by pie6k** [comment]
Huge +1. I think it would be great to be able to choose version of ES. Note sure how does it look on your side. But why not just compile code via babel on every save/try like https://babeljs.io/repl/ does.

**Comment by FredyC** [comment]
Personally, I would almost prefer if graphcool would just respect `.nvmrc` to pick NodeJS version and don't provide any kind of transpilation on its own. That way we would know what to expect there instead of relying on some specific setup.

**Comment by notrab** [comment]
Any update on this? Especially using the spread operator? 👍

**Comment by kbrandwijk** [comment]
Spread operator is already supported with 'use latest'

**Comment by marktani** [comment]
ES7 + TypeScript support is now there since version `0.7` of the Framework Preview: https://github.com/graphcool/graphcool/releases/tag/0.7

**Comment by marktani** [comment]
here are some example: https://github.com/graphcool/templates/pull/97

**Comment by kbrandwijk** [comment]
That's not ES7 support, that's babel.
