### ISSUE TITLE
Upgrade node version for inline functions

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool#237]
Should be at least 6+

**Comment by kbrandwijk** [comment]
Is this still an issue? Webtask is now on 6.1.1, so you might be automatically upgraded...

**Comment by dhruska** [comment]
Hey @marktani , anything we can do to help push this along? cc @peterpme

**Comment by peterpme** [comment]
Let's shoot for 8.3! 😄

**Comment by pie6k** [comment]
+1 for 8^

**Comment by mwickett** [comment]
+1 for 8^ as well

**Comment by kbrandwijk** [comment]
Like mentioned before, Auth0 Extend now allows the use of a profile that runs on Node 8, so there's really no reason not to support this anymore.

**Comment by mwickett** [comment]
Running into this issue: https://github.com/sendgrid/sendgrid-nodejs/issues/450 using Sendgrid on an inline function. Seems to related to node version.

**Comment by marktani** [comment]
node 6, ES7 + TypeScript support is now there since version `0.7` of the Framework Preview: https://github.com/graphcool/graphcool/releases/tag/0.7

here are some example: https://github.com/graphcool/templates/pull/97
