### ISSUE TITLE
Allow creating/signing in user with a single mutation

### ISSUE THREAD

**Issue by sedubois** [graphcool/graphcool#27]
For the reasons described here: https://github.com/graphcool/dashboard/issues/294

**Comment by mypark** [comment]
slightly related to issue 25 as well? https://github.com/graphcool/feature-requests/issues/25

**Comment by marktani** [comment]
This is how the authentication modules in https://github.com/graphcool/modules/tree/master/authentication are designed. For further questions and discussions on schema extensions that were used to build these modules, please join the discussion in the forum: https://www.graph.cool/forum/t/feedback-schema-extensions-beta/405.
