### ISSUE TITLE
Single Function Definition for Multiple TRANSFORM_ARGUMENT

### ISSUE THREAD

**Issue by geirman** [graphcool/graphcool#279]
I think it would be quite common to want to use the same `TRANSFORM_ARGUMENT` function for both `Create` and `Update`, such as this example which creates a computed `fullname` from `${firstname}  ${lastname}`

![2017-06-26_1019](https://user-images.githubusercontent.com/1640318/27551742-810c6480-5a59-11e7-9a2d-5a1717c94d92.png)

Same would apply for the doc example for the computed value `area`...

```javascript

module.exports = function (event) {
  console.log('Compute area')
  event.data.area = event.data.width * event.data.length

  return event
}
```

So my request would be to allow functions to be assigned to multiple mutation contexts, not just one at a time as is the case now...
![2017-06-26_0744](https://user-images.githubusercontent.com/1640318/27551907-29479e94-5a5a-11e7-9b13-fe6aeeaa3602.png)

**Comment by kbrandwijk** [comment]
If the Auth0 Extend webtask container would be exposed differently (see https://github.com/graphcool/feature-requests/issues/213#issuecomment-310173026), you could just select an existing webtask on both hooks.

**Comment by marktani** [comment]
The new CLI allows you to reference the same function handler from different functions. More information about this will be announced soon in the Forum!
