### ISSUE TITLE
Add passwordHash option to createUser mutation

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphcool#282]
I use the email/password authentication. I want to approve new users manually. That means I cannot create a `User` node directly, because the user will be able to login directly.

I use an intermediate Type for this, and create the actual `User` by script. The problem is that I can only create a `User` using username and password. This means I have to store the original, unhashed password in my intermediate Type. I do not want this.

Please add the functionality to the `createUser` mutation to create a user using `email` and `passwordHash`.

Without sharing the current password hashing mechanism, that would probably mean creating a field Type for `password` that does the same hashing as the `User` `password` field on the server.

Alternatively, use the `isVerified` field on the `User` Type for all authentication mechanisms. Then all of the above would no longer be necessary...

**Comment by marktani** [comment]
With the new custom autentication, this should be straight forward to be implemented. You can have a look at the `email-password` module as a starting point: https://github.com/graphcool/modules/tree/master/authentication/email-password.
