### ISSUE TITLE
Create 'framework' for integrations

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphcool#291]
It would be great to have a generic 'framework'/ecosystem for integrations, so it's easier for the community to contribute to integrations. An integration could be defined as: 

- Set of Types
- Changes to existing Types
- Configuration options
- Queries and mutations, with their implementations
- ...

Probably related to a set of existing FR's (custom queries/mutations etc.)

**Comment by kbrandwijk** [comment]
Also closely related to https://github.com/graphcool/feature-requests/issues/292

**Comment by CameronK** [comment]
Agreed. I'd love to contribute to community-driven extensions of the platform. Let the Graphcool team focus on the lower-level backend development while the community open-sources solutions to common problems.

**Comment by marktani** [comment]
I think https://github.com/graphcool/modules is exactly what this is about - do you agree, @kbrandwijk?

**Comment by kbrandwijk** [comment]
Yes, this concept will be implemented with the new module system.
