### ISSUE TITLE
Allow developer to define 'modules' inside projects

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphcool#292]
Basically an option to group a certain functionality together, including
- Types
- RP hooks
- SSS
- Permission setup
- In the future, custom queries/mutations

Next step would be to make these modules 'reusable' across projects, or even published as community module

**Comment by marktani** [comment]
Great idea! For now, let's keep them in this repo: https://github.com/graphcool-examples/modules
This is highly related to #213!

A first approach here could be a simple script/command using the CLI that adds all needed components to an existing project configuration. So after these are installed, they are not managed as a separate "module" anymore.

Later, a module concept can be introduced that allows you to manage different parts of your project, reuse it across projects and share with the community in a structured fashion.

**Comment by kbrandwijk** [comment]
Thanks for picking up on this one. I have a basic setup script using the system API that I will share in a separate folder under the modules repo. Could become part of the CLI later on.

**Comment by marktani** [comment]
This is now possible in the new CLI - modules are a simple way to structure code in a project, but there is no package/dependency concept ingrained (yet): https://github.com/graphcool/modules
