### ISSUE TITLE
Consider options to reduce response size

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphcool#304]
I recently found https://github.com/gajus/graphql-deduplicator, it describes a way to reduce response size by removing 'body' fields from duplicate nodes in the response. I think it's a powerful concept, and it would help reduce bandwidth usage a lot for some use cases. It wouldn't help as much as https://github.com/graphcool/api-bugs/issues/110, but it's another possible optimization, especially for mobile.

**Comment by sorenbs** [comment]
It seems to me that this would be interesting if it became more of a standard. It should be supported directly in clients and there should be a way for a client to inform a server to perform the de-duplication. We will not be pursuing this before it sees wider adoption.

Would you be interested in bringing this up with the Apollo/Relay teams to see what they think?

**Comment by kbrandwijk** [comment]
It already works with apollo-client out of the box. Not sure about relay.

**Comment by kbrandwijk** [comment]
On further read (https://github.com/wincent/relay/tree/hack/contrib/lightweight-results) deduplication results were disappointing for most use cases. Gzip is the clear winner here, and supported by the HTTP protocol regardless of GraphQL or any client. So I'll take https://github.com/graphcool/api-bugs/issues/110 over this one :smile:

**Comment by marktani** [comment]
I'll close this for now. If this becomes relevant again, please open a new issue.

See #378.
