### ISSUE TITLE
Including type in event.data in RP

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphcool#323]
I believe there is an inconsistency in the `event` object used in RP. It does not include the object type. For example, the event type is `PostInput`, yet all of it's properties are directly under `event.data`, instead of `event.data.PostInput`.

The reason for asking is that some RP's need to query the Type the RP is defined on. For example, to validate input for a new Post in `TRANSFORM_ARGUMENT`, you might need to query `allPosts`. This *has* to be hardcoded now, because in the RP function, you have no way to determine what type the RP runs for.

I realize this would be a breaking change, but it would be more consistent with query and mutation results to include the Type in the `data` object.

**Comment by sorenbs** [comment]
Hi Kim

I see your use case. Would it make sense for you to add the type information to the context object instead?

**Comment by kbrandwijk** [comment]
I would love to get a context object for RP's, for a number of other reasons (projectId, user authentication context, PAT, just like on SE). For this, it would work, but it might still be inconsistent.
If I use the Relay API, would event.data contain the input object for the mutation, or the seperate fields? In the first case, it's already sort of consistent, and adding it to the context wouldn't hurt.

**Comment by kbrandwijk** [comment]
Further discussion in #750
