### ISSUE TITLE
Allow multiple queries/mutations in one SE

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphcool#326]
It would be easier to deploy, and easier to reuse (helper) functions, if multiple queries/mutations would be allowed in a schema extensions. For inline functions, this can easily be done because multiple `module.exports` are allowed (I tested this before it was disabled).

For external webhooks, this could be solved by passing the name of the query/mutation in either the URL or header for a webhook.

**Comment by marktani** [comment]
This will besolved by #543, so closing it 🙂

**Comment by fabien0102** [comment]
Hello,
just to signal that the doc (https://www.graph.cool/docs/reference/functions/resolvers-su6wu3yoo2) is not up to date :wink:
