### ISSUE TITLE
Add simple way to include server's current time in query payload

### ISSUE THREAD

**Issue by briansayles** [graphcool/graphcool#332]
Certain situations require knowledge of the server's current time at the time a query payload is sent to the client. Specifically, timers that need to be synchronized across different clients whose local times will be different would need this knowledge. 

Per GC support's recommendation, I'm going to implement a workaround by mutating a single Time node and retrieving its updatedAt field value. A simpler solution would be desirable, especially one that would allow the currentServerTime to be appended to a query payload.

**Comment by marktani** [comment]
Thanks for putting this request out there 🙌

**Comment by sorenbs** [comment]
The recently released resolver functions should solve this use case :-)
