### ISSUE TITLE
Support returning an Array from an SE

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphcool#356]
As mentioned https://github.com/graphcool/feature-requests/issues/318#issuecomment-322230474 and https://www.graph.cool/forum/t/returning-an-array-from-a-se/763.

**Comment by marktani** [comment]
closing as duplicate of #435

**Comment by kbrandwijk** [comment]
Usually, duplicates work the other way around... E.g. newer one is usually the duplicate...
