### ISSUE TITLE
Declare function dependencies with a package.json

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool#357]
As mentioned in [this changelog](https://www.graph.cool/forum/t/changelog-week-32-34/737?u=nilan), inline functions currently always resolve the latest available version of a npm package on function creating and updating.

A better mechanism would be to read the versions from a `package.json`.

**Comment by kbrandwijk** [comment]
Or: just switch to the default Auth0 Extend editor, that allows you to select npm modules with specific versions as dependencies: https://auth0.com/extend/docs/libraries/extend-editor#npm-modules. Added benefits: settings meta values, secrets, etc. (see other FR's)...

**Comment by marktani** [comment]
This is now implemented for 0.7: #800
