### ISSUE TITLE
Require specific version of NPM module

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphcool#364]
Webtask.io and Auth0 Extend allows you to require a specific version of a NPM module using the `require('module@x.y.z')` syntax. However, this breaks on Graphcool, so it must be something specific to Graphcool. Then again, multiple versions of the same npm module exists on the environment. For example:
`https://wt-graphcool.it.auth0.com/api/env/node/modules/nodemailer` returns:
```json
[{"name":"nodemailer","version":"2.5.0","state":"available"},
{"name":"nodemailer","version":"4.1.0","state":"available"},
{"name":"nodemailer","version":"0.2.0","state":"available"},
{"name":"nodemailer","version":"1.5.1","state":"available"},
{"name":"nodemailer","version":"2.0.0","state":"available"},
{"name":"nodemailer","version":"2.7.2","state":"available"},
{"name":"nodemailer","version":"3.1.8","state":"available"},
{"name":"nodemailer","version":"4.0.0","state":"available"},
{"name":"nodemailer","version":"4.0.1","state":"available"}]
```
Yet, there's no way to specify which version you want.

Error in the console:
```
Uncaught (in promise) TypeError: Cannot read property 'split' of undefined
    at i (582f6c9c0cd5dd68bce7dbbf071c58343e73eea2.js:1)
    at u._constructComponentWithoutOwner (582f6c9c0cd5dd68bce7dbbf071c58343e73eea2.js:1)
    at u._constructComponent (...
```

By the way, this does *not* require the use of package.json (like the other FR), that's why I created this as a seperate FR.

**Comment by kbrandwijk** [comment]
Apparently, using the syntax `import nodemailer from 'nodemailer@2.5.0'` (for example), together with 'use latest', appears to work! So, not really as issue if it's properly documented.

**Comment by schickling** [comment]
We'll soon adjust the default function environment of Graphcool which will allow you to support specific versions of NPM packages.

**Comment by sorenbs** [comment]
The `import nodemailer from 'nodemailer@2.5.0'` syntax is not explicitly supported by the function runtime, and should not be used. It might break in the future.

As Johannes said, we will support an explicit package.json file in the future and seamlessly migrate existing functions to use this.

**Comment by sorenbs** [comment]
Closing in favor of https://github.com/graphcool/graphcool/issues/357
