### ISSUE TITLE
isomorphic fetch has a blank response.json()

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#379]
<a href="https://github.com/kguller"><img src="https://avatars1.githubusercontent.com/u/1985853?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kguller](https://github.com/kguller)**
_Tuesday Jun 13, 2017 at 17:01 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/117_

----

**What is the current behavior?**
When using a Request Pipeline Function on PRE_WRITE stage using an inline function I ran into issues using the isomorphic-fetch library.  I made a basic GET call to a test REST api that is fully tested.  I wrapped the fetch in a Promise as suggested and all of my event data was returned properly, but the response from fetch always returns an empty object.  response.text() and response.json() both return an empty object, however the status and statusText are correct with 200 and OK.

**What is the expected behavior?**
response.json() should return the json displayed in the Postman screenshot:
```
{
  "userId": 1,
  "id": 1,
  "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
  "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
}
```

![image](https://user-images.githubusercontent.com/1985853/27094181-1be39a14-501e-11e7-93e9-3046bdefc8d0.png)

**If the current behavior is a bug, please provide the steps to reproduce it.**

Here is my source code screenshot and code.
![image](https://user-images.githubusercontent.com/1985853/27094378-bb670990-501e-11e7-96a8-33cd85a6be38.png)

EXAMPLE EVENT
```
{
  "data": {
    "createdAt": "2017-06-12T04:35:15.553Z",
    "id": "cj3tnaq5d00003i5wt45s4vg5",
    "request": {"method":"product.get"},
    "response": {},
    "updatedAt": "2017-06-12T04:35:15.553Z"
  },
  "context": {
    "headers": {}
  }
}
```

INLINE FUNCTION
```js
require('isomorphic-fetch');
module.exports = function (event) {
 
  var api = "http://jsonplaceholder.typicode.com/posts/1"

  return new Promise((resolve, reject) => {
    fetch(api, {
      method: 'get',
      headers: {
        'Content-Type': 'application/json; charset=utf-8'
      }
    }).then((response) => {
      event.data.response = {"test":"tested", "json":response.json()}
      resolve(event)
    }).then((data) => {
      resolve({error: 'Could not finish mutation, because only movies exist.'})
    }).catch((error) => {
      console.log(error)
      resolve({error: 'Could not connect to API'})
    })
  })  
}
```

**Comment by schickling** [comment]
<a href="https://github.com/dhruska"><img src="https://avatars3.githubusercontent.com/u/2578537?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dhruska](https://github.com/dhruska)**
_Monday Aug 14, 2017 at 20:49 GMT_

----

I am having this issue as well, with both `isomorphic-fetch` and `node-fetch`.

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Monday Aug 14, 2017 at 21:14 GMT_

----

I cannot say for sure what is happening here, but the extra Promise wrapper is not needed. This works:

```js
require('isomorphic-fetch');
module.exports = function (event) {
 
  var api = "http://jsonplaceholder.typicode.com/posts/1"
  
  return fetch(api, {
      method: 'get',
      headers: {
        'Content-Type': 'application/json; charset=utf-8'
      }
    }).then((response) => {
    	return response.json()
    }).then((data) => {
      console.log(data)
      return {error: 'Could not finish mutation, because only movies exist.'}
    }).catch((error) => {
      console.log(error)
      return {error: 'Could not connect to API'}
    }) 
}
```

Could you share your code, @dhruska?

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Monday Aug 14, 2017 at 21:15 GMT_

----

Ah, interestingly, `response.json()` returns a promise, so that's probably related.

**Comment by schickling** [comment]
<a href="https://github.com/dhruska"><img src="https://avatars3.githubusercontent.com/u/2578537?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dhruska](https://github.com/dhruska)**
_Monday Aug 14, 2017 at 21:52 GMT_

----

@marktani Ha, yeah that was definitely the problem! My code is very similar to the snippet you posted. The following is working for me:

```
const fetch = require('isomorphic-fetch')

module.exports = function (event) {
  return fetch(API_URL)
    .then((response) => {
      return response.json()
    })
    .then((response) => {
      console.log(response)
    })
    .catch(err => console.log(err))
}
```

**Comment by marktani** [comment]
The original problem can be fixed returning the `response.json()`:

```
.then((response) => {
  return response.json()
})
.then((json) => {
  event.data.response = {"test": "tested", "json": json}
  resolve(event)
})
```
