### ISSUE TITLE
Relay Modern schema does not generate the correct enums

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#382]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Monday Jun 19, 2017 at 12:05 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/126_

----

**What is the current behavior?**

Given this schema:

```graphql
type Post {
  title: String
  type: PostType 
}

enum PostType {
  A,
  B
}
```

The Relay Schema will looks somewhat like this:

```
input CreatePost {
  title: String
  enum: POST_POST_TYPE
}

enum POST_TYPE {
  A,
  B
}
```

instead of

```
input CreatePost {
  title: String
  enum: PostType
}

enum PostType {
  A,
  B
}
```

That happens both when exporting the schema with `get-graphql-schema` as well as the export schema feature in the Console.

**Comment by sorenbs** [comment]
@marktani Was this resolved by our recent enum changes?

**Comment by marktani** [comment]
Yes, it was 🙂
