### ISSUE TITLE
Change default region to us-west-2

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#387]
<a href="https://github.com/sorenbs"><img src="https://avatars3.githubusercontent.com/u/281337?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sorenbs](https://github.com/sorenbs)**
_Thursday Jun 22, 2017 at 09:43 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/135_

----

Change default region to us-west-2

**Comment by sorenbs** [comment]
This is handled by CLI and Console. The console already uses ping time to decide the region.
