### ISSUE TITLE
function invocations are not tracked and no logs are being created for functions in AP and US regions

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#392]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Sunday Jun 25, 2017 at 17:06 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/146_

----

**What is the current behavior?**

SSS function invocations are not tracked and no logs are being created.

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**

Add a new type:

```graphql
type Post implements Node {
  id: ID! @isUnique
  title: String!
  createdAt: DateTime!
  updatedAt: DateTime!
}
```

Create a new SSS:

```graphql
subscription {
  Post(filter: {
    mutation_in: [CREATED, UPDATED, DELETED]
  }) {
    updatedFields
    node {
      id
    }
  }
}
```

```js
// Click "EXAMPLE EVENT" to see whats in `event`
module.exports = function (event) {
  console.log('Received event')
  console.log(event.data)
}

```

**If applicable, share the query, mutation or subscription for reproduction**

Create a new post:

```graphql
mutation {
  createPost(title: "") {
    id
  }
}
```

No logs or invocations are shown in the functions view.

**What is the expected behavior?**

An invocation and a log entry should be visible in the Console.

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Monday Jul 17, 2017 at 20:24 GMT_

----

I am getting logs and invocations on SSS. Is there a special case where it doesn't work?
![image](https://user-images.githubusercontent.com/852069/28288304-11e38718-6b3f-11e7-9599-7221b4a9edb5.png)
![image](https://user-images.githubusercontent.com/852069/28288319-1ce82ce0-6b3f-11e7-8328-d6d332cd2423.png)

Update: also unable to reproduce using the exact example from above.

**Comment by schickling** [comment]
<a href="https://github.com/CameronK"><img src="https://avatars2.githubusercontent.com/u/424892?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [CameronK](https://github.com/CameronK)**
_Monday Jul 17, 2017 at 20:50 GMT_

----

I'm also receiving logs for SSS.

(Why stealth introduce a bug when you can stealth introduce a fix?)

**Comment by schickling** [comment]
<a href="https://github.com/mikenikles"><img src="https://avatars3.githubusercontent.com/u/788827?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mikenikles](https://github.com/mikenikles)**
_Tuesday Jul 18, 2017 at 03:30 GMT_

----

Odd, I re-tested my function and don't see any logs. 
![image](https://user-images.githubusercontent.com/788827/28299523-ab16d89c-6b2e-11e7-8b3c-cff3bf6cd3b5.png)

The function definitely gets called. It sends a message to Slack and I receive that message.

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Tuesday Jul 18, 2017 at 06:45 GMT_

----

@mikenikles Are you using any Promises or callbacks, but don't return them from your function?

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Tuesday Jul 18, 2017 at 22:12 GMT_

----

I have tested this, and it seems this only works for EU region, but I'm not sure. 

@mikenikles can you confirm you're not on EU region, and can you easily retest on EU?
@CameronK is the project where it works on EU region?

**Comment by schickling** [comment]
<a href="https://github.com/CameronK"><img src="https://avatars2.githubusercontent.com/u/424892?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [CameronK](https://github.com/CameronK)**
_Tuesday Jul 18, 2017 at 22:48 GMT_

----

@kbrandwijk I just took another look and I believe I was partially incorrect previously; some of my SSS functions return logs, while others don't. Take a look at this:

![image](https://user-images.githubusercontent.com/424892/28342911-40015642-6be0-11e7-943e-b9b21c068ac6.png)

See the spike in invocations for the second function (Pre-create Person): all 417 of those were called from the script defined by the webhook in the first function (Post-create ImportJob). Note that the first function does not record an invocation.

I took a look at my logs on AWS - that particular invocation ran operations for 30 seconds, including the saving of those 417 records. It looks like an error occurred *after* the save, though.

Just ran another test on the lower two SSS' and they worked fine:
![image](https://user-images.githubusercontent.com/424892/28343092-33f98a26-6be1-11e7-8d15-af9f6b119c64.png)

Both of those execute much shorter, simpler operations.

So in my case, it looks like this occurs due to either:
1) some sort of timeout (the invocation took 30s+)
2) the invocation returning an error (in my case, the error inside the Lambda function was converted to a 500 response)

**Comment by schickling** [comment]
<a href="https://github.com/mikenikles"><img src="https://avatars3.githubusercontent.com/u/788827?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mikenikles](https://github.com/mikenikles)**
_Tuesday Jul 18, 2017 at 22:55 GMT_

----

@kbrandwijk I don't think I ever selected a region 🤔. Is there a simple way to verify which region I'm on? I'm based at the west coast in North America, so if the region is based on where I signed up from, I wouldn't be on EU.

My function is copied from the examples, it simply:

```js
var slack = require('slack-notify')(SLACK_WEBHOOK_URL)

module.exports = function (event) {
  console.log('New user signed up for preview:')
  console.log(event.data.SignUpPreview.node)

  slack.send({
   text: ('New User Sign Up:\nCreated at: ' + event.data.SignUpPreview.node.createdAt + '\nEmail: ' + event.data.SignUpPreview.node.email),
   unfurl_links: 1,
  })
}
```

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Tuesday Jul 18, 2017 at 22:56 GMT_

----

@CameronK on *inline* functions, I had all kinds of response codes logged as error in the logs (502, 400, and what not). Maybe that's different for external webhooks though. The reason why that particular SSS doesn't log, might be a second issue altogether, because it *does* say '10 days ago', so at one point, the invocation *was* logged. Regarding the region, are you on EU?

**Comment by schickling** [comment]
<a href="https://github.com/CameronK"><img src="https://avatars2.githubusercontent.com/u/424892?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [CameronK](https://github.com/CameronK)**
_Tuesday Jul 18, 2017 at 22:57 GMT_

----

@mikenikles If you didn't select a region, you're likely on the EU region - that was the only one available until about a month ago, I believe. (here's more info: https://www.graph.cool/docs/blog/introducing-regions-and-better-performance-she7yaab6l/)

@kbrandwijk I'm currently on EU.

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Tuesday Jul 18, 2017 at 23:00 GMT_

----

@mikenikles The only way I know how to check, is go to the schema view with the devtools network tab open, select the first system call, open the response, and expand the project details:
![image](https://user-images.githubusercontent.com/852069/28343432-9f972630-6c1d-11e7-8397-6fd1621a2c54.png)
You'll notice the region field in there.

**Comment by schickling** [comment]
<a href="https://github.com/mikenikles"><img src="https://avatars3.githubusercontent.com/u/788827?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mikenikles](https://github.com/mikenikles)**
_Tuesday Jul 18, 2017 at 23:05 GMT_

----

Cool, looking at that in my dev tools, it shows `US_WEST_2`

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Tuesday Jul 18, 2017 at 23:06 GMT_

----

@mikenikles slack.send() actually accepts a callback as second parameter. That might cause it to not finish nicely. Could you try returning a Promise, like below (inline edited, so untested)?
```
var slack = require('slack-notify')(SLACK_WEBHOOK_URL)

module.exports = function (event) {
  console.log('New user signed up for preview:')
  console.log(event.data.SignUpPreview.node)

  return new Promise(function (resolve,reject) {
    slack.send({
   text: ('New User Sign Up:\nCreated at: ' + event.data.SignUpPreview.node.createdAt + '\nEmail: ' + event.data.SignUpPreview.node.email),
   unfurl_links: 1,
  }, function() { resolve({data: event.data}) })
  }
}
```

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Tuesday Jul 18, 2017 at 23:09 GMT_

----

@mikenikles if my theory is correct, that Promise probably won't help. Can you create an empty SSS, just with the default function, and see if that logs anything?

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Tuesday Jul 18, 2017 at 23:15 GMT_

----

Another observation, I can confirm the region-specific behavior for both internal functions and external webhooks.

**Comment by schickling** [comment]
<a href="https://github.com/mikenikles"><img src="https://avatars3.githubusercontent.com/u/788827?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mikenikles](https://github.com/mikenikles)**
_Wednesday Jul 19, 2017 at 03:38 GMT_

----

@kbrandwijk Thanks for the suggestions, I created an empty SSS with the default inline function.

**Subscription Query**
```graphql
subscription {
  SignUpPreview(filter: {
    mutation_in: [CREATED, UPDATED, DELETED]
  }) {
    updatedFields
    node {
      id
    }
  }
}
```

**Inline Code**
```js
// Click "EXAMPLE EVENT" to see whats in `event`
module.exports = function (event) {
  console.log('Received event')
  console.log(event.data)
}
```

I created a new record for the `SignUpPreview` type, but don't see any invocations or logs. I know the filter works because the Slack function I have uses the same subscription query and messages arrive in Slack as expected.

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Wednesday Jul 19, 2017 at 17:28 GMT_

----

@mikenikles That is yet another confirmation that it has nothing to do with the SSS itself, but most likely with the region of the project. Let's hope @marktani can confirm this as the underlying issue.

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Thursday Jul 20, 2017 at 09:36 GMT_

----

Thanks for the additional digging, everyone! 🙏  We'll have to further investigate this on our end, but currently I believe your assumption is correct.

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Thursday Aug 10, 2017 at 16:31 GMT_

----

I confirmed that this is also the case for request pipeline functions in the US region.

**Comment by sorenbs** [comment]
@dpetrick Did our recent infrastructure change fix this issue?

**Comment by kbrandwijk** [comment]
I had an exceptional SE invocation registered on a US project, once, about 12 hours ago. Nothing after that, and nothing for RP.

**Comment by marktani** [comment]
Function logs and invocation trackers work across all regions again. Thanks for your patience everyone! 🙏
