### ISSUE TITLE
Multiple subscription mutation types don’t work

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#400]
<a href="https://github.com/heymartinadams"><img src="https://avatars2.githubusercontent.com/u/11673745?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [heymartinadams](https://github.com/heymartinadams)**
_Tuesday Jul 04, 2017 at 14:32 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/164_

----

**What is the current behavior?**
A subscription only appears to get fired for one `mutation` type, not another, if a subscription contains both. This issue might possibly be related to #162.

**If applicable, share the query, mutation or subscription for reproduction**
```javascript
this.connectionsUpdateSubscription = this.props.gqlDataQuery.subscribeToMore({
  variables: { userId: this.props.state.user.id },
  document: gql`gqlConnectionsSubscription`,
  updateQuery: (previousState, { subscriptionData }) => {
    const { mutation, node, previousValues } = subscriptionData.data.Connections
    switch (mutation) {
    case 'UPDATED': return { gqlConnections: previousState.gqlConnections.concat([node]) }
    case 'DELETED': return { gqlConnections: previousState.gqlConnections.filter(connection => (connection.id !== previousValues.id)) }
    default: return { gqlConnections: previousState.gqlConnections }
    }
  },
  onError: (err) => console.error(err)
})
```

with `gqlConnectionsSubscription` being:

```graphql
subscription($userId: ID!) {
  Connections(filter: {
    OR: [
      {
        mutation_in: [UPDATED]
        updatedFields_contains: "complete"
        node: { source: { id: $userId } }
      }, {
        mutation_in: [UPDATED]
        updatedFields_contains: "complete"
        node: { target: { id: $userId } }
      }, {
        mutation_in: [DELETED]
        node: { source: { id: $userId } }
      }, {
        mutation_in: [DELETED]
        node: { target: { id: $userId } }
      }
    ]
  }) {
    mutation
    updatedFields
    node {
      id
    }
    previousValues {
      id
    }
  }
}
```

**What is the expected behavior?**
The `subscription` should work for both `UPDATED` and `DELETED` mutations, but with this code above only appears to work for `UPDATED` mutations.

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Tuesday Jul 04, 2017 at 15:08 GMT_

----

Thanks for the report! Can you share some mutations that are expected to trigger this subscription but don't? For easier reproduction, I'd prefer "raw" GraphQL queries and mutations rather than embedded in Apollo 🙂

**Comment by schickling** [comment]
<a href="https://github.com/heymartinadams"><img src="https://avatars2.githubusercontent.com/u/11673745?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [heymartinadams](https://github.com/heymartinadams)**
_Wednesday Jul 05, 2017 at 00:34 GMT_

----

> For easier reproduction, I'd prefer "raw" GraphQL queries and mutations rather than embedded in Apollo 🙂

Do you mean like this (remember, I’m a junior dev, slow to learn the terms 😊):

```javascript
this.connectionsSubscription = this.props.gqlDataQuery.subscribeToMore({
  variables: { userId: this.props.state.user.id },
  document: gql`
    subscription($userId: ID!) {
      Connections(filter: {
        OR: [
          {
            mutation_in: [UPDATED]
            updatedFields_contains: "complete"
            node: { source: { id: $userId } }
          }, {
            mutation_in: [UPDATED]
            updatedFields_contains: "complete"
            node: { target: { id: $userId } }
          }, {
            mutation_in: [DELETED]
            node: { source: { id: $userId } }
          }, {
            mutation_in: [DELETED]
            node: { target: { id: $userId } }
          }
        ]
      }) {
        mutation
        updatedFields
        node {
          id
          source {
            id
          }
          target {
            id
          }
        }
      }
    }
  `,
  updateQuery: (previousState, { subscriptionData }) => {
    const { mutation, node, previousValues } = subscriptionData.data.Connections
    switch (mutation) {
    case 'UPDATED': return { gqlConnections: previousState.gqlConnections.concat([node]) }
    case 'DELETED': return { gqlConnections: previousState.gqlConnections.filter(connection => (connection.id !== previousValues.id)) }
    default: return { gqlConnections: previousState.gqlConnections }
    }
  },
  onError: (err) => console.error(err)
})
```

When I have this subscription, only `UPDATED` subscription is triggered.

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Wednesday Jul 05, 2017 at 12:21 GMT_

----

In this case, I referred to the plain GraphQL subscription:

```graphql
subscription($userId: ID!) {
      Connections(filter: {
        OR: [
          {
            mutation_in: [UPDATED]
            updatedFields_contains: "complete"
            node: { source: { id: $userId } }
          }, {
            mutation_in: [UPDATED]
            updatedFields_contains: "complete"
            node: { target: { id: $userId } }
          }, {
            mutation_in: [DELETED]
            node: { source: { id: $userId } }
          }, {
            mutation_in: [DELETED]
            node: { target: { id: $userId } }
          }
        ]
      }) {
        mutation
        updatedFields
        node {
          id
          source {
            id
          }
          target {
            id
          }
        }
      }
    }
```

And it would be very useful to see the mutations that you expect to trigger this subscription in the two `DELETED` cases 🙂

**Comment by schickling** [comment]
<a href="https://github.com/heymartinadams"><img src="https://avatars2.githubusercontent.com/u/11673745?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [heymartinadams](https://github.com/heymartinadams)**
_Wednesday Jul 05, 2017 at 17:10 GMT_

----

I used this mutation:
```graphql
mutation($connectionId: ID!) {
  deleteConnection: deleteConnections(id: $connectionId) {
    id
  }
}
```

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Thursday Jul 06, 2017 at 08:48 GMT_

----

Could you please try if that subscription works as expected:

```graphql
subscription($userId: ID!) {
  Connections(filter: {
    mutation_in: [DELETED]
    node: {
      target: {
        id: $userId
      }
    }
  }) {
    mutation
    previousValues {
      id
    }
  }
}
```

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Thursday Jul 06, 2017 at 15:51 GMT_

----

Sorry for the back and forth here, but could you try to reproduce this behaviour in the GraphQL Playground? [Similar issues](https://github.com/graphcool/api-bugs/issues/167 ) look like a problem in the client and not the backend and I'd like to eliminate this option here.

**Comment by sorenbs** [comment]
@heymartinadams We have fixed an issue that caused a similar behaviour. Please reopen this ticket if you can still reproduce the issue :-)

**Comment by heymartinadams** [comment]
Awesome, thanks @sorenbs!

**Comment by cameronrll** [comment]
Hi, I believe I am having a similar issue to the one above, for one of my models, the DELETED "listener" on the subscription is never triggered, both in app and playground. However for my other models it works fine, and I have no idea why. I have tried removing and adding the model which does not work, however now I am out of ideas

**Comment by kbrandwijk** [comment]
@cameronrll Do you also have a subscription query for multiple mutation types, like the OP? Otherwise, you might create a new issue instead.
