### ISSUE TITLE
Can't require modules with a slash in inline functions

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#402]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Friday Jul 07, 2017 at 13:08 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/170_

----

**What is the current behavior?**

Requiring a module like `require('core-js/fn/regexp/escape')` or `require('mandrill-api/mandrill')` doesn't work. The function can't be created.

**What is the expected behavior?**

The function should be created and the module resolved correctly.

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Monday Jul 24, 2017 at 16:34 GMT_

----

Using `'use latest'` and the `import mandrill from 'mandrill-api/mandrill'` syntax, this works.
Using the `require(...)` syntax, it doesn't.

So for importing submodules, use the `import ... from ...` syntax only.

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Saturday Aug 12, 2017 at 21:17 GMT_

----

Is this still a bug, or just something that needs to be documented?

**Comment by sorenbs** [comment]
The real fix for this is to introduce explicit dependency declaration using a standard `package.json`. We aim to introduce this in the near future

**Comment by marktani** [comment]
See also #357 🙂

**Comment by marktani** [comment]
declaring dependencies with a `package.json` has been introduced to the Framework in v0.7: #800.
