### ISSUE TITLE
Handle missing data property in returned object in resolver functions gracefully

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#412]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Wednesday Jul 19, 2017 at 16:23 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/195_

----

**What is the current behavior?**

Returning an unexpected shape in a schema extension results in an internal server error.

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**

Setup a new schema extension function like this:

```graphql
type MyPayload {
 success: Boolean!
}

extend type Mutation {
 myMutation(
   argument: String!
 ): MyPayload
}
```

and implement the function:

```js
 return { data: { success: true } }
```

all is well! However, if you use this instead:

```js
 return { data: { badField: true } }
```

you'll receive an internal server error.

**What is the expected behavior?**

Introduce a new error code + message that helps to understand the problem.

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Monday Jul 24, 2017 at 15:32 GMT_

----

In case of a required field, the typical "null bubbling" behaviour is expected as well.

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Friday Aug 11, 2017 at 16:47 GMT_

----

This is now fixed 💚

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Monday Aug 14, 2017 at 18:04 GMT_

----

This still happens when `data` is not part of the returned object:

```
return { success: true }
```

results in an internal server error.

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Tuesday Aug 15, 2017 at 13:38 GMT_

----

@marktani Your last comment triggered something with me. Wouldn't it make more sense if you could return your object from a function, and the system would wrap the return value automatically, or put any thrown errors in the error object?

To prevent breaking changes :wink: you might implement it like this: if top-level return value is `data` then return as is, otherwise wrap in `data { ... }`. That would keep all existing functions working as-is.

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Wednesday Aug 16, 2017 at 08:50 GMT_

----

I actually think the current API is better, as it allows for a unified experience for inline functions and webhooks. In webhooks, there's no way to control how catching errors should be handled.

**Comment by schickling** [comment]
<a href="https://github.com/mattfysh"><img src="https://avatars3.githubusercontent.com/u/470258?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mattfysh](https://github.com/mattfysh)**
_Friday Aug 18, 2017 at 07:57 GMT_

----

Agreed - event in, event out - allows you to compose, which is probably only important for request pipeline functions, but then it makes sense to make input/output consistent across all function types

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Friday Aug 18, 2017 at 09:20 GMT_

----

It's already inconsistent for both, because you return:
```
{ data: { sum: 3 } }
```
And the query result is:
```
{ data: { add: { sum: 3 } } }
```
So it looks like the query `add` returned `{ sum: 3}`, not `{ data: { sum: 3 } }`

**Comment by schickling** [comment]
<a href="https://github.com/mattfysh"><img src="https://avatars3.githubusercontent.com/u/470258?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mattfysh](https://github.com/mattfysh)**
_Friday Aug 18, 2017 at 09:29 GMT_

----

@kbrandwijk I could be wrong, but I think you may be conflating events and queries

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Friday Aug 18, 2017 at 21:39 GMT_

----

@mattfysh What I described was the way you return a value from a SE, and how that translates into the query result. To me, that feels inconsistent. SE's follow the same format as SSS and RP for return values, but for SSS and RP that's not a problem, because those return values are not translated directly into query results, so the issue I mentioned only surfaced since the introduction of SE's.

**Comment by schickling** [comment]
<a href="https://github.com/mattfysh"><img src="https://avatars3.githubusercontent.com/u/470258?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mattfysh](https://github.com/mattfysh)**
_Friday Aug 18, 2017 at 21:55 GMT_

----

If you use the `TRANSFORM_PAYLOAD` hook point of an RP function, that should translate directly into a query response. I think there may be some confusion still around what is a query and what is an event... perhaps it helps to express it as:

`response.data[operationName] = fn(event).data`

Where:

* `response` is your JSON HTTP response
* `event` is the type of object that is both an input and an output of a Graphcool Function (`fn`)
* `operationName` is defined alongside your function name in the GraphQL function editor - it's defined either in your `extend Query/Mutation` code, or when you selected the event trigger e.g. User is Created / `createUser`

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Friday Aug 18, 2017 at 22:04 GMT_

----

I meant that the query response inserts the operation name between the `data` node and the result object.

**Comment by schickling** [comment]
<a href="https://github.com/mattfysh"><img src="https://avatars3.githubusercontent.com/u/470258?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mattfysh](https://github.com/mattfysh)**
_Friday Aug 18, 2017 at 22:06 GMT_

----

@kbrandwijk sure, I assume that's because the operation name is opaque to the Graphcool Function, it does not deal in operation names, or requests/responses - only events :)

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Friday Aug 18, 2017 at 22:07 GMT_

----

@nilan What's your take on https://github.com/graphcool/api-bugs/issues/195#issuecomment-323304380?

**Comment by marktani** [comment]
The only reason the `data` property is needed as a top-level element, is that you might want to return an `error` instead. At the moment, you can return a field called `error` like so:

```
return { data: error: 2 }
```

and an error like so:

```
return { error: "My Error" }
```

With your suggestion, it wouldn't be possible to distinguish between the two cases.

**Comment by marktani** [comment]
@do4gr what's your state on this issue?

**Comment by do4gr** [comment]
We now have a fix for these:  
* The 'badField' case will now give you an error since you are missing a required field.
* The data object will now be optional if your return type is optional. 

 It should be deployed soon.
