### ISSUE TITLE
Using an invalid type in a schema extension schema results in internal server error

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#413]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Monday Jul 24, 2017 at 09:14 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/199_

----

**What is the current behavior?**

Using an invalid type in a schema extension schema results in internal server error.

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**

Create a new schema extension function with this schema:

```graphql
type MyPayload {
  params: String
}

extend type Query {
  myQuery(
     fakeField: [[Float]]
 ): MyPayload
}
```

The function cannot be saved, because of the invalid type `[[Float]]`.

**What is the expected behavior?**

A useful error message is returned.

**Comment by marktani** [comment]
That should be fixed.
