### ISSUE TITLE
Can't remove default value once set

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#418]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Monday Jul 31, 2017 at 09:51 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/213_

----

**What is the current behavior?**

If you remove the default value from the schema file and resubmit it, the default value will be returned in the final schema.

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**

Start with this:

```graphql
type A implements Node {
  id: ID! @isUnique
  title: String @defaultValue(value: "a")
  createdAt: DateTime!
  updatedAt: DateTime!
}
```

Note that `title` has a `defaultValue`. Now, remove the `defaultValue` and submit:

```graphql
type A implements Node {
  id: ID! @isUnique
  title: String
  createdAt: DateTime!
  updatedAt: DateTime!
}
```

The returned schema will still contain the default value.

**What is the expected behavior?**

The returned schema should not have the default value anymore.

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Wednesday Aug 02, 2017 at 08:51 GMT_

----

Also see https://github.com/graphcool/console/issues/1250

**Comment by sorenbs** [comment]
@do4gr Did we fix this with the recent change to how we handle null values?

**Comment by kbrandwijk** [comment]
Current behavior: Schema change is not applied, no warning or error. You can only do 'reset changes', which puts the default value back in...

**Comment by do4gr** [comment]
We have a fix ready for this and will soon deploy it.

**Comment by marktani** [comment]
This is fixed 🙂
