### ISSUE TITLE
Can create different Type definitions with the same name in two SE

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#420]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Thursday Aug 03, 2017 at 20:51 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/217_

----

**What is the current behavior?**
It's possible to create two SE's with the same Type in them, with a different definition. Both SE's will save correctly. Only the first Type definition is actually used.

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**
SDL 1:
```
type MyPayload { someField: Int }

extend type Query {
  add(a: Int! b: Int!): MyPayload
}
```
SDL 2:
```
type MyPayload { anotherField: Int }

extend type Query {
  sum(a: Int! b: Int!): MyPayload
}
```

This breaks intellisense in the Playground, the Docs only show the first definition, but both queries work with the correct return field (`someField` for `add`, `anotherField` for `sum`)
![image](https://user-images.githubusercontent.com/852069/28943411-05f7431e-789f-11e7-86cd-8675ba2ead1b.png)

**What is the expected behavior?**
The two payload definitions should either be merged (like with gql schema definitions), or the second SE should throw a validation error on save.

**Comment by sorenbs** [comment]
We should return an error on save.

**Comment by kbrandwijk** [comment]
Or allow the extend type syntax? Because this is related to a bunch of other issues, for example that you can't reuse payload types across SE's etc.

**Comment by do4gr** [comment]
We were not correctly checking for duplicate type names and duplicate function names in all cases. We fixed that and you will now get an error on trying to use the same name for two types or functions - even when they are created in the same deploy.
