### ISSUE TITLE
Entering null in nested Mutations results in internal Server Error

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#422]
<a href="https://github.com/do4gr"><img src="https://avatars2.githubusercontent.com/u/16278407?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [do4gr](https://github.com/do4gr)**
_Tuesday Aug 08, 2017 at 17:36 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/223_

----

Bug:
【 code graphql 】
type User implements Node {
  createdAt: DateTime!
  id: ID! @isUnique
  updatedAt: DateTime!
  post: Post @relation(name: "PostOnUser")
}

type Post implements Node {
  id: ID! @isUnique
  title: String! @defaultValue(value: "Hi")
  createdAt: DateTime!
  updatedAt: DateTime!
  user: User @relation(name: "PostOnUser")
}
【 end code 】

This returns an internal server error. For this input, the post argument should just be ignored.

createUser(post: null) {
  id
 }

However, for a required relation, post should be required, so null is not allowed.

**Comment by sorenbs** [comment]
@do4gr Did we fix this already?

**Comment by do4gr** [comment]
Yes, this is fixed.
