### ISSUE TITLE
specific schema changes are not registered using "apply changes"

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#425]
<a href="https://github.com/moksahero"><img src="https://avatars0.githubusercontent.com/u/700960?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [moksahero](https://github.com/moksahero)**
_Wednesday Aug 09, 2017 at 15:42 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/226_

----

**What is the current behavior?**
In Console
1. change relation name in console in two corresponding types
2. click "Preview Changes" to make sure there is no error and button turns "Apply Changes"
3. clicking "Apply Changes" turns the button back to "Preview Changes" nothing else happens

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**
change anything like field name or relation name and try to submit the change

**If applicable, share the query, mutation or subscription for reproduction**

**What is the expected behavior?**
3. clicking "Apply Changes" will make changes to the schema

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Wednesday Aug 09, 2017 at 15:43 GMT_

----

Hey @moksahero, thanks for the report! Could you share your exact schema before and after the change? 🙂

**Comment by schickling** [comment]
<a href="https://github.com/moksahero"><img src="https://avatars0.githubusercontent.com/u/700960?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [moksahero](https://github.com/moksahero)**
_Wednesday Aug 09, 2017 at 15:45 GMT_

----

nothing happens the schema when "Apply Changes" is clicked so before and after schemata are exactly the same

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Wednesday Aug 09, 2017 at 15:46 GMT_

----

Well, this bug only occurs for very specific changes. To be able to reproduce this bug, seeing what exact changes you are trying to apply is very helpful! :) So, the initial schema + the schema that you want to apply is what I mean.

**Comment by schickling** [comment]
<a href="https://github.com/moksahero"><img src="https://avatars0.githubusercontent.com/u/700960?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [moksahero](https://github.com/moksahero)**
_Wednesday Aug 09, 2017 at 15:47 GMT_

----

Before:
type Message implements Node {
  id: ID! @isUnique
  dashboardUser: DashboardUser @relation(name: "MessagesFromDashboardUser")
  channelUser: ChannelUser @relation(name: "MessagesFromChannelUser")
  chat: Chat @relation(name: "MessagesInChat")
  text: String!
  createdAt: DateTime!
  updatedAt: DateTime!
}

type Chat implements Node {
  id: ID! @isUnique
  dashboardUser: DashboardUser @relation(name: "ChatsFromDashboardUser")
  channelUser: ChannelUser @relation(name: "ChatsFromChannelUser")
  messages: [Message!]! @relation(name: "MessagesInChat")
  createdAt: DateTime!
  updatedAt: DateTime!
}

Changes I want to make:
type Message implements Node {
  id: ID! @isUnique
  dashboardUser: DashboardUser @relation(name: "MessagesFromDashboardUser")
  channelUser: ChannelUser @relation(name: "MessagesFromChannelUser")
  chat: Chat @relation(name: "MessageOnChat")
  text: String!
  createdAt: DateTime!
  updatedAt: DateTime!
}

type Chat implements Node {
  id: ID! @isUnique
  dashboardUser: DashboardUser @relation(name: "ChatsFromDashboardUser")
  channelUser: ChannelUser @relation(name: "ChatsFromChannelUser")
  messages: [Message!]! @relation(name: "MessageOnChat")
  createdAt: DateTime!
  updatedAt: DateTime!
}

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Wednesday Aug 09, 2017 at 15:48 GMT_

----

Thanks 🙏  For reference, the change is `MessagesInChat` -> `MessagesOnChat`

**Comment by schickling** [comment]
<a href="https://github.com/moksahero"><img src="https://avatars0.githubusercontent.com/u/700960?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [moksahero](https://github.com/moksahero)**
_Wednesday Aug 09, 2017 at 15:49 GMT_

----

From:
type App implements Node {
  createdAt: DateTime!
  id: ID! @isUnique
  updatedAt: DateTime!
  name: String!
  teams: [Team!]! @relation(name: "TeamOnApp")
  stickers: [String!]
}

To:
type App implements Node {
  id: ID! @isUnique
  name: String!
  teams: [Team!]! @relation(name: "TeamOnApp")
  stickers: [String!]
  createdAt: DateTime!
  updatedAt: DateTime!
}

is also failing

**Comment by schickling** [comment]
<a href="https://github.com/moksahero"><img src="https://avatars0.githubusercontent.com/u/700960?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [moksahero](https://github.com/moksahero)**
_Wednesday Aug 09, 2017 at 15:49 GMT_

----

seems like any changes to this schema is not happening

**Comment by schickling** [comment]
<a href="https://github.com/moksahero"><img src="https://avatars0.githubusercontent.com/u/700960?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [moksahero](https://github.com/moksahero)**
_Wednesday Aug 09, 2017 at 15:50 GMT_

----

For reference, the change is MessagesInChat -> MessageOnChat
To be more precise but yes this is where change needs to happen

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Wednesday Aug 09, 2017 at 15:51 GMT_

----

Hm that's strange, it should say `@isUnique` and not `@isunique` in your schema, maybe that's related?

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Wednesday Aug 09, 2017 at 15:55 GMT_

----

here:

![image](https://user-images.githubusercontent.com/1780597/29131052-df02867e-7d2b-11e7-9d21-ee457d95cc1d.png)

**Comment by schickling** [comment]
<a href="https://github.com/moksahero"><img src="https://avatars0.githubusercontent.com/u/700960?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [moksahero](https://github.com/moksahero)**
_Wednesday Aug 09, 2017 at 15:55 GMT_

----

@isunique not sure how this happened. Let me paste again
Before:
type Chat implements Node {
  id: ID! @isUnique
  dashboardUser: DashboardUser @relation(name: "ChatsFromDashboardUser")
  channelUser: ChannelUser @relation(name: "ChatsFromChannelUser")
  messages: [Message!]! @relation(name: "MessagesInChat")
  createdAt: DateTime!
  updatedAt: DateTime!
}


type Message implements Node {
  id: ID! @isUnique
  dashboardUser: DashboardUser @relation(name: "MessagesFromDashboardUser")
  channelUser: ChannelUser @relation(name: "MessagesFromChannelUser")
  chat: Chat @relation(name: "MessagesInChat")
  text: String!
  createdAt: DateTime!
  updatedAt: DateTime!
}

what I want:
type Chat implements Node {
  id: ID! @isUnique
  dashboardUser: DashboardUser @relation(name: "ChatsFromDashboardUser")
  channelUser: ChannelUser @relation(name: "ChatsFromChannelUser")
  messages: [Message!]! @relation(name: "MessageOnChat")
  createdAt: DateTime!
  updatedAt: DateTime!
}


type Message implements Node {
  id: ID! @isUnique
  dashboardUser: DashboardUser @relation(name: "MessagesFromDashboardUser")
  channelUser: ChannelUser @relation(name: "MessagesFromChannelUser")
  chat: Chat @relation(name: "MessageOnChat")
  text: String!
  createdAt: DateTime!
  updatedAt: DateTime!
}

**Comment by schickling** [comment]
<a href="https://github.com/moksahero"><img src="https://avatars0.githubusercontent.com/u/700960?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [moksahero](https://github.com/moksahero)**
_Wednesday Aug 09, 2017 at 15:56 GMT_

----

ha commenting here with @ make everthing after lower case

**Comment by schickling** [comment]
<a href="https://github.com/moksahero"><img src="https://avatars0.githubusercontent.com/u/700960?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [moksahero](https://github.com/moksahero)**
_Wednesday Aug 09, 2017 at 15:57 GMT_

----

I can't paste code here? that's crazy

**Comment by schickling** [comment]
<a href="https://github.com/moksahero"><img src="https://avatars0.githubusercontent.com/u/700960?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [moksahero](https://github.com/moksahero)**
_Wednesday Aug 09, 2017 at 15:58 GMT_

----

![screenshot from 2017-08-10 00-57-20](https://user-images.githubusercontent.com/700960/29131193-104e8cec-7d67-11e7-8f25-6755336ebeb1.png)

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Wednesday Aug 09, 2017 at 16:02 GMT_

----

What's the change you mentioned in https://github.com/graphcool/api-bugs/issues/226#issuecomment-321297151? I can only see that you reordered the fields, is that correct?

**Comment by schickling** [comment]
<a href="https://github.com/moksahero"><img src="https://avatars0.githubusercontent.com/u/700960?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [moksahero](https://github.com/moksahero)**
_Wednesday Aug 09, 2017 at 16:08 GMT_

----

yes just pushing DateTime fields to the bottom. I can make this type of change too right?

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Wednesday Aug 09, 2017 at 16:09 GMT_

----

No, this change is currently ignored, this explains the observed behaviour. There's already a feature request for this though: https://github.com/graphcool/feature-requests/issues/15

**Comment by schickling** [comment]
<a href="https://github.com/moksahero"><img src="https://avatars0.githubusercontent.com/u/700960?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [moksahero](https://github.com/moksahero)**
_Friday Aug 11, 2017 at 08:15 GMT_

----

so do you need any more info to fix this bug? Let me try to do it again. Thanks

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Friday Aug 11, 2017 at 08:31 GMT_

----

No! To summarize:

* if the only change of a schema is renaming relations, it does not work
* if the only change of a schema is reordering fields, it does not work

**Comment by sorenbs** [comment]
Closing this in favour of https://github.com/graphcool/graphcool/issues/15

**Comment by meteorplus** [comment]
@schickling you can use the graphic designer on the right to alter and rename fields ;)

@sorenbs thanks :p

what's the ETA about filter by Array[String]? thank you
