### ISSUE TITLE
Returning a null error breaks functions

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#427]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Friday Aug 11, 2017 at 14:41 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/229_

----

**What is the current behavior?**

Triggering this function result in an internal server error:

```js
module.exports = function sum(event) {
  const data = event.data

  const sum = data.a + data.b

  return {data: {sum: sum}, error: null}
}
```

**What is the expected behavior?**

When `error: null` is part of the returned value, it should just be ignored.

**Comment by sorenbs** [comment]
@do4gr Did you already fix this?

**Comment by do4gr** [comment]
Yes, this is fixed.
