### ISSUE TITLE
Changing a unique int to unique String results in internal server error

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#429]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Monday Aug 14, 2017 at 11:23 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/231_

----

**What is the current behavior?**

Changing a unique int to unique String results in internal server error.

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**

Start a new project with this schema:

```graphql
type User implements Node {
  createdAt: DateTime!
  id: ID! @isUnique
  updatedAt: DateTime!
  int: Int @isUnique
}
```

Change the `int: Int @isUnique` to `int: String @isUnique`:

```graphql
type User implements Node {
  createdAt: DateTime!
  id: ID! @isUnique
  updatedAt: DateTime!
  int: String @isUnique
}
```

Results in internal server error.

**What is the expected behavior?**

It should just work ™

**Comment by sorenbs** [comment]
@do4gr This sounds like something you already worked on. Can you shed some light?

**Comment by do4gr** [comment]
This is not fixed. I can still reproduce it.

**Comment by marktani** [comment]
Fixed 🎉
