### ISSUE TITLE
More auth providers: Facebook, Github,  ...

### ISSUE THREAD

**Issue by katopz** [graphcool/graphcool#43]
Hi,

Auth0 is nice for free dev but it can reach `$745/mo` in prod too.
So the question is do you have other way to so social login?
For example : https://www.reindex.io/docs/security/authentication/#social-login-authentication-providers

Thanks

**Comment by schickling** [comment]
Hi @katopz, that's a very good point. Yes, we're having plans to add more auth providers in the future. Which ones in particular would be important for you?

**Comment by katopz** [comment]
@schickling Facebook is a must have for real business, and github for my dream project. :)

Thanks

**Comment by mbiqbal** [comment]
@schickling Do we have a timeline for this? Especially facebook?

**Comment by marktani** [comment]
Using Auth0 is the recommended way for now, we'll add further Social Logins in the future.

**Comment by sedubois** [comment]
I'm sad to hear that. I hope Facebook and email auto can come very soon (or at least that there would be a documented way to do it without Auth0). I have the prospect of bringing a prod app with thousands of users and it makes me question whether Graphcool can be more than just a prototyping tool.

**Comment by marktani** [comment]
Facebook Social Login is indeed on our close time horizon. I'll keep this thread posted with further information soon.

**Comment by schickling** [comment]
I totally agree with you @sedubois. We have more and more people asking for this so it's a high priority for us along #39 🙂

**Comment by mbiqbal** [comment]
@marktani Do we have an ETA for this?

**Comment by marktani** [comment]
We've run a closed beta for this feature for a few weeks and it will take us another few weeks until this feature is available to everyone. Thanks for your patience :pray:

**Comment by jvbianchi** [comment]
add Google as a social provider would be nice.

**Comment by mkozhukharenko** [comment]
yes, google would be nice as well

**Comment by jhalborg** [comment]
IMO Facebook and Google auth are both mandatory for serious projects. Good to know they're in the works :)

**Comment by jhalborg** [comment]
@marktani - Just to make sure, will the tokens / integrations to the new auth providers be usable with the permissions?

**Comment by marktani** [comment]
The closed beta is still going on and now also includes Google authentication. Both integrations include token verification as well as an integration with the permission system 🙂

**Comment by sedubois** [comment]
Considering that password authentication should (AFAIK) be avoided for any new project, I think it would make sense to have an easy passwordless system (sending one-time tokens by email/SMS). Can this be considered in the current development?

**Comment by marktani** [comment]
This is already available through the Digits and Auth0 integrations - did you have something specific in mind?

**Comment by sedubois** [comment]
Thanks @marktani. I mean that, as pointed in the OP, it's quite pricy just to get authentication.

**Comment by changalberto** [comment]
Without facebook auth, this is a show stopper for me at the moment. Please get this feature out soon. =)

**Comment by marktani** [comment]
Hey folks thanks for your thoughts!

@sedubois, Digits is free as far as I can tell. Did you think of a specific integration for an passwordless system?

@changalberto, the closed beta for Facebook/Google Auth is going great and we're doing out best to push it out as fast as possible 🙂

**Comment by sedubois** [comment]
@marktani AFAIK digits is only for mobile phone, but I need email auth (that's the data I have).

**Comment by gustavopch** [comment]
@marktani Digits was acquired by Firebase. It was integrated into Firebase Authentication and will be retired in September 30.

**Comment by jhalborg** [comment]
All the more reason to offer a Firebase Auth integration ;)

**Comment by rafaelcorreiapoli** [comment]
What if I don't want to use Auth0Lock for my UI?
Let's say I want to use react-native-fbsdk to get the facebook token, how can I exchange that for a Auth0's idToken to perform the authentication flow ?

**Comment by kbrandwijk** [comment]
@rafaelcorreiapoli You would manually call the Auth0 authentication API with the Access Token obtained from your Facebook SDK login (see https://auth0.com/docs/api/authentication#social). The Auth0 token you get from that call can be used to authenticate with Graphcool.

**Comment by marktani** [comment]
We recently released examples for authentication with [Facebook](https://github.com/graphcool-examples/functions/tree/master/facebook-authentication) and [Google](https://github.com/graphcool-examples/functions/tree/master/google-authentication) using the new beta feature "Schema Extensions" :tada:

We're still looking for help for more examples like Twitter, Github or Firebase. If you're interested to join the beta program, please contact me in Slack (my handle is nilan).

**Comment by marktani** [comment]
This can be discussed further here: https://www.graph.cool/forum/t/feedback-schema-extensions-beta/405.
