### ISSUE TITLE
Cross-Origin problem when displaying file with pdf.js

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#436]
<a href="https://github.com/pbandjs"><img src="https://avatars0.githubusercontent.com/u/20318511?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [pbandjs](https://github.com/pbandjs)**
_Wednesday Aug 23, 2017 at 15:09 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/240_

----

Details: https://www.graph.cool/forum/t/error-when-trying-to-download-file-with-react-pdf/564

**Comment by sorenbs** [comment]
This was resolved in the linked forum thread
