### ISSUE TITLE
Internal Server Error when Adding Type Called User that has extra fields

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#437]
<a href="https://github.com/do4gr"><img src="https://avatars2.githubusercontent.com/u/16278407?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [do4gr](https://github.com/do4gr)**
_Friday Aug 25, 2017 at 14:27 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/241_

----

This is a bug.

**What is the current behavior?**

When creating a fresh project and trying to add a copy of the User type there is a warning.

```
type User implements Node {
  createdAt: DateTime!
  id: ID! @isUnique
  updatedAt: DateTime!
}
```

If instead, you add the exact same type, but add an extra field, an internal server error is returned.

```
type User implements Node {
  createdAt: DateTime!
  id: ID! @isUnique
  updatedAt: DateTime!
  anotherField: String
}
```

The error for duplicate type name should be returned in both cases..

**Comment by marktani** [comment]
Is that still the case in the latest CLI version, @do4gr?

**Comment by do4gr** [comment]
yes. Still results in an internal server error.

**Comment by marktani** [comment]
Will be cleaned up when #454 is tackled I guess.

**Comment by marktani** [comment]
Now that #454 is closed, can you look into this again, @do4gr? I assume this is fixed now.

**Comment by do4gr** [comment]
Still occuring. I will fix it.
