### ISSUE TITLE
Adding the same field twice result in internal server error

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#443]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Wednesday Aug 30, 2017 at 13:35 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/248_

----

**What is the current behavior?**

Adding the same field twice at the same time result in internal server error.

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**

Add the same field twice to an existing type:

```graphql
type Item {
  # ...
  # new:
  test: String
  test: String
}
```

Apply changes. You'll receive an internal server error, and no `test` field has been added.

**What is the expected behavior?**

Either an error message, or the field `test` added once.

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Wednesday Aug 30, 2017 at 13:46 GMT_

----

I'd vote for an error message. Either the schema is 100% correct, and changes will be applied, or it isn't. I would consider it a bad thing if the system starts 'thinking' for itself about how to correct my mistakes :smile:

**Comment by sorenbs** [comment]
@do4gr Did we solve this already?

**Comment by kbrandwijk** [comment]
It now throws an error: {Type}: The type `{Type}` has a duplicate fieldName. So seems solved!
