### ISSUE TITLE
Using illegal character in function name throws internal error

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#446]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Friday Sep 01, 2017 at 18:38 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/251_

----

**What is the current behavior?**
Create a new function with a ~ sign in the name. Saving it throws an internal error.

**What is the expected behavior?**
Validate function name.

**Comment by do4gr** [comment]
This is covered by the recent introduction of function naming rules. Function names are validated against the following regex: ^[a-zA-Z0-9\-_]{1,}$

**Comment by marktani** [comment]
Function names cannot be longer than 64 characters.
