### ISSUE TITLE
GC Push deletes and recreates Functions

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#451]
<a href="https://github.com/do4gr"><img src="https://avatars2.githubusercontent.com/u/16278407?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [do4gr](https://github.com/do4gr)**
_Thursday Sep 07, 2017 at 08:30 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/256_

----

Updating a function using gc push will delete and recreate it. This way you lose invocation history and logs. (thx agartha for reporting)

**Comment by marktani** [comment]
Now, functions are _updated_ instead of deleted & recreated. All functions are furthermore updated for any change in the service definition.

This will be improved going forward.
