### ISSUE TITLE
Make createdAt, updatedAt optional

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#452]
<a href="https://github.com/mavilein"><img src="https://avatars3.githubusercontent.com/u/2470881?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mavilein](https://github.com/mavilein)**
_Thursday Sep 07, 2017 at 11:47 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/257_

----

* the user does not have to specify in the `types.graphql` file
* it is still created in the background in the database
* ideally it would not be visible in the Client API

So maybe we have to add an `isVisible` flag to our Fields data structure.

**Comment by marktani** [comment]
This is now fixed 🙂 

The field is not there from the start, once it's added, the values are there. It can be removed and added, and the values will still be there.

fields need to be `createdAt: DateTime!` and `updatedAt: DateTime!`.
