### ISSUE TITLE
Make System Types optional

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#454]
We currently have two System Types:

- User
- File

Projects can be created through the console (not ejected) or through the CLI (ejected)

When a project is created through the CLI we will not add the User and File type. From hereon the User type has no special meaning as legacy Auth Providers are not available for ejected projects.
Ejected projects can still use the File API, so the File model has special meaning. If a File model is added, it has to have the same structure as the current File type.

When a project is created through the Console, we still create the User and File types.

**Comment by mavilein** [comment]
As a first step we don't want to require System types in `types.graphql` input provided by the user. In the background we will still create it.
