### ISSUE TITLE
Pull wants to overwrite SchemaExtensionFile without actually doing it

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#457]
<a href="https://github.com/do4gr"><img src="https://avatars2.githubusercontent.com/u/16278407?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [do4gr](https://github.com/do4gr)**
_Thursday Sep 07, 2017 at 16:39 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/262_

----

Triggering gc pull repeatedly always warns that it wants to overwrite a schemaextension file. But then it changes nothing.

<img width="824" alt="bildschirmfoto 2017-09-07 um 18 35 21" src="https://user-images.githubusercontent.com/16278407/30174573-d51b2062-93fb-11e7-94fd-28b00ccf5b65.png">

**Comment by mavilein** [comment]
We remove the pull command.
