### ISSUE TITLE
504 and 502 Error Message are not rendered correctly

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#458]
<a href="https://github.com/do4gr"><img src="https://avatars2.githubusercontent.com/u/16278407?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [do4gr](https://github.com/do4gr)**
_Thursday Sep 07, 2017 at 16:51 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/263_

----

The messages are turned into a json.

<img width="1419" alt="bildschirmfoto 2017-09-07 um 18 50 05" src="https://user-images.githubusercontent.com/16278407/30175051-7df6244c-93fd-11e7-8096-201913854331.png">

**Comment by sorenbs** [comment]
@do4gr Is this in the CLI?

**Comment by do4gr** [comment]
Yes. In case of a long running deploy there is a timeout message returned from cloudfront. This is then not rendered correctly.

**Comment by schickling** [comment]
This issue was moved to graphcool/graphcool-cli#176
