### ISSUE TITLE
Don't add default public permissions for new fields/models

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#459]
<a href="https://github.com/sorenbs"><img src="https://avatars3.githubusercontent.com/u/281337?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sorenbs](https://github.com/sorenbs)**
_Thursday Sep 07, 2017 at 16:53 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/264_

----

**Comment by mavilein** [comment]
Just do that for ejected projects.
