### ISSUE TITLE
rename schemaExtension to resolver

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#461]
<a href="https://github.com/sorenbs"><img src="https://avatars3.githubusercontent.com/u/281337?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sorenbs](https://github.com/sorenbs)**
_Thursday Sep 07, 2017 at 18:56 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/266_

----

**Comment by marktani** [comment]
This is also relevant for @nikolasburk 🙂
