### ISSUE TITLE
Scalar List Field are updated during Deploy even though they are not changed

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#463]
<a href="https://github.com/do4gr"><img src="https://avatars2.githubusercontent.com/u/16278407?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [do4gr](https://github.com/do4gr)**
_Friday Sep 08, 2017 at 09:04 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/269_

----

This is a bug.

When pulling a project then deploying it to a new env and there  deploying it again Scalar list fields are updated, even though they were not changed.

**Comment by marktani** [comment]
This is fixed.
