### ISSUE TITLE
Deploy is being run even if there are errors in subscription queries

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#464]
<a href="https://github.com/do4gr"><img src="https://avatars2.githubusercontent.com/u/16278407?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [do4gr](https://github.com/do4gr)**
_Friday Sep 08, 2017 at 09:12 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/270_

----

This is a bug.

When validating a local version via gc status subscription query errors are being detected. But when running deploy, the mutation is attempted, but no functions are being created and no error is received.

**Comment by do4gr** [comment]
This is fixed, will close when it's deployed.
