### ISSUE TITLE
GC Status checks subscription queries against current types, instead of future types

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#465]
<a href="https://github.com/do4gr"><img src="https://avatars2.githubusercontent.com/u/16278407?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [do4gr](https://github.com/do4gr)**
_Friday Sep 08, 2017 at 09:24 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/271_

----

When validating a local project with gc status it checks subscription queries against the current project state instead of the future state including the type changes. GC deploy already does the correct thing. They both should do the correct thing.

**Comment by do4gr** [comment]
This is fixed now.
