### ISSUE TITLE
Auth0 integration view is confusing

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#479]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Friday May 19, 2017 at 18:01 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/29_

----

It's not obvious that the fields are editable

**Comment by schickling** [comment]
<a href="https://github.com/nosykretts"><img src="https://avatars2.githubusercontent.com/u/2125103?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nosykretts](https://github.com/nosykretts)**
_Thursday May 25, 2017 at 16:44 GMT_

----

just need little more greyish input field...

**Comment by sorenbs** [comment]
This will be solved by file-based workflow
