### ISSUE TITLE
The custom behaviour for copy-paste in schema view is annoying

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#481]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Tuesday May 23, 2017 at 13:25 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/35_

----

for example I want to quickly add a new string field, so I copy-paste an existing one. This automatically adds `@rename` which is wrong in this case.

**Comment by sorenbs** [comment]
This will be resolved by file-based workflow
