### ISSUE TITLE
Allow multiple deletion on record

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#482]
<a href="https://github.com/iamrommel"><img src="https://avatars1.githubusercontent.com/u/177265?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [iamrommel](https://github.com/iamrommel)**
_Tuesday May 23, 2017 at 16:36 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/37_

----

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Friday Jun 23, 2017 at 09:44 GMT_

----

Hey @iamrommel can you elaborate what you mean with this?

**Comment by sorenbs** [comment]
@iamrommel Please see https://github.com/graphcool/graphcool/issues/42 and https://github.com/graphcool/graphcool/issues/47

Please open this issue again if your use case is different :-)
