### ISSUE TITLE
Create Relation Popup is not intuitive enough

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#483]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Thursday May 25, 2017 at 13:32 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/42_

----

http://g.recordit.co/jZQ3OgDrnj.gif

* create relation button is simply greyed out, it's not :100: clear that you need to select a type in the first step

**Comment by sorenbs** [comment]
Will be resolved by file-based workflow
