### ISSUE TITLE
"store multiple values in this field" option is confusing

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#486]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Wednesday May 31, 2017 at 08:12 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/45_

----

**Comment by schickling** [comment]
<a href="https://github.com/rohmanhm"><img src="https://avatars2.githubusercontent.com/u/7524911?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [rohmanhm](https://github.com/rohmanhm)**
_Friday Jul 21, 2017 at 04:02 GMT_

----

What that's mean?

**Comment by sorenbs** [comment]
Will be resolved by file-based workflow
