### ISSUE TITLE
api hard to find in docs overview

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#487]
<a href="https://github.com/timsuchanek"><img src="https://avatars1.githubusercontent.com/u/1094804?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [timsuchanek](https://github.com/timsuchanek)**
_Saturday Jun 10, 2017 at 10:29 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/46_

----

**Comment by sorenbs** [comment]
@timsuchanek Can you add some more context and assign the correct `component/` label. Alternatively close the issue :-)

**Comment by schickling** [comment]
I assume this is resolved in the new docs design.
