### ISSUE TITLE
Query Variables box in Playground is barely visible and it's not intuitive to open it

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#497]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Thursday Jun 29, 2017 at 10:00 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/57_

----

**Comment by sorenbs** [comment]
duplicate of https://github.com/graphcool/graphcool/issues/480
