### ISSUE TITLE
Apply to whole type is not intuitive

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#505]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Thursday Jul 20, 2017 at 12:27 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/68_

----

> When updating a permission, there is a big button which says "apply to whole type", so I click that, without realising it's already selected and I'm actually *unselecting* it. I do this every time - it doesn't look selected. Make this idempotent please!

**Comment by sorenbs** [comment]
This will be resolved by the file-based workflow
