### ISSUE TITLE
Formatting Error in CLI Error Message

### ISSUE THREAD

**Issue by do4gr** [graphcool/graphcool#520]
When the file for a ServerSideSubscription is missing the CLI shows the correct error, but it is weirdly formattted.

<img width="700" alt="bildschirmfoto 2017-09-08 um 17 20 01" src="https://user-images.githubusercontent.com/16278407/30219790-71f3de58-94bd-11e7-9e68-c94f642484a1.png">

**Comment by schickling** [comment]
This issue was moved to graphcool/graphcool-cli#175
