### ISSUE TITLE
Support Modules

### ISSUE THREAD

**Issue by mavilein** [graphcool/graphcool#523]
Modules allow you to better structure code.

You could include a weather module in your graphcool.yaml file like this:

```
modules:
  weatherModule: "modules/weather/weather.yaml"
```

Modules have the same features as normal Graphcool projects with the one limitation that they can not reference other modules. Functions, permissions, rootTokens and types in a module are merged into your project and are not name-spaced. If there are conflicts you won't be able to deploy your project.

**Comment by marktani** [comment]
We'll collect example modules here: https://github.com/graphcool/modules. Modules shall increase reusability and structure in your code base.
