### ISSUE TITLE
Put Permissions and Functions under the Type they belong to when possible

### ISSUE THREAD

**Issue by do4gr** [graphcool/graphcool#526]
Fields are already ordered under the type they belong to. The same could be done for permissions and functions. At the moment it is not clear on which types the permissions were created/ deleted.

<img width="873" alt="bildschirmfoto 2017-09-11 um 11 11 14" src="https://user-images.githubusercontent.com/16278407/30267234-3932a00a-96e2-11e7-86d6-27e63ca3f624.png">

**Comment by timsuchanek** [comment]
:+1: will make that nicer today
