### ISSUE TITLE
Omitting a required field in a RP hook causes internal server error

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphcool#527]
Schema:
```
type Test implements Node {
  createdAt: DateTime!
  description: String!
  id: ID! @isUnique
  updatedAt: DateTime!
}
```
RP hook on `Test` `CREATE`:
```
module.exports = function (event) {
  delete event.data.description
  return {data: event.data}
}
```

I would like the same error I'm getting when I don't provide a value for a required field (`field required but not provided`)

**Comment by marktani** [comment]
The explanation for this behaviour is that the incoming mutation will be validated against the GraphQL schema *before* entering the `operationBefore` function but not after it is executed

Running this validation grants type guarantees for existing fields in `event.data` inside the function.

Can you name an actual use case for why the doubled GraphQL valiadation would be beneficial? Why would you want to delete fields part of the incoming mutation?

**Comment by kbrandwijk** [comment]
Basically, you can do anything in a RP hook. If for example, you set an Int field to a String value, you get a nice error, saying the returned Json Object does not match the GraphQL type.

I would expect a missing required field to produce the same error, since that also does not match the type definition.

And I can't really come up with a good reason to delete a required field in an RP hook. :see_no_evil:

**Comment by marktani** [comment]
Ah that's right. The values for the individual fields are of course still validated against the according GraphQL type. Then I agree, this should include requried/optional checks :+1:

**Comment by kbrandwijk** [comment]
I actually forgot about the type checking, until I tested my Int to String example just now, otherwise I would have referred to that in the original description.
