### ISSUE TITLE
require @model directive on model types and deprecate implements Node

### ISSUE THREAD

**Issue by sorenbs** [graphcool/graphcool#533]
Currently a model type is specified like this:

```graphql
type MyModel implements Node {}
```

We will change this to:

```graphql
type MyModel @model {}
```

The rationale for this is that we need a way to distinguish between `model types` that are backed by the database and `general types` that are used in other parts of the system, such as resolvers.

Implementing an interface has defined meaning that is not related to weather or not the type is backed by database.

**Comment by ptpaterson** [comment]
More curious than anything...

Would `@model` apply the `implements Node` or other central interface?  

With `Node` and first class interface support we could have a list/collection of type `[Node!]!`,  extend it to enforce additional fields across every model in the project, and also query against.  I guess by that time we have interface support, I could create my own `Node` interface and apply it to all models.

**Comment by marktani** [comment]
This is now deployed. See https://github.com/graphcool/graphcool/issues/817 for more background.
