### ISSUE TITLE
FR: Use kebab-case function filenames instead of using spaces

### ISSUE THREAD

**Issue by timsuchanek** [graphcool/graphcool#538]
Moved over from https://github.com/graphcool/graphcool-cli/issues/188

**Comment by sorenbs** [comment]
We should restrict function names. Spaces should not be allowed.

I suggest we adopt this constraint: `^[a-zA-Z0-9\-_]*$`

As a first step we should enforce this when creating or updating functions.

We should later consider migrating existing functions based on a well defined conversion.

**Comment by marktani** [comment]
The new function name is now using the above regex. 

The new regex will only be checked when updating an existing function or creating a new function.
