### ISSUE TITLE
Bug: graphcool push made a relation field become required

### ISSUE THREAD

**Issue by mattfysh** [graphcool/graphcool#544]
While manually migrating graphcool updates from one environment to another, I noticed a couple of strange bugs

1. `tags: [String!]` became `tags: [String!]!` after the `graphcool push` command (notice the new addition of the requirement exclamation on the end there
2. the local file didn't fully sync - enums should have been moved to the bottom of the file. I committed my changes, and then later tried to fix the issue above, by doing a `graphcool pull` - this introduced unexpected diff with enums being moved to the bottom of the local file. Ideally they are synced with the server and moved to the bottom upon the original `push`

**Comment by mattfysh** [comment]
Workaround for the first issue was to remove the requirement `!` using the graphcool console, and then perform a `graphcool pull` - which resulted in the second issue

**Comment by kbrandwijk** [comment]
1. Still happens with 1.3.13

**Comment by mattfysh** [comment]
this looks like its been fixed, followed the same steps to promote changes to the next environment, and neither 1 or 2 happened :) thanks! 👍

**Comment by marktani** [comment]
Thanks @mattfysh 🙂
