### ISSUE TITLE
'graphcool deploy help' will deploy project

### ISSUE THREAD

**Issue by do4gr** [graphcool/graphcool#546]
When entering 'graphcool deploy help' instead of 'graphcool help deploy' to get help on the command no error is given but the project is deployed. There should be an error thrown for wrong usage of the deploy command. For other extra arguments than help an error is produced.

<img width="622" alt="bildschirmfoto 2017-09-12 um 16 49 18" src="https://user-images.githubusercontent.com/16278407/30332634-12706db8-97db-11e7-8094-77c14a099ebe.png">

Also the error message for other arguments after deploy says deploy is not a command. 

<img width="472" alt="bildschirmfoto 2017-09-12 um 16 54 45" src="https://user-images.githubusercontent.com/16278407/30332666-2fed9154-97db-11e7-9b07-744e30ee135e.png">

**Comment by kbrandwijk** [comment]
This issue was moved to graphcool/graphcool-cli#238
