### ISSUE TITLE
Updating a function and deploying deletes and creates a new function

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool#547]
**What is the current behavior?**

Updating a function locally and deploying it with the CLI deletes and recreates the function.

![image](https://user-images.githubusercontent.com/1780597/30369479-f4c1ce84-9874-11e7-9419-015849412611.png)

**What is the expected behavior?**

The function should be updated and not deleted and recreated.

**Comment by kbrandwijk** [comment]
Duplicate of https://github.com/graphcool/graphcool/issues/451?

**Comment by marktani** [comment]
yes!
