### ISSUE TITLE
[1.3.13] Type already exists in project error when deploying

### ISSUE THREAD

**Issue by timsuchanek** [graphcool/graphcool#549]
_From @kbrandwijk on September 12, 2017 14:37_

I don't know exactly how to reproduce this, but I deployed a module with Type 'X'.
Then, renamed in to 'Y'.
Then, renamed it back to 'X'.

When deploying, I now get the error:
```
Global
    × A model with the name 'X' already exists in your project
```
Might be a back-end issue though...

_Copied from original issue: graphcool/graphcool-cli#237_

**Comment by marktani** [comment]
I could not reproduce this and assume it is fixed.

**Comment by kbrandwijk** [comment]
I accidentally ran into it again, and can reproduce. See https://github.com/graphcool/cli/issues/289.
