### ISSUE TITLE
[1.3.13] Invalid change to one module removes other module

### ISSUE THREAD

**Issue by timsuchanek** [graphcool/graphcool#550]
_From @kbrandwijk on September 12, 2017 14:33_

I broke the schema for one of my modules. On deployment, it removed the Type defined in _another_ module. Without warning or error about the schema error in the module.

_Copied from original issue: graphcool/graphcool-cli#236_

**Comment by marktani** [comment]
Does that still happen, @kbrandwijk? I could not reproduce this.
