### ISSUE TITLE
Timeout for big projects when deploying with the CLI

### ISSUE THREAD

**Issue by timsuchanek** [graphcool/graphcool#551]
_From @Alex-Mann on September 12, 2017 15:44_

After trying to use `graphcool init` and copy from an existing project, I get the following error:
```
Creating project Shardlancer Catcher... ✔
 ▸    GraphQL Error (Code: 504): {"response":{"error":"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01
 ▸    Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\"
 ▸    CONTENT=\"text/html; charset=iso-8859-1\">\n<TITLE>ERROR: The request could not be
 ▸    satisfied</TITLE>\n</HEAD><BODY>\n<H1>ERROR</H1>\n<H2>The request could not be satisfied.</H2>\n<HR noshade
 ▸    size=\"1px\">\nCloudFront attempted to establish a connection with the origin, but either the attempt failed
 ▸    or the origin closed the connection.\n<BR clear=\"all\">\n<HR noshade size=\"1px\">\n<PRE>\nGenerated by
 ▸    cloudfront (CloudFront)\nRequest ID:
 ▸    AcN9y9Nc1mm2Hd8Nysq_-7Rse27m_-5KkYwuamMVRZBHtIo35Q8CDw==\n</PRE>\n<ADDRESS>\n</ADDRESS>\n</BODY></HTML>","status":504}
```

_Copied from original issue: graphcool/graphcool-cli#239_

**Comment by timsuchanek** [comment]
_From @marktani on September 12, 2017 17:57_

Was this a one off error, or does it happen consistently?

**Comment by timsuchanek** [comment]
_From @Alex-Mann on September 12, 2017 19:16_

This occurs every time for the project I want to copy.

**Comment by timsuchanek** [comment]
_From @kbrandwijk on September 12, 2017 19:29_

Related to https://github.com/graphcool/graphcool-cli/issues/176#issuecomment-328161066?

**Comment by timsuchanek** [comment]
_From @marktani on September 12, 2017 21:22_

looks to be the case, yes

**Comment by timsuchanek** [comment]
Currently deploying big projects are timing out. We're working on that

**Comment by kbrandwijk** [comment]
Hint: http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorCustomOrigin.html#request-custom-request-timeout

**Comment by sorenbs** [comment]
The request timeout is increased to 60 seconds. Unfortunately this is the max setting supported by CloudFormation.

A workaround for bigger projects is to create it in smaller batches. If a project contains 200 models you might be able to create them 50 at a time.

Please note that we allow the deploy command to run for up to 2 minutes, so it is possible that it completes even if the request times out. It is not recommended to rely on this.

The real solution to this issue is git integration which will be available in a future release.

**Comment by kbrandwijk** [comment]
> The default timeout is 30 seconds. You can change the value to between 4 and 60 seconds. If you need a timeout value outside that range, [request a change to the limit](https://console.aws.amazon.com/support/home?region=us-east-1#/case/create?issueType=service-limit-increase&limitType=service-code-cloudfront-distributions).

Maybe in the meantime, just increase it to two minutes, as git integration is still only on the horizon. Don't know how git integration will solve this by the way, in the end it's still the same action that needs to be performed...

**Comment by antho1404** [comment]
I just let one comment https://github.com/graphcool/graphcool-cli/issues/241#issuecomment-329446444 related, it looks like the 60s limit it still not enough.

Maybe for some heavy functions like the `push` used in the CLI there is a way to process this in a background task.

For information my project is not that big, far from the 200 models
- 11 types
- 9 SSS functions (all webhooks)
- 34 permissions

@sorenbs good to know for the git integration 👍

**Comment by Alex-Mann** [comment]
I am in a similar boat as @antho1404, I have <15 types and maybe 20-30 functions and I always get a timeout. Will there be a workaround for this before the git integration makes its way out?

**Comment by antho1404** [comment]
@Alex-Mann The workaround I found is to create a fresh project and recreate it from the beginning but using the CLI and push for every function/permissions like that there is only one mutation to apply all the time and not 50 and so far it works really good. It takes a bit of time to recreate everything but not much more than many copy paste and after that no 504 anymore. That's not perfect solution but at least it works

**Comment by sorenbs** [comment]
The workaround suggested by @antho1404 is what we currently recommend. @Alex-Mann - we will improve this situation before git integration becomes available.

**Comment by antho1404** [comment]
for this workaround it could be really good that the CLI dump the files before it create the new project (and have the timeout) like that we can already have all the functions and permission and we can just comment some parts on the yml and deploy.

This would be awesome if it's possible to do :)

**Comment by notrab** [comment]
I seem to get this error more when I have `git` and `node_modules` inside the folder.

Perhaps this will help debug it. I also opened https://github.com/graphcool/graphcool-cli/issues/255 to highlight this issue.

```
git clone https://github.com/notrab/graphcool-cli-bug.git
cd graphcool-cli-bug
graphcool init
```

The above will error.

If you run...

```
rm -rf .git
graphcool init
```

It works. It doesn't time out.

**Comment by marktani** [comment]
This is also part of the current situation described here: #595. Our proposal how to improve this is also documented there.

**Comment by marktani** [comment]
Further discussion will happen in the mentioned issue.
