### ISSUE TITLE
Deleting a root token is not possible

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool#554]
**What is the current behavior?**

Deleting a root token is not possible. It says the token does not exist.

**Please share the relevant part of your project (GraphQL schema, functions, permissions, ...) for easier reproduction**

```graphql
mutation a {
  deletePermanentAuthToken(input: {
    permanentAuthTokenId: "<id>"
    clientMutationId: "abc"
  }) {
    deletedId
  }
}
```

```graphql
{
  "data": {
    "deletePermanentAuthToken": null
  },
  "errors": [
    {
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "deletePermanentAuthToken"
      ],
      "code": 2000,
      "message": "No Permanent Auth Token with id '<id>'",
      "requestId": "eu-west-1:system:cj7j6wwrt09hm01945uzcsh4a"
    }
  ]
}
```

I double checked that I am passing the correct `<id>` of the root token.

**What is the expected behavior?**

The token should be deleted.

Note that this is a separate issue than https://github.com/graphcool/console/issues/1281, the console is not using the correct mutation input fields.

**Comment by kbrandwijk** [comment]
"Works on my machine" :tm:

**Comment by marktani** [comment]
This looks to only happen when initializing a project from the CLI and subsequently creating a PAT from Console. We will not support this and will provide more information about this matter soon.

**Comment by heymartinadams** [comment]
@marktani FYI, I initialized my project from the Console and created the PAT from the Console, too.
