### ISSUE TITLE
Should be possible to return `{data: null}` from resolvers without getting an error

### ISSUE THREAD

**Issue by nikolasburk** [graphcool/graphcool#558]
**What feature are you missing?**

In a `resolver` function, it should be possible to return `{data: null}` without having to also provide an `error`.

**How could this feature look like in detail? Tradeoffs?**

Considering the equivalent for the standard `user` query that returns the logged in user or null. If you want to build that for a custom auth type using a resolver, you would set up the schema extension e.g. like this:

```graphql
type AuthenticatedEmailUserPayload {
  id: String!
  email: String!
}

extend type Query {
  authenticatedEmailUser: AuthenticatedEmailUserPayload
}
```

`authenticatedEmailUser` is optional, so it should be allowed to just return null:

```js
module.exports = function authenticatedEmailUser(event) {

  if (!event.context.auth || !event.context.auth.nodeId) {
    return { data: null }
  }

  ...
}
```

However, with this implementation the server also returns an error for non-logged-in users:

```js
{
  "data": {
    "authenticatedEmailUser": null
  },
  "errors": [
    {
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "authenticatedEmailUser"
      ],
      "code": 5006,
      "message": "The return value should include a 'data' field of type object",
      "requestId": "eu-west-1:simple:cj7k7742xq5ha0118jq8vigrf"
    }
  ]
}
```

**Comment by do4gr** [comment]
As part of the rework of the resolver function return types it is now possible to return '{data: null}' for resolver payload types that are optional  ( 'PayloadType' and '[PayloadType!]'). Returning just an empty response '{}' will also soon be possible.
