### ISSUE TITLE
Returning `null` for a string in a resolver converts it to the empty string in the response

### ISSUE THREAD

**Issue by nikolasburk** [graphcool/graphcool#559]
For **bug reports**, please fill in the next sections:

**What is the current behavior?**

Consider a `resolver` function that's set up as follows:

```graphql
type AuthenticatedEmailUserPayload {
  id: ID
}

extend type Query {
  authenticatedEmailUser: AuthenticatedEmailUserPayload!
}
```

And implemented like this:

```js
module.exports = function authenticatedEmailUser(event) {
    return {data: {id: null}}
}
```

The client receives an empty string for the value of `id`:

```js
{
  "data": {
    "authenticatedEmailUser": {
      "id": ""
    }
  }
}
```

**Please share the relevant part of your project (GraphQL schema, functions, permissions, ...) for easier reproduction**

See above

**If applicable, share the query, mutation or subscription for reproduction**

```graphql
{
  authenticatedEmailUser {
    id
  }
}
```

**What is the expected behavior?**

The client should receive this response:

```js
{
  "data": {
    "authenticatedEmailUser": {
      "id":  null
    }
  }
}
```

**Comment by marktani** [comment]
This is fixed now. 🙂
