### ISSUE TITLE
Performing a schemaMigration with a lot of changes can lead to an inconsistent project state

### ISSUE THREAD

**Issue by do4gr** [graphcool/graphcool#563]
This is a bug.

I tried to perform a big schema change in the console, deleting a couple of types with many fields at the same time. All without data. The preview did not show any changes and correctly displayed the expected changes. Applying the changes did not respond within 5-10 seconds. Upon clicking apply changes again, two internal server errors fired. Afterwards the project was in an inconsistent state.

**Comment by marktani** [comment]
We significantly improved the performance for schema migrations. It still can happen that the request times out after some while, but the process will most of the time finish in the background.

We have to think about a better approach to this in general, but I'll close this for now 🙂
