### ISSUE TITLE
Renaming a Type will delete the old one and recreate a new one - but without relations

### ISSUE THREAD

**Issue by do4gr** [graphcool/graphcool#564]
Renaming this type:

```
type EmailUser2 implements Node {
  createdAt: DateTime!
  downvotedComment: [Comment!]! @relation(name: "UsersDownvotedComment")
  downvotedPosts: [Post!]! @relation(name: "UserDownvotedPost")
  email: String @isUnique
  groups: [Group!]! @relation(name: "UserOnGroup")
  id: ID! @isUnique
  name: String @isUnique
  password: String
  posts: [Post!]! @relation(name: "UserOnPost")
  profilePic: File @relation(name: "UserOnFile")
  updatedAt: DateTime!
  upvotedComment: [Comment!]! @relation(name: "UsersUpvotedComment")
  upvotedPosts: [Post!]! @relation(name: "UserUpvotedPost")
  adminGroups: [Group!]! @relation(name: "GroupOnUser")
  comments: [Comment!]! @relation(name: "CommentOnUser")
  contributer: Contributor @relation(name: "ContributerOnUser")
  isAdmin: Boolean @defaultValue(value: false)
  karma: Int
}
```

led to the following deploy changes: 

<img width="647" alt="bildschirmfoto 2017-09-15 um 15 51 06" src="https://user-images.githubusercontent.com/16278407/30485536-fa260ff6-9a2d-11e7-9391-23ab11dfdba8.png">

The old type is deleted and a new once created as is expected. But only non-relation fields are being created for the new one. Only a second deploy afterwards will then create the relations and their corresponding permissions.

<img width="428" alt="bildschirmfoto 2017-09-15 um 15 55 59" src="https://user-images.githubusercontent.com/16278407/30485666-6fe1da36-9a2e-11e7-9450-84d96610402e.png">

**Comment by marktani** [comment]
This is now fixed 🙂
