### ISSUE TITLE
The settings page is broken after deleting the project

### ISSUE THREAD

**Issue by marceloogeda** [graphcool/graphcool#565]
**What is the current behavior?**

I'll describe it using the concept of BDD

Given I'm on the Settings page
When I delete my project
And it's not the last project I have
Then my project was deleted
And the page breaks
And I can't click on any links

Take a look:
<img width="1440" alt="screen shot 2017-09-16 at 16 08 34" src="https://user-images.githubusercontent.com/3205036/30515465-87580b4c-9afe-11e7-812d-c55cbc0e2628.png">

**What is the expected behavior?**
Redirect to the previous or last project.

**Comment by marceloogeda** [comment]
@marktani this doesn't happen anymore, you can close this problem 🙂

**Comment by marktani** [comment]
Cheers 🙏
