### ISSUE TITLE
When cloning a project through the CLI the alias value is not set

### ISSUE THREAD

**Issue by marceloogeda** [graphcool/graphcool#566]
**What is the current behavior?**

I ran the following command:  

<img width="1139" alt="screen shot 2017-09-16 at 18 17 39" src="https://user-images.githubusercontent.com/3205036/30516152-e08d8684-9b0c-11e7-9be0-59fb5d907523.png">

That command works I really have a cloned project, but when I took a look into my project settings I miss the project alias who was set on the command line.

<img width="1440" alt="screen shot 2017-09-16 at 18 19 06" src="https://user-images.githubusercontent.com/3205036/30516220-a8e3d542-9b0e-11e7-9c51-b44256610038.png">

**What is the expected behavior?**

I expect to have the project alias set.

**Comment by marktani** [comment]
Will be fixed in the CLI of the Framework Preview. See here for more information: https://www.graph.cool/forum/t/feedback-framework-preview/949?u=nilan.

**Comment by timsuchanek** [comment]
The preview is now released. You can read more about it [here](blog.graph.cool/graphcool-framework-preview-ff42081b1333)
