### ISSUE TITLE
Subscription's filters don't have any effect

### ISSUE THREAD

**Issue by damien-monni** [graphcool/graphcool#567]
**What is the current behavior?**

When subscribing using a filter, the filter is not working and we are receiving everything that is created.

**Please share the relevant part of your project (GraphQL schema, functions, permissions, ...) for easier reproduction**

I am using the freecom example from graphcool, part 5.
You can reproduce the error using the following process:

- Open the following link in 2 different browsers on 2 different networks, for exemple on your computer wich is on a Wifi network and on your mobile which is using 3G data: [https://freecom.netlify.com/](https://freecom.netlify.com/)

- Send a message from both browsers, you will see your message from one browser apearing in the other one. For me, the issue seems to apear when I send a message from the 2nd browser I opened (my mobile on 3G network, then the message is also apearing on my computer).

**If applicable, share the query, mutation or subscription for reproduction**

The query is the one used in the [freecom application](https://www.graph.cool/freecom/) part 5:

```graphql
const newMessageSubscription = gql`
  subscription newMessageSubscription($conversationId: ID!) {
    Message(
      filter: {
        AND: [
          { mutation_in: [CREATED] }
          { node: { conversation: { id: $conversationId } } }
        ]
      }
    ) {
      node {
        id
        text
        createdAt
        agent {
          id
          slackUserName
          imageUrl
        }
      }
    }
  }
`;
```

**What is the expected behavior?**
I should not see the message send from my mobile in any other app (like the one opened in my computer)

**Comment by marktani** [comment]
Thanks, I can reproduce the problem. We'll look into this as soon as possible 🙂

**Comment by parronator** [comment]
Same here but sometimes returns everything and sometimes anything. It is a very unpredictable behaviour

**Comment by marktani** [comment]
Thanks, we're currently investigating a problem with subscriptions when variables are present - will keep this thread posted with updates 🙂

**Comment by marktani** [comment]
This is now fixed - thanks a lot for brining this up! 🙂
