### ISSUE TITLE
Endpoints interpolation messed up

### ISSUE THREAD

**Issue by iamclaytonray** [graphcool/graphcool#569]
This is just a simple interpolation issue. It's not that big of a deal but figured I'd report it anyway. Just need a couple of spaces :)

<img width="544" alt="screen shot 2017-09-17 at 6 29 47 pm" src="https://user-images.githubusercontent.com/16495816/30525539-61c4bc4e-9bd6-11e7-9125-587fedd2c05d.png">

**Comment by iamclaytonray** [comment]
^ That is a screenshot under Endpoints => API Endpoints in the GraphCool app

**Comment by kbrandwijk** [comment]
Duplicate of https://github.com/graphcool/graphcool/issues/522
