### ISSUE TITLE
Permission error messages should include the name of the model that is invalid

### ISSUE THREAD

**Issue by joarwilk** [graphcool/graphcool#592]
**What is the current behavior?**
Lets say I have a type name "Item" and I add a permission rule in my graphcool.yml file like this: `- operation: Item.*`.

Trying to deploy will print an error like this: `✖ unhandled error: Wrong operation defined for ModelPermission. You supplied: '*'` since that rule is for relationships, not types.

The error message doesnt really help with debugging since it doesnt say which part of the configuration is failing. If you have a large schema trying to find the invalid rule will mean having to remove rules one by one until the error disappears.

**What is the expected behavior?**
If the error message would reference the name of the model that is failing, debugging would be a lot easier. Something like this:

`✖ unhandled error: Wrong operation defined for ModelPermission. You supplied: 'Item.*'`

**Comment by sorenbs** [comment]
Great point @joarwilk 

Just to add that in the future we will support the wildcard permission for models. We just haven't gotten around to it yet :-)

**Comment by aurnik** [comment]
I'm getting the "Wrong operation defined for ModelPermission" even though the * is only on relations. Any idea what could be going wrong? I know some others on the forums were having this same problem.

**Comment by marktani** [comment]
can you share a service definition that leads to that error?

**Comment by do4gr** [comment]
We changed the error messages to now return the full operation definition. As proposed we now return `Item.*` instead of just `*`. For relations we included the check as well.

**Comment by joarwilk** [comment]
Yay, thanks @do4gr
