### ISSUE TITLE
Add "Interfaces" to Github Projects

### ISSUE THREAD

**Issue by iamclaytonray** [graphcool/graphcool#594]
Hey, this is a pretty simple one. Can you add "Interfaces" to Projects so we can see progress on it? I did a quick search but it wasn't there. I also think it'd probably be a good idea to add Integrations into Projects, so we can watch progress on those as well. Thoughts?

**Comment by iamclaytonray** [comment]
Or add a ROADMAP.md

**Comment by sorenbs** [comment]
I like the idea of tracking progress on modules 👍 Maybe @marktani can elaborate on how we are currently doing this.

We will add a long-term roadmap in the near future. We are currently in the process of adopting a two-weekly release cadence. We are likely to add a roadmap when we have made the first couple releases under this new approach.

**Comment by iamclaytonray** [comment]
Cool, sounds good!

**Comment by marktani** [comment]
Hey Clayton, thanks a lot for your feedback, it's well appreciated 🙂 

We'll document the status of the current milestone in the Project, but we do have to improve communication about the *mid/long-term* roadmap.

One consideration I have with your suggestion is that before long, we'll have 250 issues in Projects 🙂  That's about how many feature requests there are right now: https://github.com/graphcool/graphcool/labels/kind%2Ffeature

About integrations specifically, I'd love to hear your thoughts about the ones that can be seen in https://github.com/graphcool/modules/ and https://github.com/graphcool-examples/functions/ - are you missing a specific function example or module template?

@sorenbs also opened up the discussion around interfaces recently, please chime in there with your thoughts: https://github.com/graphcool/graphcool/issues/83.

I'm closing this issue for now, feel free to join the discussion in here or the Forum: https://graph.cool/forum/.

**Comment by iamclaytonray** [comment]
No, I don't think anything's missing. I think it would possibly cut down on Issues and FRs if people are aware on features that they would like to see but can also see that it is on the roadmap. For me, when I see something I am interested in, I just wait and don't bother asking about that feature. I'd say communication to the community is really good. This could just be something to enhance that and hopefully, cut down on Issues. (Interfaces is just one example, because it's the most obvious in the console as "coming soon". I think this could apply to whatever is currently being worked on and whatever you guys are planning on working on in the future.) Projects may not be the best place. I think a roadmap would probably be better
