### ISSUE TITLE
Upgrade the default graphcool API endpoint playgrounds to graphql-playground

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphcool#596]
Because it's awesome :smiley:

**Comment by marktani** [comment]
Done 🙂

**Comment by kbrandwijk** [comment]
There's only a slight stylesheet issue between graphqlbin.com and the API endpoints on tabs, buttons and query text. Is that deliberate?
![image](https://user-images.githubusercontent.com/852069/31032289-ba41cf72-a55b-11e7-9707-23bb5cd7423f.png)

**Comment by timsuchanek** [comment]
Ok it seems the font is not loaded properly, will have to look into that
