### ISSUE TITLE
Authenticating from a remote client

### ISSUE THREAD

**Issue by hammadfauz** [graphcool/graphcool#601]
For **feature requests**, please fill in the next sections:

**What feature are you missing?**
My workflow involves developing on a remote server by connecting to it via ssh. When I do `graphcool init` , it gives me a message about opening the browser for auth. Since the server is headless with no browser installed, this message stays indefinitely, and I cannot proceed.

I worked around this by following changes to `/dist/src/api/GraphcoolAuthServer.js`
```
 32    -       while (true) {
 32    +       console.log(`${constants_1.authUIEndpoint}?cliToken=${cliToken}&authTrigger=${this.authTrigger}`);
 33    +       while (true) {
```

**How could this feature look like in detail? Tradeoffs?**
Would like to have a timeout where if it has not authenticated in a while (60 sec?), console prints a link to the screen, to manually open the browser and authenticate.

I would submit a pull request, but there's no code or anything about contributing in the repo, yet.

**Comment by marktani** [comment]
Hey @hammadfauz have you seen the `graphcool auth --token` command? You can get a valid token from within the project settings in the Console.

**Comment by hammadfauz** [comment]
@marktani No, I haven't tried that. But even with the token, as a new user, I wouldn't know the auth url.

**Comment by marktani** [comment]
Hey @hammadfauz, let's continue the discussion in https://github.com/graphcool/cli/issues/281 :)
