### ISSUE TITLE
Insufficient permissions with only relations inputs

### ISSUE THREAD

**Issue by antho1404** [graphcool/graphcool#607]
**What is the current behavior?**

When I create a new data with only relations in parameters the permissions system always return `Insufficient permissions`. When the mutation also include a field from the model everything works well.

Video of the bug from the console -> http://jmp.sh/c5LQq6o

**Please share the relevant part of your project (GraphQL schema, functions, permissions, ...) for easier reproduction**

Permission: 
```
- operation: Trigger.create
  authenticated: true
  query: permissions/types/Trigger/create.graphql
```
and the query bellow (but whatever the permission it's always failing)
```
{
  SomeUserExists(filter: {
    id: $user_id,
    projects_some: {
      id: $input_projectId
    }
  })
}
```

Trigger model:
```
type Trigger implements Node {
  createdAt: DateTime!
  id: ID! @isUnique
  enable: Boolean @defaultValue(value: true)
  updatedAt: DateTime!
  connector: Connector! @relation(name: "ConnectorOnTriggers")
  project: Project! @relation(name: "TriggerOnProject")
  action: Action! @relation(name: "ActionOnTriggers")
}
```

**If applicable, share the query, mutation or subscription for reproduction**

RequestId: `ap-northeast-1:simple:cj83yxcpf44uy0185i1wk01ee`

```
mutation {
  createTrigger(
    actionId: "cj82ygl640ls801542u33xg38",
    connectorId: "cj82ygl740lvi0162pdxek26m",
    projectId: "cj7rqftfv0czc0168urlcfuz3"
  ) {
    id
  }
}
```

**What is the expected behavior?**

It should be possible to have a valid result from the permission system even when we just edit relations.

**Workaround**

We just have to edit another field from the model which is not a relation and the permission is working

**Comment by antho1404** [comment]
This doesn't work with the `updateXX` mutation, the same hack is required

**Comment by marktani** [comment]
Thanks a lot for bringing this up!

This behaviour is documented here https://www.graph.cool/docs/reference/auth/important-notes-aej3ne1eez/ and here https://github.com/graphcool/graphcool/issues/445.

We will improve this behaviour in the course of our efforts to introduce transactional guarantees to nested mutations. Please have a look here: https://github.com/graphcool/graphcool/issues/597.
