### ISSUE TITLE
Also download full schema file

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#612]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Sunday May 28, 2017 at 12:29 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/86_

----

This is needed for autocompletion in IDEs and also for Relay Modern.

See also: https://www.graph.cool/docs/faq/graphql-how-to-download-graphql-idl-schema-maiv5eekan/

**Comment by timsuchanek** [comment]
This functionality is solved by the `graphql-cli` so we shouldn't replicate it in the `graphcool` cli and have a clear separation. We should communicate this more clearly in docs & examples.

**Comment by schickling** [comment]
See https://github.com/graphcool/graphcool/issues/707
