### ISSUE TITLE
CLI Support for project aliases with a hyphen

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#616]
<a href="https://github.com/pbassut"><img src="https://avatars1.githubusercontent.com/u/1500037?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [pbassut](https://github.com/pbassut)**
_Monday Jul 17, 2017 at 22:10 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/128_

----

Looks like the cli doesn't recognize projects with a hyphen in it.
When you do `graphcool-cli pull PROJECT_ALIAS` it'll write PROJECT_ALIAS to the project file but it'll strip out everything after the hyphen(e.g. "my-project" becomes "my").

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Tuesday Jul 18, 2017 at 08:26 GMT_

----

Thanks for reporting this problem @pbassut! I think when using `graphcool pull ALIAS` the project file should still contain the endpoint in the first line.

**Comment by schickling** [comment]
<a href="https://github.com/ruurtjan"><img src="https://avatars2.githubusercontent.com/u/1055478?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ruurtjan](https://github.com/ruurtjan)**
_Saturday Aug 05, 2017 at 17:18 GMT_

----

The regex [here](https://github.com/graphcool/graphcool-cli/blob/8c66be0cdf5b4214696ade69e68dac70b0af863f/src/utils/validation.ts#L2) is different from the one on the website. Creating a name with spaces or hyphens is allowed there.

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Saturday Aug 05, 2017 at 17:25 GMT_

----

Thanks for chiming in @ruurtjan! It's a separate issue but still relevant.

**Comment by timsuchanek** [comment]
Fixed in the latest preview
