### ISSUE TITLE
Stop printing stacktraces to my console

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#619]
<a href="https://github.com/prestongarno"><img src="https://avatars0.githubusercontent.com/u/15187511?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [prestongarno](https://github.com/prestongarno)**
_Friday Aug 25, 2017 at 07:23 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/143_

----

It's completely useless because it doesn't tell me what went wrong

**Comment by schickling** [comment]
<a href="https://github.com/timsuchanek"><img src="https://avatars1.githubusercontent.com/u/1094804?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [timsuchanek](https://github.com/timsuchanek)**
_Friday Aug 25, 2017 at 07:33 GMT_

----

That's a very good point. But do you even see stack traces without setting the `DEBUG` environment variable?

**Comment by schickling** [comment]
<a href="https://github.com/prestongarno"><img src="https://avatars0.githubusercontent.com/u/15187511?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [prestongarno](https://github.com/prestongarno)**
_Friday Aug 25, 2017 at 07:42 GMT_

----

Yeah, although I just realized that I was using the argument `--header` from get-graphql-schema.  I'm really just trying to do schema introspection of open graphql API endpoints for testing my client library. How do I set headers with auth tokens from the CLI?

**Comment by timsuchanek** [comment]
Closing this as this belongs to [`graphql-cli`](https://github.com/graphcool/graphql-cli)
