### ISSUE TITLE
Allow .graphcool file in current folder

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#622]
<a href="https://github.com/timsuchanek"><img src="https://avatars1.githubusercontent.com/u/1094804?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [timsuchanek](https://github.com/timsuchanek)**
_Tuesday Sep 05, 2017 at 18:37 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/153_

----

Makes multi env development easier.

**Comment by timsuchanek** [comment]
This is especially needed for CI environments, where you don't have a "home" folder.
The CLI searches up from the current working directory and looks for the "next" `.graphcool` file.
This allows having a streamlined process.

When we understand the processes better, we later can put this information alternatively into environment variables, but they are rather limited.

**Comment by kbrandwijk** [comment]
@timsuchanek This is great, and will definitely open up possibilities for CI :tada:
