### ISSUE TITLE
Support `GRAPHCOOL_PROJECT` environment variable as alternative to .graphcoolrc

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#626]
<a href="https://github.com/schickling"><img src="https://avatars2.githubusercontent.com/u/1567498?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [schickling](https://github.com/schickling)**
_Thursday Sep 07, 2017 at 19:54 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/171_

----

In cases where you don't want to commit the `.graphcoolrc` file to your repository and you need to be able to deploy a project (for example from a CI environment) it would be very helpful to be able to set the `GRAPHCOOL_PROJECT` environment variable instead to provide the necessary project context (can be either the ID or alias).

**Comment by timsuchanek** [comment]
This is now called `GRAPHCOOL_TARGET` and can be provided like this:
```sh
export GRAPHCOOL_TARGET=shared-eu-west-1/cj8vn13me00er0147a280yhwn
graphcool deploy #runs without having a .graphcoolrc
```
