### ISSUE TITLE
file protocol instead of https

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#628]
<a href="https://github.com/samandarr"><img src="https://avatars2.githubusercontent.com/u/2642041?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [samandarr](https://github.com/samandarr)**
_Friday Sep 08, 2017 at 10:51 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/174_

----

After executing following command, browser pop-up and tried to open file:///console.graph.cool/cli/auth%3FcliToken={SOME_TK}&authTrigger=init

`$ graphcool init --schema https://graphqlbin.com/hn-starter.graphql --name Hackernews` 
⠦ You need to authenticate. Your browser will open shortly...✖  Error: Whoops, something went wrong during authentication.

 * You can enable additional output by setting `export DEBUG=graphcool` and rerunning the command.
 * Open an issue on GitHub: https://github.com/graphcool/graphcool-cli.
 * Get in touch if you need help: http://slack.graph.cool/

⠴ You need to authenticate. Your browser will open shortly...raven@2.1.2 alert: failed to send exception to sentry: Socket timed out on request to sentry.io

**Comment by schickling** [comment]
<a href="https://github.com/timsuchanek"><img src="https://avatars1.githubusercontent.com/u/1094804?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [timsuchanek](https://github.com/timsuchanek)**
_Tuesday Sep 12, 2017 at 09:04 GMT_

----

Thanks for reporting @samandarr.
To be able to do anything about it, we need more information.
Is it possible for you to turn on `export DEBUG=*` and try this with the latest graphcool cli version
`1.3.13`? Thanks!

**Comment by schickling** [comment]
<a href="https://github.com/samandarr"><img src="https://avatars2.githubusercontent.com/u/2642041?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [samandarr](https://github.com/samandarr)**
_Tuesday Sep 12, 2017 at 17:47 GMT_

----

@timsuchanek Currently using cli version of 1.3.7. Works fine.  Thanks!.

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Tuesday Sep 12, 2017 at 17:48 GMT_

----

Please note that this is a beta version that should not be used in production yet. The officially supported version right now is 1.2.1.

**Comment by schickling** [comment]
<a href="https://github.com/samandarr"><img src="https://avatars2.githubusercontent.com/u/2642041?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [samandarr](https://github.com/samandarr)**
_Tuesday Sep 12, 2017 at 18:03 GMT_

----

@marktani okay, I take it into account

**Comment by schickling** [comment]
<a href="https://github.com/samandarr"><img src="https://avatars2.githubusercontent.com/u/2642041?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [samandarr](https://github.com/samandarr)**
_Wednesday Sep 13, 2017 at 09:50 GMT_

----

Having the same issue again once I run 
`export DEBUG=*` (enabled debugging)
`graphcool console` 

  graphcool Send request to https://api.graph.cool/system
  graphcool Payload:
  graphcool {"query":"query ($projectId: ID!){\n  viewer {\n    project(id: $projectId) {\n      id\n      name\n      alias\n      schema\n      version\n      region\n    }\n  }\n}","variables":{"projectId":"cj7iuaw6601ah0175bd0mlu5x"}} +0ms
The Console for project Dunemyth Foe was opened in your browser.

**Comment by timsuchanek** [comment]
The --schema option doesn't exist anymore in the new CLI version, therefore this won't be fixed.
