### ISSUE TITLE
[1.3.10] Project created, even though error occured

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#632]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Monday Sep 11, 2017 at 01:07 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/189_

----

If you `gc init` a new environment, and there's (for example) something wrong with the schema, the console shows an error ('Whoops, something went wrong while creating the project.' with the reason why), but a blank project is still created.

**Comment by timsuchanek** [comment]
Fixed in the latest beta
