### ISSUE TITLE
Init command is slow to render first interactive selection

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#633]
<a href="https://github.com/schickling"><img src="https://avatars2.githubusercontent.com/u/1567498?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [schickling](https://github.com/schickling)**
_Monday Sep 11, 2017 at 14:16 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/192_

----

When running `graphcool init` it takes several seconds until the interactive selection appears. Is there some code that could be executed asynchronously to speed this up?

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Monday Sep 11, 2017 at 16:26 GMT_

----

The slowest part seems to be `const anyjson = require("any-json")`; in yaml.js. No idea why...

**Comment by schickling** [comment]
<a href="https://github.com/schickling"><img src="https://avatars2.githubusercontent.com/u/1567498?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [schickling](https://github.com/schickling)**
_Monday Sep 11, 2017 at 17:58 GMT_

----

We should probably replace it by another package then. @timsuchanek any ideas?

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Monday Sep 11, 2017 at 18:36 GMT_

----

Please have a good look at http://opentracing.io/. It gives you wonderful insights.

**Comment by schickling** [comment]
<a href="https://github.com/timsuchanek"><img src="https://avatars1.githubusercontent.com/u/1094804?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [timsuchanek](https://github.com/timsuchanek)**
_Tuesday Sep 12, 2017 at 08:24 GMT_

----

Open tracing looks good! I first need to deeper analyze which parts are taking a lot of time, partly there is also a simple plugin cache that I currently disabled, which will make it already ~1s faster.
Then we definitely should look for alternatives

**Comment by marktani** [comment]
It's faster by ~500ms, so I'm closing this.
