### ISSUE TITLE
[1.3.13] It's hard to get the correct module url for git branches

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#636]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Monday Sep 11, 2017 at 20:19 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/200_

----

I tried to add a module from: https://github.com/kbrandwijk/modules/tree/get-gravatar/misc/get-gravatar
Then, I found out I can't use a branch, so I merged.

Then, adding it again from: https://github.com/kbrandwijk/modules/tree/master/misc/get-gravatar
Which is still wrong.

Following the syntax from the examples, and comparing it to that repo, I finally came up with:

`gc module:add kbrandwijk/modules/misc/get-gravatar`, which worked...

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Monday Sep 11, 2017 at 20:23 GMT_

----

Update, after reading the docs for https://github.com/ianstormtaylor/download-github-repo, I actually found out that I can still get it from a branch (note the `#branch-name` in there):

`gc module:add kbrandwijk/modules#get-gravatar/misc/get-gravatar`

**Comment by schickling** [comment]
<a href="https://github.com/timsuchanek"><img src="https://avatars1.githubusercontent.com/u/1094804?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [timsuchanek](https://github.com/timsuchanek)**
_Wednesday Sep 27, 2017 at 13:53 GMT_

----

We need better docs around this

**Comment by marktani** [comment]
`graphcool module` has been replaced by `graphcool add-template`: #720.
