### ISSUE TITLE
NPM and file support for modules

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#637]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Monday Sep 11, 2017 at 20:37 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/202_

----

Proposed syntax:

`gc module:add github:user/repo#branch/folder` (like current implementation)
`gc module:add npm:module-name` (for npm modules, it would install and copy from `node_modules`)
`gc module:add file:path` (copy from `path`)

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Monday Sep 11, 2017 at 23:51 GMT_

----

Or take inspiration from `npm install`: https://docs.npmjs.com/cli/install

```
npm install [<@scope>/]<name>
npm install [<@scope>/]<name>@<tag>
npm install [<@scope>/]<name>@<version>
npm install [<@scope>/]<name>@<version range>
npm install <git-host>:<git-user>/<repo-name>
npm install <git repo url>
npm install <tarball file>
npm install <tarball url>
npm install <folder>
```

**Comment by schickling** [comment]
<a href="https://github.com/timsuchanek"><img src="https://avatars1.githubusercontent.com/u/1094804?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [timsuchanek](https://github.com/timsuchanek)**
_Tuesday Sep 12, 2017 at 09:24 GMT_

----

This is a nice proposal! We will discuss it internally how we want to move forward with that

**Comment by marktani** [comment]
`graphcool module` has been replaced by `graphcool add-template`: #720.
