### ISSUE TITLE
[1.3.13] Inconsistent use of slashes in project file

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#638]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Monday Sep 11, 2017 at 20:44 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/203_

----

All functions use `/` for the paths, all modules use `\` for the paths

**Comment by timsuchanek** [comment]
Is this happening on windows?

**Comment by kbrandwijk** [comment]
Yes

**Comment by marktani** [comment]
`graphcool module` has been replaced by `graphcool add-template`: #720.
