### ISSUE TITLE
[1.3.13] Can't open console for project that is not in my environments

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#642]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Monday Sep 11, 2017 at 21:21 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/209_

----

If I `gc init` a project, without specifying an environment, I cannot open it using `gc console` because that command now only works with an environment, and not with projectid anymore.

Proposal: add --project,-p flag, and accept both project id and name.

**Comment by marktani** [comment]
This is now solved via targets.
