### ISSUE TITLE
[1.3.13] Function logs only work if remote project contains local function

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#644]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Monday Sep 11, 2017 at 21:44 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/211_

----

If I specify a random function from a random project, it doesn't work. The function has to be part of the local project definition. Which makes me wonder about all kind of edge cases for how this is checked, like:
- Is this checked by function name, and could the function be doing something completely different?

Also, why is there a -p flag, if you can only use (effectively) projects that are part of the environment. -e would suffice in that case.

However, I would just like to get logs for a function in a random project.

**Comment by schickling** [comment]
<a href="https://github.com/timsuchanek"><img src="https://avatars1.githubusercontent.com/u/1094804?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [timsuchanek](https://github.com/timsuchanek)**
_Tuesday Sep 12, 2017 at 09:34 GMT_

----

Thanks for bringing this up, I'm not yet sure how we want to support account-wide function logs, as there could be naming conflicts, but this should definitely have a better experience

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Tuesday Sep 12, 2017 at 10:52 GMT_

----

Don't depend on the local configuration for this command, just connect to whatever projectid/name is passed to the command.

**Comment by marktani** [comment]
Solved by targets.
