### ISSUE TITLE
[1.3.13] FR: Search up the folder structure for project file

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#646]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Monday Sep 11, 2017 at 22:05 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/216_

----

It would be helpful if I could call all 'gc' commands from a subfolder. I keep navigating back between code and root folder every time I need to run a command...

**Comment by timsuchanek** [comment]
Done in latest preview
