### ISSUE TITLE
[1.3.13] Explain flow for working with existing projects

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#649]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Monday Sep 11, 2017 at 22:44 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/223_

----

I have an existing project, for which I want to create a local project.
`gc pull` is officially deprecated, so please explain the flow to create a local project for my existing project.

**Comment by schickling** [comment]
<a href="https://github.com/timsuchanek"><img src="https://avatars1.githubusercontent.com/u/1094804?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [timsuchanek](https://github.com/timsuchanek)**
_Tuesday Sep 12, 2017 at 09:49 GMT_

----

Thanks for bringing this up, we will add an `Eject` button to the Console and provide more information on the ejection path

**Comment by marktani** [comment]
The "Upgrade Project" button is now available to everyone in the project settings.
