### ISSUE TITLE
[1.3.13] Flatten module(s)

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#651]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Tuesday Sep 12, 2017 at 00:05 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/225_

----

Add an option to flatten a single, or all, modules, into the main project file and file structure.

**Comment by marktani** [comment]
`graphcool module` has been replaced by `graphcool add-template`: #720.
