### ISSUE TITLE
Require lower node version than 8.3

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#652]
<a href="https://github.com/timsuchanek"><img src="https://avatars1.githubusercontent.com/u/1094804?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [timsuchanek](https://github.com/timsuchanek)**
_Tuesday Sep 12, 2017 at 08:28 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/226_

----

For broad adoption this is important.
It could also be solved be zeit/pkg

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Tuesday Sep 26, 2017 at 08:07 GMT_

----

Now that 8.4 is out, some are running into the problem that the CLI is only available to 8.3 🙂

**Comment by kbrandwijk** [comment]
How a single optional parameter saved the day :smile:

**Comment by timsuchanek** [comment]
See https://github.com/graphcool/graphcool/issues/777 for more information
