### ISSUE TITLE
[1.3.13] Project list is infinite

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#653]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Tuesday Sep 12, 2017 at 08:59 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/227_

----

After the last project, the first project comes again. Is this intended? If so, a visual cue that this is the list from the start would be helpful. (For example a line that only contains `-` characters).

This is for the selection when doing `graphcool init` based on an existing project.

**Comment by schickling** [comment]
<a href="https://github.com/timsuchanek"><img src="https://avatars1.githubusercontent.com/u/1094804?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [timsuchanek](https://github.com/timsuchanek)**
_Tuesday Sep 12, 2017 at 10:43 GMT_

----

Yes, this is intended. We should indeed find a better UI for that

**Comment by timsuchanek** [comment]
Done in the latest preview
