### ISSUE TITLE
[1.3.20] `graphcool init` output says previously existing files have just been written

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#654]
<a href="https://github.com/nikolasburk"><img src="https://avatars1.githubusercontent.com/u/4058327?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nikolasburk](https://github.com/nikolasburk)**
_Tuesday Sep 12, 2017 at 11:59 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/229_

----

I just created a new project with `graphcool init`. Inside the directory where I ran the command I had the `authenticate-with-auth0-and-apollo` directory including some files. After `graphcool init` finished successufully it said: `Written files:` and printed a file tree that also contains the directory that already existed before.

![image](https://user-images.githubusercontent.com/4058327/30324799-967518a2-97c2-11e7-8441-122d470b31b4.png)

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Tuesday Sep 12, 2017 at 12:08 GMT_

----

Can you do
```sh
npm -g remove graphcool
npm -g install graphcool@1.3.13
``` 
? `1.3.20` was a temporary version, `1.3.13` is now the latest version.

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Tuesday Sep 12, 2017 at 14:40 GMT_

----

As far as I can see, in `1.3.13` it still generates that file list from the current state of the directory, showing whatever files were already there, instead of just showing the files it has actually written.

**Comment by marktani** [comment]
Fixed in latest preview 👌
