### ISSUE TITLE
[1.3.13] Unable to use types from module in main schema

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#656]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Tuesday Sep 12, 2017 at 14:00 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/231_

----

If a module defines a Type, and I subsequently want to create a relation to that Type, I get an error when deploying that there's no Type with that name.

So, the types in my module are not taken into account when the schema is validated.

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Tuesday Sep 12, 2017 at 14:03 GMT_

----

Example use case: one of the modules for authentication defines a XXXUser Type. In order to integrate this, I add a relation to it in my main schema User Type, and vice versa in the module.

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Wednesday Sep 27, 2017 at 18:39 GMT_

----

Is this still the case, @kbrandwijk? 🙂 I can successfully define relations across modules.

**Comment by marktani** [comment]
`graphcool module` has been replaced by `graphcool add-template`: #720.
