### ISSUE TITLE
[1.3.13] Changes in modules not picked up

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#657]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Tuesday Sep 12, 2017 at 14:05 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/232_

----

I added a module, and made some changes to it. When I deploy, it says:
`Identical project definition`

**Comment by schickling** [comment]
<a href="https://github.com/timsuchanek"><img src="https://avatars1.githubusercontent.com/u/1094804?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [timsuchanek](https://github.com/timsuchanek)**
_Wednesday Sep 13, 2017 at 09:18 GMT_

----

What exactly did you change in the module? There are some changes that are not tracked also in the root module

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Wednesday Sep 13, 2017 at 09:19 GMT_

----

I just successfully changed `types.graphql`. I added a relation to a type defined in the base module. Deploy went as expected.

**Comment by schickling** [comment]
<a href="https://github.com/timsuchanek"><img src="https://avatars1.githubusercontent.com/u/1094804?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [timsuchanek](https://github.com/timsuchanek)**
_Wednesday Sep 27, 2017 at 14:10 GMT_

----

@kbrandwijk can you elaborate on this? We couldn't reproduce it until now

**Comment by marktani** [comment]
`graphcool module` has been replaced by `graphcool add-template`: #720.
