### ISSUE TITLE
[1.3.13] Module project file can include functions and permissions for 'other types'

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#658]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Tuesday Sep 12, 2017 at 14:22 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/234_

----

The project file can define hooks and permissions for Types that are not part of the module. This relates to how Types will be defined for modules, but I think a module should be self-contained. Every permission, rp hook or anything should be on a type that's part of the module schema.

Of course, that would require the Type merging from the other issue.

**Comment by schickling** [comment]
<a href="https://github.com/timsuchanek"><img src="https://avatars1.githubusercontent.com/u/1094804?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [timsuchanek](https://github.com/timsuchanek)**
_Wednesday Sep 13, 2017 at 09:20 GMT_

----

In the current implementation, we don't do any checking at all. When  implementing the checks we should consider this

**Comment by marktani** [comment]
`graphcool module` has been replaced by `graphcool add-template`: #720.
