### ISSUE TITLE
git and node_modules copied on init

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#664]
<a href="https://github.com/notrab"><img src="https://avatars3.githubusercontent.com/u/950181?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [notrab](https://github.com/notrab)**
_Thursday Sep 21, 2017 at 14:40 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/255_

----

Running `graphcool init` with a project that is tracked in git and has node_modules, copies these files.

I've yet to reduplicate this issue, as everytime it results in https://github.com/graphcool/graphcool/issues/551 - But this could help resolve that issue. But when I don't get 504 error, I get...

```
Written files:
   ├─ .env
   ├─ .git
   │  ├─ COMMIT_EDITMSG
   │  ├─ FETCH_HEAD
   │  ├─ HEAD
   │  ├─ config
   │  ├─ hooks
   │  │  ├─ ctags
   │  │  ├─ post-checkout
   │  │  ├─ post-commit
   │  │  ├─ post-merge
   │  │  ├─ post-rewrite
   │  │  ├─ pre-commit
   │  │  ├─ pre-push
   │  │  └─ prepare-commit-msg
   │  ├─ index
   │  ├─ info
   │  │  └─ exclude
   │  ├─ logs
   │  │  ├─ HEAD
   │  │  └─ refs
   │  │     ├─ heads
   │  │     │  └─ master
   │  │     └─ remotes
   │  │        └─ origin
   │  │           └─ master
   │  ├─ objects
```

**Surely .git and node_modules don't need to be synced?**

Duplicate error:

```
git clone https://github.com/notrab/graphcool-cli-bug.git
cd graphcool-cli-bug
graphcool init
```

The above will error.

If you run...

```
rm -rf .git
graphcool init
```

It works. It doesn't time out.

**Comment by timsuchanek** [comment]
Fixed in the latest preview
