### ISSUE TITLE
rename module command to modules

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#666]
<a href="https://github.com/lifeiscontent"><img src="https://avatars3.githubusercontent.com/u/180963?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lifeiscontent](https://github.com/lifeiscontent)**
_Friday Sep 22, 2017 at 18:16 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/257_

----

```
$ graphcool modules add graphcool/modules/authentication/facebook
 ▸    modules is not a graphcool command.
 ▸    Perhaps you meant module:add
 ▸    Run graphcool help for a list of available commands.
```

version of graphcool: graphcool/1.3.16-beta.18 (darwin-x64) node-v8.5.0

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Friday Sep 22, 2017 at 18:25 GMT_

----

could you try
`graphcool module add graphcool/modules/authentication/facebook` instead? 🙂 
We do plan to rename `module` to `modules`, did you already read that somewhere?

**Comment by marktani** [comment]
The latest version now uses `modules`.
