### ISSUE TITLE
Adding a module in an empty folder throws error

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#667]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Friday Sep 22, 2017 at 19:14 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/258_

----

```sh
mkdir algolia
graphcool module add graphcool/modules/syncing/algolia
```

```
Downloading module graphcool/modules/syncing/algolia from graphcool/modules ... ✔
 ▸    Cannot read property 'modules' of undefined
```

**Comment by marktani** [comment]
`graphcool module` has been replaced by `graphcool add-template`: #720.
