### ISSUE TITLE
Adding a module throws an error if there is no existing modules key

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#668]
<a href="https://github.com/Merott"><img src="https://avatars3.githubusercontent.com/u/1757708?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Merott](https://github.com/Merott)**
_Sunday Sep 24, 2017 at 08:48 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/259_

----

Remove the `modules` entry from the `graphcool.yml` file, then run:

```
graphcool module add graphcool/modules/syncing/algolia
```

You get:

```
Downloading module graphcool/modules/syncing/algolia from graphcool/modules ... ✔
▸    Cannot read property 'endPosition' of undefined
```

**Comment by marktani** [comment]
`graphcool module` has been replaced by `graphcool add-template`: #720.
