### ISSUE TITLE
Reference GraphQL operations from files

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#669]
<a href="https://github.com/schickling"><img src="https://avatars2.githubusercontent.com/u/1567498?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [schickling](https://github.com/schickling)**
_Sunday Sep 24, 2017 at 14:07 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/260_

----

_TBD_

**Comment by marktani** [comment]
This is now possible in the latest preview, see https://github.com/graphcool/graphcool/issues/602#issuecomment-336709814 for more information 🎉
