### ISSUE TITLE
init doesn't correctly work when running with an existing local definition

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#672]
<a href="https://github.com/timsuchanek"><img src="https://avatars1.githubusercontent.com/u/1094804?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [timsuchanek](https://github.com/timsuchanek)**
_Monday Sep 25, 2017 at 09:04 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/265_

----

It inits an empty project

**Comment by timsuchanek** [comment]
Int and deploy are now split up, so this is not relevant anymore.
