### ISSUE TITLE
Removing a module via the modules command

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#673]
<a href="https://github.com/marceloogeda"><img src="https://avatars1.githubusercontent.com/u/3205036?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marceloogeda](https://github.com/marceloogeda)**
_Tuesday Sep 26, 2017 at 00:54 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/267_

----

Something like this:

```sh
graphcool module remove MODULEURL
```

**Comment by schickling** [comment]
<a href="https://github.com/timsuchanek"><img src="https://avatars1.githubusercontent.com/u/1094804?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [timsuchanek](https://github.com/timsuchanek)**
_Wednesday Sep 27, 2017 at 12:58 GMT_

----

Not yet planned, but good idea!

**Comment by marktani** [comment]
`graphcool module` has been replaced by `graphcool add-template`: #720.
