### ISSUE TITLE
Allow modules to be installed from graphcool.yml file

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#678]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Wednesday Sep 27, 2017 at 00:13 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/273_

----

Use case: if I specify an existing Github module in my graphcool.yml, ideally I shouldn't have to commit that module to my own git repo. Just like node_modules, it would be great if the modules would be installed when for example doing the first `git init`.

Or, I could add a module to my graphcool.yml, run something like `gc modules install`, and the missing modules would be installed.

**Comment by marktani** [comment]
Modules have been replaced by Templates: #720.
