### ISSUE TITLE
FR: Open graphqlbin playground / endpoint playground when using `gc playground`

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#679]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Wednesday Sep 27, 2017 at 00:21 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/274_

----

Now, the console is opened, with the playground tab, when using `gc playground`. It would be better to open the API endpoint playground directly, or integrate with a locally installed graphql-playground-electron if available. See https://github.com/graphcool/graphql-playground/issues/123 for details on that last option.

**Comment by timsuchanek** [comment]
This is implemented in the latest `graphcool` cli beta version and graphql playground. It's not yet using the protocol handler, just argv, but that is sufficient for now

**Comment by kbrandwijk** [comment]
No, the protocol handler is only needed when opening the local app from the web, like from a button in the hosted playground. So this is fine!
