### ISSUE TITLE
Deleting modules not handled gracefully

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#680]
<a href="https://github.com/timsuchanek"><img src="https://avatars1.githubusercontent.com/u/1094804?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [timsuchanek](https://github.com/timsuchanek)**
_Wednesday Sep 27, 2017 at 13:28 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/275_

----

deleting a module in the filesystem but not in `graphcool.yml`and doing `graphcool diff` should be handled gracefully

**Comment by marktani** [comment]
modules have been replaced by templates: #720
