### ISSUE TITLE
Two issues with headers

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#681]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Wednesday Sep 27, 2017 at 13:28 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/276_

----

- headers are required for a webhook, even though the documentation says they are not.
- headers are passed to the webhook, but the body also contains an empty headers object.

**Comment by sorenbs** [comment]
1 - is fixed and deployed
2 - I assume you are referencing the context.request.headers field. This is supposed to contain headers sent by the user, not the headers specified for a function

**Comment by kbrandwijk** [comment]
2 - What do you mean by headers set by the user? If I have a function set up with headers, and I call that function in the new playground, specifying headers, all of those headers are sent as real headers, and the headers object always stays empty.

**Comment by sorenbs** [comment]
That's correct. The feature is currently broken :-)

**Comment by marktani** [comment]
I created a separate feature request for 2): https://github.com/graphcool/graphcool/issues/877 🙂
