### ISSUE TITLE
add cli option for custom module names for modules add

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#682]
<a href="https://github.com/timsuchanek"><img src="https://avatars1.githubusercontent.com/u/1094804?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [timsuchanek](https://github.com/timsuchanek)**
_Wednesday Sep 27, 2017 at 13:29 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/277_

----

**Comment by marktani** [comment]
`graphcool module` has been replaced by `graphcool add-template`: #720.
