### ISSUE TITLE
local function invocation brittle

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#684]
<a href="https://github.com/timsuchanek"><img src="https://avatars1.githubusercontent.com/u/1094804?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [timsuchanek](https://github.com/timsuchanek)**
_Wednesday Sep 27, 2017 at 13:32 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/280_

----

Taken from https://www.graph.cool/forum/t/feedback-new-cli-beta/949/36?u=nilan

Spent a some time trying to debug functions from auth modules before I realized that toString wasn’t called on errors so the logs only showed “{}”. Also invoking functions locally seems to be broken? I can call it with some json but there’s no output.
The navigation in console for functions/logs is bugged, often requiring a reload before I can open the logs again after a gc deploy.

**Comment by timsuchanek** [comment]
Turned this issue into smaller chunks
