### ISSUE TITLE
Decide module vs modules wording

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#686]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Wednesday Sep 27, 2017 at 15:32 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/284_

----

Currently, documentation states that `modules` is correct, while CLI & usage information states that `module` is correct.

**Comment by timsuchanek** [comment]
It's now called 'modules'
