### ISSUE TITLE
Separate `graphcool init` and `graphcool deploy`

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#706]
I suggest to semantically/functionally separate the `graphcool init` and the `graphcool deploy` command. This means that the `init` command just bootstraps a new project without actually deploying it yet.

**Comment by kbrandwijk** [comment]
That's a very good idea. I use `graphcool init` a lot just to boilerplate a local project, but without the need to deploy it, at least right away.

**Comment by timsuchanek** [comment]
Done in latest preview
