### ISSUE TITLE
Write FAQ about difference between `graphcool` and `graphql-cli`

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#707]
There seems to be [a bit of confusion](https://github.com/graphcool/graphql-cli/issues/18) around the usage of the `graphcool` CLI and the [`graphql-cli`](https://github.com/graphcool/graphql-cli) tool.

It would be beneficial if there was a FAQ article discussing the following:

* Differences between both CLIs and when to use which
* Encourage combined usage of both and discuss best practices/workflows

Todo before closing:

- [x] Update issue: https://github.com/graphcool/graphql-cli/issues/18
- [x] Add link to FAQ in readme: https://github.com/graphcool/graphql-cli

**Comment by kbrandwijk** [comment]
Related: https://github.com/graphcool/cli/issues/272

**Comment by nikolasburk** [comment]
Here's the FAQ: https://docs-next.graph.cool/faq/other-reob2ohph7/#whats-the-difference-between-the-graphcool-cli-and-the-graphql-cli

I also created a PR to add a link to it to the graphql-cli's README: https://github.com/graphcool/graphql-cli/pull/32

**Comment by kbrandwijk** [comment]
This does not address the issue of the two project using incompatible environment configuration, like I mentioned [here](https://github.com/graphcool/graphcool/issues/707#issuecomment-333325653).
