### ISSUE TITLE
File API: file deletion does not delete file

### ISSUE THREAD

**Issue by sedubois** [graphcool/graphcool#713]
**What is the current behavior?**

- using Graphcool web console, upload a file to the file API (e.g an image)
- note the file URL and navigate to the file: it is visible
- using Graphcool console, select the file and delete it
- navigate again to the same file URL: it is still visible

**What is the expected behavior?**

The file must disappear immediately. Because the information stored can be of a sensitive nature, I need to have the confidence that if I need to delete a file for whatever reason, that this change is indeed taken into account and propagates instantaneously or at least very rapidly (and that I can have a way to see that it's going to happen).

**Comment by kbrandwijk** [comment]
The is an open issue for faster cache invalidation: https://github.com/graphcool/graphcool/issues/254.
Currently, as described here: https://github.com/graphcool/api-bugs/issues/102, files are cached for a maximum of one hour.
