### ISSUE TITLE
Rethink `graphcool modules` workflows

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#719]
The current `graphcool modules add` workflow feels fairly cumbersome, especially when there are model types involved. These types typically need to be adjusted manually anyway and it would make more sense to keep them in one location in the first place. IMO the same holds true for `permissions` and `rootTokens`.

I suggest to rethink the `graphcool modules` CLI command.

Besides that, the entire `modules` concept of the framework needs further exploration as well (should probably be another issue).

**Comment by marktani** [comment]
Also see #605.

**Comment by marktani** [comment]
Modules have been replaced by templates: #720.
