### ISSUE TITLE
[1.4.0] Second module not added to graphcool.yml and deploy broken

### ISSUE THREAD

**Issue by timsuchanek** [graphcool/graphcool#721]
Originally from @kbrandwijk 

 
`$ gc init`
`$ gc modules add ...../github`
`$ set CLIENT_ID=xxx`
`$ set CLIENT_SECRET=xxx`
`$ gc modules add ...../facebook`

![image](https://user-images.githubusercontent.com/852069/31048194-bca46dac-a618-11e7-8566-ae9fe8b1133c.png)

Manually added the facebook module and fixed the facebook code-paths.

`$ gc deploy`

![image](https://user-images.githubusercontent.com/852069/31048201-f4a47698-a618-11e7-8a90-41f15c54b90e.png)

**Comment by marktani** [comment]
`graphcool module` has been replaced by `graphcool add-template`: #720.
