### ISSUE TITLE
terminal authentication won't open the browser

### ISSUE THREAD

**Issue by Wenzel** [graphcool/graphcool#727]
While following the `howtographql` tutorial, i was asked to use graphcool:

~~~
graphcool init --schema https://graphqlbin.com/hn-starter.graphql --name Hackernews
~~~

**What is the current behavior?**
This command will wait undefinitely for my browser to open a url.
~~~
⠹ You need to authenticate. Your browser will open shortly...
~~~

and nothing happens.

**What is the expected behavior?**
My default browser should open a url to authenticate with graphcool.

How can i debug this ?

Thanks !

**Comment by kbrandwijk** [comment]
As a workaround, you can use `graphcool auth --token .....` with the token you can find in your project settings in the console. Are you using a specific development environment where this happens (online IDE, special OS version, anything)?

**Comment by Wenzel** [comment]
hi @kbrandwijk ,

I don't have any project settings.
I guess `--schema https://graphqlbin.com/hn-starter.graphql --name Hackernews` is supposed to create that file ?

> Are you using a specific development environment where this happens (online IDE, special OS version, anything)?
No, just the console on Linux (Fedora).

Thank you for your help.

**Comment by marktani** [comment]
The URL to be opened is now printed in the latest preview, so you can manually open it.

**Comment by anaibol** [comment]
Hello I have 1.3.7 and i don't see the link. I'm on Linux.

**Comment by sastava007** [comment]
> The URL to be opened is now printed in the latest preview, so you can manually open it.
@marktani @Wenzel 

Can you please share that link?
I'm not able to find it anywhere also seems like graph.cool isn't operational anymore.
