### ISSUE TITLE
no valid session error

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool#731]
**What is the current behavior?**

running `graphcool auth` and `graphcool info` returns "no valid session" error. as you can see in the screenshot, `graphcool init` works just fine.

![image](https://user-images.githubusercontent.com/1780597/31271756-e568680a-aa88-11e7-93e8-ecac3693996f.png)

**What is the expected behavior?**

running `graphcool auth` opens the browser for authentication, `graphcool info` prints information.

**Comment by rwatts3** [comment]
can we get a response on this issue ? 
it was closed with no explanation as to what's the problem and I am still seeing this with the new `graphcool@next` module.

**Comment by schickling** [comment]
Apologies for the confusion @rwatts3. We’re looking into it!

**Comment by timsuchanek** [comment]
The CLI now reauthenticates if an invalid session is found.
This will be released in the 0.7 release this afternoon
