### ISSUE TITLE
Remove gc env command

### ISSUE THREAD

**Issue by timsuchanek** [graphcool/graphcool#732]
The command is currently rather confusing than useful. `deploy` writes automatically into the file, if more adjustments are needed, you just can edit the `.graphcoolrc` file on your own.

**Comment by timsuchanek** [comment]
The command has been removed as announced in the latest preview.

**Comment by kbrandwijk** [comment]
So the consideration for being able to set the default environment wasn't taken into account? Any workaround other than manual editing?

**Comment by timsuchanek** [comment]
The default stage is automatically set when deploying the first time.
When you want to override it while deploying to a new stage, we introduced the `--default` option to force overriding the default stage.

**Comment by kbrandwijk** [comment]
@timsuchanek Exactly what I was looking for. Thanks!
