### ISSUE TITLE
Confirmation answer ignored on `graphcool delete`

### ISSUE THREAD

**Issue by l-catallo** [graphcool/graphcool#735]
When issuing the `graphcool delete` command the project is deleted regardless of the user's input.

![image](https://user-images.githubusercontent.com/2939295/31291188-7cd64c66-aacf-11e7-93e7-c3547d65e40b.png)

I checked and the project was actually deleted. The same thing happens if I don't type anything.

Version info: `graphcool/0.6.0-beta.3 (linux-x64) node-v8.6.0`

Edit: Typing `y` cancel the deletion

**Comment by marktani** [comment]
> The same thing happens if I don't type anything.

**Comment by l-catallo** [comment]
> > The same thing happens if I don't type anything.
>
> what do you mean with this?

If I press enter without typing a response the default behavior should be to cancel the operation (as the message says). Right now the project is deleted anyway.

**Comment by kbrandwijk** [comment]
Maybe the text should be updates to 'Are you sure you want to keep cj....?' or 'Do you not want to delete cj....?' or 'Do you confirm that you don't want to stop keeping access to cj...?' :smiling_imp: :rofl:

**Comment by timsuchanek** [comment]
This is fixed now, the code simply confused y with n.
