### ISSUE TITLE
Type definition for project file is missing from recent beta CLI packages

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphcool#744]
In the earlier versions of the beta CLI, the Json file with the definition of the YAML was part of the package. Now, I can't find it anywhere (not even in the sources, for that matter).

Please reintroduce this Json definition, because it can be used for linting/intellisense by some IDE addons.

**Comment by marktani** [comment]
It is now available in a separate package, see https://github.com/graphcool/graphcool-json-schema 🙂
