### ISSUE TITLE
Resolvers: Unable to import npm package from npm organization

### ISSUE THREAD

**Issue by notrab** [graphcool/graphcool#757]
**What is the current behavior?**

Importing a module from an NPM organization results in a 

```js
'use latest'

const sgMail = require('@sendgrid/mail')
const { fromEvent } = require('graphcool-lib')
```

`graphcool deploy` returns:

```
Could not create serverless function for 'sendConfirmationEmail'. Ensure that the code is valid
```

If you remove the `@sendgrid/` part and replace this with a normal module that doesn't belong to an organization, it imports fine.

There are several packages I wish to use that belong to organizations, this support would be appreciated 💚

**What is the expected behavior?**

Deploy successfully.

**Comment by kbrandwijk** [comment]
There must be something else wrong with this, because I have succesfully used scoped packages, like https://github.com/AgarthaSolutions/graphcool-mutex/blob/master/example/src/increment.js#L3. 
Also see #424.

**Comment by notrab** [comment]
This indeed is related to #424 

@schickling any thoughts on when this support will be added?

**Comment by kbrandwijk** [comment]
I have just created a dummy project to test this:

- `gc init` -> blank
- uncomment function
- add `const sg = require('@sendgrid/mail')`
- `gc deploy` -> succesful

**Comment by sorenbs** [comment]
We will add better support for specifying npm modules in the next couple weeks for projects that use the cli to manage their service (formerly project)

@notrab Please reach out directly if you are interested in beta testing the new workflow :-)

**Comment by notrab** [comment]
@kbrandwijk It appears to be working in a new project but updating an existing project with this seems to fail.

There is definitely something up in the pipeline with this one. Can you try on any existing projects to require that module? 👍

**Comment by kbrandwijk** [comment]
By 'existing', you mean edit a function in the console for a non-ejected project, or?

**Comment by notrab** [comment]
Either. Both don't work for me if I use `@`, if I remove, either way works. So odd. Seems to work for new projects.

**Comment by kbrandwijk** [comment]
Try removing and recreating the function, instead of editing it. It might be a change in the underlying containers used for new functions.

**Comment by notrab** [comment]
Weird. I'm still getting issues when doing this, even in new projects.

I'll close this and await an invite to the new runtime and see if the issue persists then.
