### ISSUE TITLE
Remove unused npm tags for graphcool

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphcool#763]
It's confusing.

![image](https://user-images.githubusercontent.com/852069/31394843-a0bab24e-addf-11e7-831e-4803a250ee22.png)

**Comment by timsuchanek** [comment]
Unfortunately, you can't remove tags from npm.

**Comment by kbrandwijk** [comment]
It seems like you can:
https://docs.npmjs.com/cli/dist-tag

`npm dist-tags rm graphcool alpha`

**Comment by schickling** [comment]
Done ✅

**Comment by kbrandwijk** [comment]
The problem now is that @next is no longer the version the open beta started out with, and people installing @next now are getting 0.7.0-beta.3, with a different file layout (.graphcoolrc), and different commands (like `modules` removed)... This is still confusing.

I think this would make more sense:
@latest = latest non-beta version
@next = stable open beta release
@somethingelse = nightly?

**Comment by timsuchanek** [comment]
@kbrandwijk The versioning schema is now this:

@latest = latest non-beta version
@next = stable open beta release
@alpha = nightly

I already pushed the latest nightly to @next, but from now on that will go to @alpha
