### ISSUE TITLE
graphcool local up hangs

### ISSUE THREAD

**Issue by rwatts3** [graphcool/graphcool#766]
> When using the graphcool@next package after running graphcool init, then trying to run graphcool local up.

> All containers for the docker-compose proceed as expected except for one.
It’s looking for a docker image titled graphcool/single-server

> Which i have confirmed does not exist on docker hub nor anywhere in this repository.

**Comment by marktani** [comment]
Can you please describe when you run into this error? How to reproduce it?
Thanks! 🙏

**Comment by rwatts3** [comment]
When using the `graphcool@next` package after running graphcool init, then trying to run graphcool local up. 

All containers for the docker-compose proceed as expected except for one. 
It’s looking for a docker image titled `graphcool/single-server`

Which i have confirmed does not exist on docker hub nor anywhere in this repository.

**Comment by rwatts3** [comment]
Today I tested again and the single-server issue is now resolved, however when I run the command `graphcool local up` All containers startup, but the dialog

"Waiting for Graphcool to initialize. This can takeseveral minutes..." displays forever and never leaves the screen.

Also i noticed that when trying to use graphcool local up on windows 7 with docker toolbox aka virtualbox setup, because you are enforcing the port's host to 127.0.0.1 , I cannot access the site outside of the virtualbox environment. The correct way I believe would be to set the host to 0.0.0.0 this should work on both docker toolbox and docker for windows|mac

**Comment by dpetrick** [comment]
Hi @rwatts3, 

we're aware of the hanging issue and have a fix ready, to be deployed soon. The workaround is to kill the container and execute `graphcool local up` again.

I will look into the port bindings soon, thanks for the report.

For the record (and anyone interested reading this), the `graphcool/single-server` issue was an old docker image reference that shouldn't happen anymore with the newest CLI.

Thanks.

**Comment by marktani** [comment]
I created this proposal/feature request: https://github.com/graphcool/graphcool/issues/787 let's continue the discussion about the port bindings there 🙂

**Comment by rwatts3** [comment]
Also , can we also have the ability to configure environment variables for the cluster, as well as possibly changing port / host information. 

For example, I'm using an nginx proxy with letsencrypt to generate ssl keys for my services. 

I need to pass environment variables to each container I spin up in order for it to be detected by the proxy service.

**Comment by dpetrick** [comment]
Yes, that is on our roadmap.

**Comment by sorenbs** [comment]
The original issue is solved, ports are discussed in #787 and environment variables should be discussed in #748 

Thanks for opening this issue @rwatts3

**Comment by rwatts3** [comment]
Thank you
