### ISSUE TITLE
CLI 0.7.0-beta.3 Unable to deploy permission queries

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphcool#768]
Error: `Permission Query is invalid. Could not be parsed. Error Message: Syntax error while parsing GraphQL query. Invalid input \"query ($node_id: ID) q\", expected OperationDefinition, FragmentDefinition or TypeSystemDefinition`

permission query:
```
query ($node_id: ID!) {
  SomeUserExists(filter: {
    id: $node_id
    })
}
```

**Comment by do4gr** [comment]
Is this error being thrown while you deploy or when actually triggering a permission check?

**Comment by kbrandwijk** [comment]
When the permission is triggered. Deploy goes fine.

**Comment by marktani** [comment]
This is a duplicate of #703 and is currently being worked on as discussed here: https://github.com/graphcool/graphcool/issues/602.
