### ISSUE TITLE
Unexpected token function

### ISSUE THREAD

**Issue by atefBB** [graphcool/graphcool#777]
I got this error when using `graphcool init`: 
`C:\Users\...\AppData\Roaming\npm\node_modules\graphcool\node_modules\rwlockfile\lib\rwlockfile.js:9
async function pidActive(pid) {`
 `^^^^^^^^`
`SyntaxError: Unexpected token function`.

Any ideas to deal with it?

**Comment by parronator** [comment]
same here

**Comment by atefBB** [comment]
@parronator solved?

**Comment by marktani** [comment]
This error is thrown when the node version is older, could you please upgrade that to a more recent one?

**Comment by atefBB** [comment]
@marktani I'm using the `v6.11.0` version of nodejs.

**Comment by marktani** [comment]
Could you try to upgrade the version to 8+? :)

**Comment by kbrandwijk** [comment]
Why was the node version check removed?

**Comment by schickling** [comment]
Good question @kbrandwijk - maybe @timsuchanek can add more context?

This problem should be resolved via #623 though.

**Comment by kbrandwijk** [comment]
@schickling See my reply in #623 for why I do not consider that a good solution. Also, it doesn't take away the issue that apparently, there's something in there that requires node 8+, which is strange, given that it's a compiled Typescript project, that could easily be compiled into something compatible with the still very common node 6.x.

**Comment by timsuchanek** [comment]
The check hasn't been removed, just tried it.
Some of the dependencies need node >= 8, we should get rid of them

**Comment by timsuchanek** [comment]
I removed the one dependency that made node 6 fail, from now on node 6 is supported.

**Comment by atefBB** [comment]
@timsuchanek Thank you !
