### ISSUE TITLE
Auth context is always null

### ISSUE THREAD

**Issue by danistefanovic** [graphcool/graphcool#779]
**What is the current behavior?**

When I try to run the [`loggedInUser` query from the authentication example](https://github.com/graphcool/graphcool/tree/master/examples/auth#checking-whether-a-user-is-currently-logged-in-with-the-loggedinuser-query), `event.context.auth` is always `null`.

**Steps to reproduce**

1. Clone/download the [auth example](https://github.com/graphcool/graphcool/tree/master/examples/auth)
2. Deploy with `graphcool deploy`
3. Execute `signupEmailUser` mutation in Playground
4. Copy returned token
5. Prepare `loggedInUser` query in Playground
6. Add HTTP header in Playground: `Authorization`: `<copied token>`
7. Execute query

Query result:
```
{
  "data": {
    "loggedInUser": {
      "id": null
    }
  }
}
``` 

The `loggedInUser` function logs "No auth context". I've added an additional log message to print out the whole context object. `event.context.auth` is indeed `null`.

**What is the expected behavior?**

`event.context.auth` should contain any authentication data.

**Comment by marktani** [comment]
In step 6, you need to set `Authorization: Bearer <token>`, are you doing this?

**Comment by danistefanovic** [comment]
I'm pretty sure I've tried it with `Bearer` and without it. But it seems to work know 👍
