### ISSUE TITLE
Missing information about defining permissions

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool#782]
There is no information in the docs about narrowing down a permission to specific fields.

**Comment by marktani** [comment]
Also see https://github.com/graphcool/graphcool/pull/783 🙂

**Comment by nikolasburk** [comment]
I added field permissions to the example in `graphcool.yml` as well an example in the `Authorization` chapter itself:

- https://github.com/graphcool/graphcool/blob/master/docs/04-Reference/01-Service-Definition/02-graphcool.yml.md#examples-2
- https://github.com/graphcool/graphcool/blob/master/docs/04-Reference/06-Auth/03-Authorization/01-Overview.md#specifying-permissions-in-graphcoolyml
