### ISSUE TITLE
graphcool@next error : modules is not a graphcool command

### ISSUE THREAD

**Issue by rwatts3** [graphcool/graphcool#788]
When running the command `gc modules` it appears the new `graphcool@next` cli does not support graphcool modules. Is this an error, or will modules be deprecated and replaced with an alternative approach ?

**Comment by rwatts3** [comment]
On a second note it appears that add-template is the new modules is this correct ?

**Comment by timsuchanek** [comment]
Thanks for bringing this up @rwatts3!
Yes, the `modules add` command is now being replaced by `add-template`. We will document this better!
