### ISSUE TITLE
Permissions for non-existing relation can be set

### ISSUE THREAD

**Issue by FredyC** [graphcool/graphcool#794]
**What is the current behavior?**
Adding a permission to `graphcool.yml` for a relation that does not exist goes without an error. Running diff silently ignores such permission. This can be troubling in case of a typo or when renaming (#700) relation and forget to rename permission as well.

**Please share the relevant part of your project (GraphQL schema, functions, permissions, ...) for easier reproduction**

```yaml
permissions:
- operation: NonExisting.*
```

**What is the expected behavior?**
Should be considered error for deploy and do not allow to push it through.

**Comment by do4gr** [comment]
Hey, thanks for reporting this. This will be turned into an error on deploy together with trying to set permissions on non-existing models. A fix for this on some of the issues covered here https://github.com/graphcool/graphcool/issues/772 will be out soon.

**Comment by marktani** [comment]
So, let's discuss this further in #772 then. Thanks for bringing this up, @FredyC!
