### ISSUE TITLE
Redact auth token in debug output

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool#798]
When you want to share your debug output from the CLI in the Forum or on Slack, it quickly happens that you include share your auth token (platform token) with everyone.

This should be prevented by redacting the token from the debug output.

**Comment by kbrandwijk** [comment]
See https://github.com/graphcool/graphcool/issues/352 for inspiration (e.g. showing the name of the token)

**Comment by marktani** [comment]
Yep, I specifically created a new issue, because the other one is about function logs.

**Comment by kbrandwijk** [comment]
I know, that's why it's not closed as duplicate :smile:
