### ISSUE TITLE
Include Node interface in Schema file

### ISSUE THREAD

**Issue by pungggi** [graphcool/graphcool#805]
**What is the current behavior?**
I am using syntax Highligther like this
https://github.com/kumarharsh/graphql-for-vscode

Because the https://www.graph.cool/docs/reference/schema/system-artifacts-uhieg2shio/ 
namely the User and File Type implements the Node interface.
Syntax Highlight cannot work.

**What is the expected behavior?**

Include the Node interface in schema file.

This has at least two advantages

1. 
Transparency. The schema becomes clearer without documentation. (By the way I did not find documentation about the Node interface)

2.
Allows for proper Syntax Highlighting.

**Comment by kbrandwijk** [comment]
All fields that are part of the interface should also exist on the Type. So I wonder why that affects syntax highlighting.

**Comment by pungggi** [comment]
@kbrandwijk Because the Node Interface is missing..

**Comment by marktani** [comment]
You need to download the full schema file and point your tool towards that. You can look into https://github.com/graphcool/graphql-config for a nice tool to obtain & sync your schema.
