### ISSUE TITLE
Adapt the CLI `pull` command to work with the new service definitions

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphcool#808]
**What feature do you want to miss?**
The deprecated `pull` command that's still available in the CLI is causing confusion, and will not function properly anymore in some cases anyways.

**How could this feature look like in detail? Tradeoffs?**
Removing all traces from it from the CLI :smile:

**Comment by marktani** [comment]
I think it could still be available, but definitely not under the name `pull`. If you only use `pull` for `read-only` access, it's a useful command. But if you are not aware of all implications you might end up with unwanted writing changes that mess up your project.

**Comment by kbrandwijk** [comment]
I think it's a transition stage. It would be nice to pull all code for an (ejected) project, but it should download the same thing you would get when your downloading the project definition after upgrading the project. That way, it works consistently, and you end up with the same result `gc init` gives you. No .graphcoolrc file, ready to deploy to a new project if needed.

**Comment by timsuchanek** [comment]
The pull command is now completely removed
