### ISSUE TITLE
CLI 0.7.0. adds phantom folders to the build.zip

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphcool#809]
Although it's not breaking anything, the build.zip contains a few empty phantom `src` folders. I suspect it tries to add that folder for every entry in the project file.

![image](https://user-images.githubusercontent.com/852069/31575049-a5500a38-b0dd-11e7-9df5-4106b7b30efd.png)

**Comment by kbrandwijk** [comment]
In addition, as seen in the screenshot, it also contains duplicate files (hello.js), but with different contents.

**Comment by marktani** [comment]
This is fixed in latest alpha 🙂
