### ISSUE TITLE
Error "provided pat is not valid for project [...]"

### ISSUE THREAD

**Issue by richardkall** [graphcool/graphcool#821]
**What is the current behavior?**

Throws an error:

```
code: 4028
message: "The provided pat is not valid for project [...]"
```

Seems to be happen when calling the `generateUserToken` method.

**How to reproduce**

Noticed this error in one of my own projects and was able to reproduce it using the auth example:
https://github.com/graphcool/graphcool/tree/master/examples/auth

**Comment by marktani** [comment]
Thanks, we're looking into this right now 🙂

**Comment by marktani** [comment]
This is already fixed 🙂
