### ISSUE TITLE
Improve "Error: You have defined functions but no node_modules has been found. Please run npm install"

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool#824]
If you have a `package.json`, but you did not specify the right dependencies, you will run `npm install`, but `graphcool deploy` will show the same error again.

I suggest this error message:

> Error: You have defined functions but no node_modules has been found.
> Please make sure you specified all needed dependencies in package.json and run npm install.

**Comment by kbrandwijk** [comment]
When would this error occur. If I have a package.json, but I don't use any modules in my functions, would I still get the error?

**Comment by marktani** [comment]
No, currently this error only occurs if you are requiring modules, but no `node_modules` was found.

**Comment by kbrandwijk** [comment]
Is there a check in place for requiring built-in modules, like 'fs' or 'util'?

**Comment by marktani** [comment]
I haven't tried it, not sure.

**Comment by marktani** [comment]
If that's the case, we should definitely adjust this... 🙂

**Comment by kbrandwijk** [comment]
Just tested it and it fails. Will create a new issue.

**Comment by kbrandwijk** [comment]
Also see https://github.com/graphcool/graphcool/issues/831
