### ISSUE TITLE
Make graphcool-lib multi-service compatible

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool#827]
When writing a function using `graphcool-lib`, it's cumbersome to make it work for different clusters (for example `graphcool-dev` and `shared-eu-west-1`).

**What feature are you missing?**

This could be solved by two ways:

* use environment variable that contains the cluster endpoint
* inject cluster endpoint into `event`

I prefer the second one.

**Comment by marktani** [comment]
also see https://github.com/graphcool/graphcool-lib/issues/12

**Comment by timsuchanek** [comment]
This is implemented in the latest `graphcool-lib@beta`
