### ISSUE TITLE
Use of built-in node module triggers node_modules errors

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphcool#831]
If you require any of the built-in node modules (https://github.com/nodejs/node/tree/master/lib), the following errors are incorrectly triggered:

`You have defined functions but no package.json has been found.`
`You have defined functions but no node_modules has been found`

Example function for easy checking:
```js
const util = require('util')

module.exports = event => {
  console.log(util.inspect(event))
  return {
    data: {
      message: `Hello ${event.data.name || 'World'}`
    }
  }
}
```

**Comment by timsuchanek** [comment]
Built-in modules are now being ignored.
