### ISSUE TITLE
Error after adding a template

### ISSUE THREAD

**Issue by jferrettiboke** [graphcool/graphcool#832]
**What is the current behavior?**

I got an error on my terminal after adding a template. I have `yarn@1.2.1` installed.

```
!    'ENOENT': spawn yarn ENOENT
```

**Please share the relevant part of your project (GraphQL schema, functions, permissions, ...) for easier reproduction**

`graphcool/0.7.0 (windows-x64) node-v8.6.0`

**What is the expected behavior?**

It must add the template with no errors.

**Comment by marktani** [comment]
Closing as duplicate of https://github.com/graphcool/graphcool/issues/813. Thanks for the report! 🙌
