### ISSUE TITLE
Deprecate modules in graphcool.yml

### ISSUE THREAD

**Issue by antho1404** [graphcool/graphcool#841]
**What is the current behavior?**

When I run `gc deploy --target dev` to my local (docker) environment my functions are not deployed and I get the following error message `Could not create serverless function for 'function-xxx'. Ensure that the code is valid`, of course the code is valid and can be deployed on the Graphcool BaaS

**Please share the relevant part of your project (GraphQL schema, functions, permissions, ...) for easier reproduction**

This is a project to reproduce the issue

https://github.com/antho1404/graphcool-dev-deploy

**What is the expected behavior?**

When running the `gc deploy --target dev` command, the functions should be deployed on the local environment and not raise this error or if there is a good reason to have an error have a better error message

**Comment by marktani** [comment]
```
modules: 
  serviceX: app/modelX/graphcool.yml
```

`modules` are not supported anymore. They have been replaced by [Templates](https://github.com/graphcool/graphcool/issues/720).

The invalid key `modules`in `graphcool/yml` should be detected, and a useful error should be shown:

> Unsupported property 'modules' found in graphcool.yml.

**Comment by antho1404** [comment]
Thanks for the quick feedback, I didn't see this new feature I will migrate this right now but yes could be good to add an error message for modules so
