### ISSUE TITLE
Broken link: Push notifications example project is not working

### ISSUE THREAD

**Issue by KevinColemanInc** [graphcool/graphcool#847]
**What is the current behavior?**
https://github.com/graphcool/graphcool/blob/master/examples/README.md
Push notifications link is broken.

**What is the expected behavior?**
it should link to an example push notification project

**Comment by marktani** [comment]
Thanks for the hint, I removed the link. Instead of an example, a push notification template is provided here: https://github.com/graphcool/templates. 🙂
