### ISSUE TITLE
"Cannot read property 'pipesCount' of undefined" when deploying to graphcool-dev using node 8.0

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool#852]
## How to reproduce

```
> git clone https://github.com/wasd171/graphcool-local-function-error.git
> cd graphcool-local-function-error
> graphcool deploy # choose local cluster
```

The output:

```
❯ graphcool deploy
Bundling functions... ⣾
 ▸    Cannot read property 'pipesCount' of undefined
```

```
❯ graphcool version
graphcool/0.7.0 (darwin-x64) node-v8.0.0
```

**Comment by wasd171** [comment]
Using `node@8.7.0` instead of `node@8.0.0` seems to fix this even for `graphcool@0.7.0`!

**Comment by marktani** [comment]
interesting, so this looks to be a problem related to the node version.

**Comment by kbrandwijk** [comment]
See https://github.com/serverless/serverless/issues/3723

**Comment by kbrandwijk** [comment]
The archiver package used to create the build.zip has an issue with node 8, causing exactly this error: https://github.com/archiverjs/node-archiver/issues/236

**Comment by timsuchanek** [comment]
The warning has been added:
https://github.com/graphcool/graphcool/commit/bec478f5a28ea57f64e1b77ec7e0faba2f052221
