### ISSUE TITLE
Custom authentication providers

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool#88]
Offer a custom authentication provider that uses functions for signup/verification of tokens.

**Comment by Noitidart** [comment]
I was thinking of doing this:

On signup:
Client creates hash of password. Hits endpoint, the endpoint stores it. (validation via email using probaly some email service

On Login:
Hash of entered password sent to endpoint, if it matches the hash in database, then it generates a session key and stores it in database, and returns to client the session key.

On page loads:
The session key is compared and if matches the session generated on login, then returns members data. If the session key is bad then member data is not returned so not logged in page is shown. (if user tricks it with fake member data, its ok all they can do is see the logged in content with the data they created, any posts requests with a bad session key will fail).

Does anyone have any ideas on how secure this approach is?

**Comment by Noitidart** [comment]
Oh idea! what I'll do is just create an endpoint on my server. This server will do the validation of the sessionkey, if it is good then it does a curl to graph.cool and returns the response. I can also have my server do any hashing/checking.

The only problem is I pay 40$ a year for my server + domain + database of unlimited data. Graphql alone is 45 a month :( I needed a solution I could hand off and be sustained by kids on student income.

**Comment by marktani** [comment]
What we're rather thinking of is giving you a way to define the needed methods either in the form of microservices (AWS Lambda, Auth0 webtask, micro/now, Azure Functions) or by defining say JavaScript code right in the Console.

So for example you would need to define these methods:

* createUserSecret(email, password): String
* verifySignedToken(token): boolean

Your idea sounds flawed as a malicious client could simply bypass your server and curl Graphcool directly.

**Comment by marktani** [comment]
Similar to #43, this can be further discussed here: https://www.graph.cool/forum/t/feedback-schema-extensions-beta/405.
