### ISSUE TITLE
CLI package.json is missing some dependencies

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphcool#889]
Each of the individual packages of the CLI has its own package.json. Some dependencies are missing in the individual package definitions. For example, `fs-extra` is missing in the package.json for graphcool-cli-core.
This might also be true for other packages, and causes problems in certain edge cases (like conflicting versions already being installed). See https://github.com/graphcool/graphcool/issues/875 for a real-world use case.

**Comment by timsuchanek** [comment]
This is fixed and published at `graphcool@0.8.0-alpha.8`
