### ISSUE TITLE
Specified rootToken not inserted into functions

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphcool#893]
If I create a PAT with the same name as my function (non-Framework Preview project), and inspect the function context, it does not contain my named PAT, but a generated one. This applies to hooks and resolvers.

I have only tested this for an inline function, not a webhook. But if it's also broken for webhooks, that will break a lot of webhooks expecting a specific PAT!

**Comment by marktani** [comment]
This is intended behaviour. More configuration options will be added soon, as discussed in https://github.com/graphcool/graphcool/issues/879.
