### ISSUE TITLE
gc local not starting on linux

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphcool#902]
![image](https://user-images.githubusercontent.com/852069/31769321-60c7c3de-b4d3-11e7-97de-3485297cad43.png)

**Comment by timsuchanek** [comment]
Thanks for reporting @kbrandwijk !
Which version of `docker-compose` are you using?

**Comment by kbrandwijk** [comment]
Apparently an old one (1.8.0). Trying to update it now...

**Comment by kbrandwijk** [comment]
Updated to 1.16.1 and it works.

**Comment by schickling** [comment]
This should be avoided in the future through https://github.com/graphcool/graphcool/issues/904
