### ISSUE TITLE
Parameter 'FunctionName' must not be null

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool#914]
Deploying an update to a function on `graphcool@alpha.9` results into this error message:

> Unable to marshall request to JSON: Unable to marshall request to JSON: Parameter 'FunctionName' must not be null

**Comment by mwickett** [comment]
Seeing this as well on `graphcool/0.8.0-alpha.7`

**Comment by marktani** [comment]
That's right, we're looking into this! 🙂

**Comment by marktani** [comment]
This is now fixed, thanks for bringing this up, @mwickett 🙌
