### ISSUE TITLE
Better database migrations

### ISSUE THREAD

**Issue by antho1404** [graphcool/graphcool#915]
### Problem

I find it quite complicated to deploy a new migration of the types and see over time what migration has been added or this kind of stuff. We can still look into the commits and see what has been added or modified in the `types.graphql` file but it's still complicated.

Moreover I will take a use case I've got few times, let's say we are working on two different features (and two different git branch), each of them add a new migration for exemple
- feature 1 add a model `Type1`
- feature 2 add a model `Type2`

When working on feature 1 we will migrate the schema and our database will have `Type1` but then working on the feature 2, we will migrate again (with a `--force` because we will destroy `Type1`) and we will have the database with only `Type2` which is totally normal in that case
BUT... if we work again on feature 1, we will have loose all the data we added to develop the feature 

### Proposition

One way that may solve this kind of problems will be to do some migration files. A migration file could be something like that :

kind of git diff with the Before that could be used as a rollback and the after that will be the actual migration
`2017-10-19T14:46:06.748Z-add-type1.diff`
```
<<<<<<< Before
=======
type Type1 @model {
  id: ID! @isUnique
  createdAt: DateTime!
  updatedAt: DateTime!
}
>>>>>>> After
```

Or even and I'm pretty sure this is something possible with the `system` api, a file migration file based on graphql

`2017-10-19T14:46:06.748Z-add-type1.graphql`
```
mutation {
  rollback: removeType(name: "Type1") { id }
  migrate: createType(
    name: "Type1",
    fields: [
      { name: "id", type: "ID!", unique: true },
      { name: "createdAt", type: DateTime! },
      { name: "updatedAt", type: DateTime! }
    ]) { id }
}
```

Of course with those migrations we will also save what migrations are deployed for exemple with the date in the file name stored and with that we will be able to switch between two versions with no problem, while we don't rollback the migration, the data are still on the database.

And of course the `types.graphql` file is really important to have but can be just a generated file and shouldn't be edited 

I don't know if this really make sense or maybe just because I've been working with rails for too many years and I'm really use to manage my databases migrations like that.

**Comment by marktani** [comment]
That's a great input, thanks a lot. Also ties in with the findings of #730. We're investigating different approaches thoroughly right now, let's keep the discussion to #730 though 🙂

**Comment by antho1404** [comment]
I had to do one script that follow a bit this logic (only for data migrations) this might maybe be helpful

https://gist.github.com/antho1404/576642a12f07f09f853a42ecf67a45f3
