### ISSUE TITLE
Broken links in the docs: 02-Concepts/04-Auth-&-Security/01-Authentication

### ISSUE THREAD

**Issue by nandito** [graphcool/graphcool#930]
Two links are leading to a non-existing Github repository in the `graphcool/docs/02-Concepts/04-Auth-&-Security/01-Authentication.md` file's Implementing "Login Mechanisms with Serverless Functions" section:

1. existing authentication mechanisms (`https://github.com/graphcool-examples/functions/tree/master/authentication`)
2.  email-and-password-based login mechanism (`https://github.com/graphcool-examples/functions/blob/master/authentication/email-user-management/functions/update-email/schema-extension.graphql`)

**Comment by joestrouth1** [comment]
Adding one more.

`/graphcool/docs/04-Reference/07-API-Gateway/01-Overview.md` contains the following:

> `[Here](../../../examples/gateway-custom-schema)` is an example

When viewed at `https://docs-next.graph.cool/reference/api-gateway/overview-ucoohic9zu` the link is broken.
