### ISSUE TITLE
ENOENT: No such file or directory, stat when running add-template

### ISSUE THREAD

**Issue by peterpme** [graphcool/graphcool#960]
**Current behavior**

```Downloading template graphcool/templates/authentication/email-password from graphcool/templates ... ✔
Path /Users/peter/Projects/tallydrinks/tally-graphcool/src/email-password/ already exists. Overwriting it now.
 ▸    'ENOENT': ENOENT: no such file or directory, stat
 ▸    '/var/folders/_8/y755ywd94_l4pc8ymg8kmjh00000gn/T/cj8z5exny00004i3zkub6x38n/authentication/email-password/src'
```

The items that are supposed to be commented out are not there. 

**Reproduction**

`graphcool add-template graphcool/templates/auth/email-password`

> If your problem can be reproduced with a certain service definition, please create a new GitHub repository with the reproduction instructions.

**Expected behavior?**

Template downloads to folder. Items are in commented out in file.

**Comment by kbrandwijk** [comment]
@peterpme The command output seems to indicate using a different path to add the template. Are you sure the reproduction steps are correct?

**Comment by peterpme** [comment]
Yes, copied it exactly from the documentation

**Comment by marktani** [comment]
Which documentation? What was the command you executed?

**Comment by peterpme** [comment]
https://github.com/graphcool/templates/tree/master/auth/email-password#getting-started

**Comment by marktani** [comment]
I can't reproduce this:

```sh
graphcool init
graphcool add-template graphcool/templates/auth/email-password
```

works just fine. then running

```sh
graphcool add-template graphcool/templates/auth/email-password
```

again, works too:

![image](https://user-images.githubusercontent.com/1780597/31831221-fcc26aa6-b5c2-11e7-896a-14a241cec83d.png)

> '/var/folders/_8/y755ywd94_l4pc8ymg8kmjh00000gn/T/cj8z5exny00004i3zkub6x38n/authentication/email-password/src'

looks to be an issue with an older downloaded template 🤔

**Comment by peterpme** [comment]
hm ok, maybe!

I upgraded a project, downloaded it and ran it. Perhaps that will do it?

Is there any way I can reset something I my end?

**Comment by marktani** [comment]
What's your `graphcool version`?

**Comment by peterpme** [comment]
0.7.0

**Comment by marktani** [comment]
Aw, could you upgrade to `0.8.0`? I think that's the problem 🙂 

```
npm install -g graphcool@next
```

**Comment by peterpme** [comment]
gah, could have sworn I did! Thanks 😘
