### ISSUE TITLE
Newline when importing multiple members breaks deploy

### ISSUE THREAD

**Issue by richardkall** [graphcool/graphcool#962]
When importing multiple items in a function, this works:

```
const { A, B, C } = require('../myFile');
```

This does not work:

```
const {
  A,
  B,
  C
} = require('../myFile');
```

Error:
```
graphcool deploy
 ▸    Cannot read property 'startsWith' of undefined
```

**Comment by kbrandwijk** [comment]
@timsuchanek It seems these regex statements: https://github.com/graphcool/graphcool/blob/master/cli/packages/graphcool-cli-engine/src/ProjectDefinition/ProjectDefinition.ts#L171-L172 needs a multiline option...
