### ISSUE TITLE
Allow to manually create users

### ISSUE THREAD

**Issue by sedubois** [graphcool/graphcool#99]
There used to be the possibility to create users from the console, but this disappeared and I'd like to get it back.

This is my scenario: I have an app with some special users who have content to provide (e.g an artist who has songs). I want to create a user which represents this content provider, even though I'm not that person.

Later on, this person might connect by themselves (through Auth0 as I've configured it now) and edit their own data. Therefore, I don't want to have separate User and e.g ContentProvider tables.

The current situation is actually quite annoying, as I'm forced to indeed create separate tables, and therefore create separate Profile pages pointing to these different tables even though they share common elements.

There should be a way to bypass authentication, and yet allow someone to take over a User later on.

**Comment by marktani** [comment]
Thanks for this suggestion! We're looking at ways to refactor the authentication flow using [interfaces](https://github.com/graphcool/feature-requests/issues/83) and will consider this annoyance :)

**Comment by sedubois** [comment]
Thanks @marktani but that feature is on your backlog, i.e several months away. The current way really is more cumbersome than it should be, duplicating both the models and the code and trying to keep everything in sync 😢 I hope a convenient workaround could be found sooner than that.

**Comment by marktani** [comment]
We are currently working on improving the email provider #39 and noticed some possible approaches that would fix your problem as well. I'll keep this issue updated with our findings.

**Comment by sedubois** [comment]
Thank you 😊

**Comment by sedubois** [comment]
Thank you 😊

**Comment by kimf** [comment]
Is it not possible through the playground?

**Comment by marktani** [comment]
it's possible, to do that but you have to supply authentication information upon creation. This is not so simple with Auth0 because you need a valid idToken currently.

**Comment by marktani** [comment]
Somewhat related to #117

**Comment by marktani** [comment]
With custom authentication, this is now possible. Please join the discussion here: https://www.graph.cool/forum/t/feedback-schema-extensions-beta/405.
