### ISSUE TITLE
Support require syntax for modules

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool#997]
Currently, using `require` in a function results in this error when deploying:

![image](https://user-images.githubusercontent.com/1780597/31861152-22bd822a-b728-11e7-844f-33b350574fe1.png)

This should be supported.

**Comment by kbrandwijk** [comment]
I can require any module I want using the require syntax. I only get the startsWith error if I use any line breaks, for which I have already submitted a PR.

**Comment by marktani** [comment]
I did something like this:

```js
import sendgrid = require('@sendgrid/mail')
```

which resulted in that error.

**Comment by kbrandwijk** [comment]
That's not a supported syntax at all. It's either `import sendgrid from '@sendgrid/mail'` or `const sendgrid = require('@sendgrid/mail'`.

**Comment by timsuchanek** [comment]
@kbrandwijk that's true, it's a mix of both, but TypeScript supports it :) https://www.typescriptlang.org/docs/handbook/modules.html

**Comment by marktani** [comment]
I got it from here: https://stackoverflow.com/a/35310280/1176596

**Comment by timsuchanek** [comment]
The regex is only there to protect legacy projects from breaking, so it's ok when it's just ignoring this.

**Comment by kbrandwijk** [comment]
As the handbook and the so link say, it's only possible with modules exported using the `export =` syntax.

**Comment by Tyguy160** [comment]
I seem to be having this issue as well. I've been following [this tutorial](https://www.howtographql.com/graphql-js/4-adding-a-database/) from Prisma. My repository with the code is [here](https://github.com/Tyguy160/hackernews-node-tutorial). I only have one line of code using `require` and I can't switch it to `import` without crashing the backend server. Even if I comment that line out, `prisma generate` still fails. Any ideas what the issue may be?

Here is my error code from running `prisma generate`:

`TypeError: Cannot read property 'startsWith' of undefined
    at GenereateCommand.<anonymous> (/usr/local/lib/node_modules/prisma/node_modules/prisma-cli-core/src/commands/generate/generate.ts:99:39)
    at step (/usr/local/lib/node_modules/prisma/node_modules/prisma-cli-core/dist/commands/generate/generate.js:45:23)
    at Object.next (/usr/local/lib/node_modules/prisma/node_modules/prisma-cli-core/dist/commands/generate/generate.js:26:53)
    at fulfilled (/usr/local/lib/node_modules/prisma/node_modules/prisma-cli-core/dist/commands/generate/generate.js:17:58)
    at <anonymous>
Exiting with code: 1`
